// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer15_out_dout,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_empty_n,
        layer15_out_read,
        layer17_out_din,
        layer17_out_num_data_valid,
        layer17_out_fifo_cap,
        layer17_out_full_n,
        layer17_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [335:0] layer15_out_dout;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;
input   layer15_out_empty_n;
output   layer15_out_read;
output  [479:0] layer17_out_din;
input  [1:0] layer17_out_num_data_valid;
input  [1:0] layer17_out_fifo_cap;
input   layer17_out_full_n;
output   layer17_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer15_out_read;
reg layer17_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer15_out_blk_n;
reg    layer17_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [25:0] mul_ln42_fu_158_p2;
reg   [25:0] mul_ln42_reg_711;
wire    ap_CS_fsm_state2;
wire   [25:0] mul_ln42_1_fu_157_p2;
reg   [25:0] mul_ln42_1_reg_715;
wire   [25:0] mul_ln42_2_fu_154_p2;
reg   [25:0] mul_ln42_2_reg_719;
wire   [26:0] mul_ln73_fu_166_p2;
reg   [26:0] mul_ln73_reg_723;
wire   [25:0] mul_ln42_3_fu_164_p2;
reg   [25:0] mul_ln42_3_reg_727;
wire   [25:0] mul_ln42_4_fu_160_p2;
reg   [25:0] mul_ln42_4_reg_731;
wire   [26:0] mul_ln73_1_fu_163_p2;
reg   [26:0] mul_ln73_1_reg_735;
wire   [25:0] mul_ln42_5_fu_165_p2;
reg   [25:0] mul_ln42_5_reg_739;
reg  signed [20:0] a_reg_1331;
reg    ap_block_state1;
reg  signed [20:0] a_6_reg_1336;
reg  signed [20:0] a_7_reg_1341;
reg  signed [20:0] a_8_reg_1346;
reg  signed [20:0] a_9_reg_1351;
reg  signed [20:0] a_1_reg_1357;
reg  signed [20:0] a_2_reg_1363;
reg  signed [20:0] a_3_reg_1368;
reg  signed [20:0] a_4_reg_1373;
reg  signed [20:0] a_5_reg_1378;
reg  signed [20:0] a_11_reg_1384;
reg  signed [20:0] a_10_reg_1389;
wire   [20:0] trunc_ln73_fu_864_p1;
reg   [20:0] trunc_ln73_reg_1395;
reg   [20:0] tmp_s_reg_1401;
reg   [20:0] tmp_9_reg_1407;
reg   [20:0] tmp_10_reg_1413;
wire   [25:0] add_ln42_17_fu_930_p2;
reg   [25:0] add_ln42_17_reg_1419;
wire   [25:0] add_ln42_fu_972_p2;
reg   [25:0] add_ln42_reg_1424;
wire   [25:0] add_ln42_20_fu_1018_p2;
reg   [25:0] add_ln42_20_reg_1429;
wire   [25:0] add_ln42_21_fu_1052_p2;
reg   [25:0] add_ln42_21_reg_1434;
wire   [25:0] add_ln42_22_fu_1082_p2;
reg   [25:0] add_ln42_22_reg_1439;
wire   [25:0] add_ln42_25_fu_1128_p2;
reg   [25:0] add_ln42_25_reg_1444;
wire   [25:0] add_ln42_26_fu_1162_p2;
reg   [25:0] add_ln42_26_reg_1449;
wire   [25:0] add_ln42_28_fu_1196_p2;
reg   [25:0] add_ln42_28_reg_1454;
wire   [5:0] mul_ln42_2_fu_154_p1;
wire   [5:0] mul_ln42_1_fu_157_p1;
wire   [5:0] mul_ln42_fu_158_p1;
wire   [5:0] mul_ln42_4_fu_160_p1;
wire   [5:0] mul_ln73_1_fu_163_p1;
wire   [5:0] mul_ln42_3_fu_164_p1;
wire   [5:0] mul_ln42_5_fu_165_p1;
wire   [5:0] mul_ln73_fu_166_p1;
wire   [24:0] shl_ln_fu_898_p3;
wire   [21:0] shl_ln73_6_fu_909_p3;
wire  signed [22:0] sext_ln42_23_fu_916_p1;
wire   [22:0] add_ln42_29_fu_920_p2;
wire  signed [25:0] sext_ln42_24_fu_926_p1;
wire  signed [25:0] sext_ln73_fu_905_p1;
wire   [24:0] and_ln_fu_940_p3;
wire   [21:0] and_ln73_s_fu_951_p3;
wire  signed [22:0] sext_ln42_25_fu_958_p1;
wire   [22:0] add_ln42_30_fu_962_p2;
wire  signed [25:0] sext_ln42_26_fu_968_p1;
wire  signed [25:0] sext_ln73_26_fu_947_p1;
wire   [24:0] and_ln73_17_fu_986_p3;
wire   [22:0] and_ln73_18_fu_997_p3;
wire  signed [23:0] sext_ln42_27_fu_1004_p1;
wire   [23:0] add_ln42_31_fu_1008_p2;
wire  signed [25:0] sext_ln42_28_fu_1014_p1;
wire  signed [25:0] sext_ln73_27_fu_993_p1;
wire   [24:0] shl_ln73_7_fu_1031_p3;
wire  signed [21:0] sext_ln73_29_fu_1028_p1;
wire   [21:0] add_ln42_32_fu_1042_p2;
wire  signed [25:0] sext_ln42_29_fu_1048_p1;
wire  signed [25:0] sext_ln73_30_fu_1038_p1;
wire   [24:0] shl_ln73_8_fu_1061_p3;
wire  signed [21:0] sext_ln73_31_fu_1058_p1;
wire   [21:0] add_ln42_33_fu_1072_p2;
wire  signed [25:0] sext_ln42_30_fu_1078_p1;
wire  signed [25:0] sext_ln73_32_fu_1068_p1;
wire   [24:0] and_ln73_19_fu_1096_p3;
wire   [21:0] and_ln73_20_fu_1107_p3;
wire  signed [22:0] sext_ln42_31_fu_1114_p1;
wire   [22:0] add_ln42_34_fu_1118_p2;
wire  signed [25:0] sext_ln42_32_fu_1124_p1;
wire  signed [25:0] sext_ln73_33_fu_1103_p1;
wire   [24:0] shl_ln73_9_fu_1141_p3;
wire  signed [21:0] sext_ln73_35_fu_1138_p1;
wire   [21:0] add_ln42_35_fu_1152_p2;
wire  signed [25:0] sext_ln42_33_fu_1158_p1;
wire  signed [25:0] sext_ln73_36_fu_1148_p1;
wire   [24:0] shl_ln73_s_fu_1175_p3;
wire  signed [21:0] sext_ln73_37_fu_1172_p1;
wire   [21:0] add_ln42_36_fu_1186_p2;
wire  signed [25:0] sext_ln42_34_fu_1192_p1;
wire  signed [25:0] sext_ln73_38_fu_1182_p1;
wire   [25:0] add_ln42_16_fu_1205_p2;
wire   [25:0] add_ln42_18_fu_1215_p2;
wire   [25:0] add_ln42_19_fu_1225_p2;
wire   [25:0] add_ln42_23_fu_1241_p2;
wire   [25:0] add_ln42_24_fu_1251_p2;
wire   [25:0] add_ln42_27_fu_1264_p2;
wire  signed [29:0] sext_ln70_5_fu_1270_p1;
wire  signed [29:0] sext_ln46_8_fu_1288_p1;
wire  signed [29:0] sext_ln46_7_fu_1284_p1;
wire  signed [29:0] sext_ln42_18_fu_1261_p1;
wire  signed [29:0] sext_ln70_4_fu_1257_p1;
wire  signed [29:0] sext_ln70_3_fu_1247_p1;
wire  signed [29:0] sext_ln46_6_fu_1281_p1;
wire  signed [29:0] sext_ln42_15_fu_1238_p1;
wire  signed [29:0] sext_ln46_5_fu_1277_p1;
wire  signed [29:0] sext_ln42_14_fu_1235_p1;
wire  signed [29:0] sext_ln70_2_fu_1231_p1;
wire  signed [29:0] sext_ln70_1_fu_1221_p1;
wire  signed [29:0] sext_ln46_fu_1274_p1;
wire  signed [29:0] sext_ln70_fu_1211_p1;
wire  signed [29:0] sext_ln42_fu_1202_p1;
wire   [475:0] tmp_fu_1291_p17;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1058(
    .din0(a_7_reg_1341),
    .din1(mul_ln42_2_fu_154_p1),
    .dout(mul_ln42_2_fu_154_p2)
);

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1059(
    .din0(a_6_reg_1336),
    .din1(mul_ln42_1_fu_157_p1),
    .dout(mul_ln42_1_fu_157_p2)
);

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1060(
    .din0(a_reg_1331),
    .din1(mul_ln42_fu_158_p1),
    .dout(mul_ln42_fu_158_p2)
);

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1061(
    .din0(a_3_reg_1368),
    .din1(mul_ln42_4_fu_160_p1),
    .dout(mul_ln42_4_fu_160_p2)
);

myproject_mul_21s_6ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 27 ))
mul_21s_6ns_27_1_1_U1062(
    .din0(a_4_reg_1373),
    .din1(mul_ln73_1_fu_163_p1),
    .dout(mul_ln73_1_fu_163_p2)
);

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1063(
    .din0(a_2_reg_1363),
    .din1(mul_ln42_3_fu_164_p1),
    .dout(mul_ln42_3_fu_164_p2)
);

myproject_mul_21s_6ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 26 ))
mul_21s_6ns_26_1_1_U1064(
    .din0(a_11_reg_1384),
    .din1(mul_ln42_5_fu_165_p1),
    .dout(mul_ln42_5_fu_165_p2)
);

myproject_mul_21s_6ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 27 ))
mul_21s_6ns_27_1_1_U1065(
    .din0(a_8_reg_1346),
    .din1(mul_ln73_fu_166_p1),
    .dout(mul_ln73_fu_166_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        a_10_reg_1389 <= {{layer15_out_dout[335:315]}};
        a_11_reg_1384 <= {{layer15_out_dout[314:294]}};
        a_1_reg_1357 <= {{layer15_out_dout[188:168]}};
        a_2_reg_1363 <= {{layer15_out_dout[209:189]}};
        a_3_reg_1368 <= {{layer15_out_dout[230:210]}};
        a_4_reg_1373 <= {{layer15_out_dout[272:252]}};
        a_5_reg_1378 <= {{layer15_out_dout[293:273]}};
        a_6_reg_1336 <= {{layer15_out_dout[83:63]}};
        a_7_reg_1341 <= {{layer15_out_dout[104:84]}};
        a_8_reg_1346 <= {{layer15_out_dout[146:126]}};
        a_9_reg_1351 <= {{layer15_out_dout[167:147]}};
        a_reg_1331 <= {{layer15_out_dout[41:21]}};
        tmp_10_reg_1413 <= {{layer15_out_dout[251:231]}};
        tmp_9_reg_1407 <= {{layer15_out_dout[125:105]}};
        tmp_s_reg_1401 <= {{layer15_out_dout[62:42]}};
        trunc_ln73_reg_1395 <= trunc_ln73_fu_864_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln42_17_reg_1419[25 : 1] <= add_ln42_17_fu_930_p2[25 : 1];
        add_ln42_20_reg_1429[25 : 2] <= add_ln42_20_fu_1018_p2[25 : 2];
        add_ln42_21_reg_1434 <= add_ln42_21_fu_1052_p2;
        add_ln42_22_reg_1439 <= add_ln42_22_fu_1082_p2;
        add_ln42_25_reg_1444[25 : 1] <= add_ln42_25_fu_1128_p2[25 : 1];
        add_ln42_26_reg_1449 <= add_ln42_26_fu_1162_p2;
        add_ln42_28_reg_1454 <= add_ln42_28_fu_1196_p2;
        add_ln42_reg_1424[25 : 1] <= add_ln42_fu_972_p2[25 : 1];
        mul_ln42_1_reg_715 <= mul_ln42_1_fu_157_p2;
        mul_ln42_2_reg_719 <= mul_ln42_2_fu_154_p2;
        mul_ln42_3_reg_727 <= mul_ln42_3_fu_164_p2;
        mul_ln42_4_reg_731 <= mul_ln42_4_fu_160_p2;
        mul_ln42_5_reg_739 <= mul_ln42_5_fu_165_p2;
        mul_ln42_reg_711 <= mul_ln42_fu_158_p2;
        mul_ln73_1_reg_735 <= mul_ln73_1_fu_163_p2;
        mul_ln73_reg_723 <= mul_ln73_fu_166_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer17_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_blk_n = layer15_out_empty_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_read = 1'b1;
    end else begin
        layer15_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer17_out_blk_n = layer17_out_full_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer17_out_write = 1'b1;
    end else begin
        layer17_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_16_fu_1205_p2 = ($signed(mul_ln42_reg_711) + $signed(26'd67094528));

assign add_ln42_17_fu_930_p2 = ($signed(sext_ln42_24_fu_926_p1) + $signed(sext_ln73_fu_905_p1));

assign add_ln42_18_fu_1215_p2 = ($signed(mul_ln42_1_reg_715) + $signed(26'd67090432));

assign add_ln42_19_fu_1225_p2 = ($signed(mul_ln42_2_reg_719) + $signed(26'd67098624));

assign add_ln42_20_fu_1018_p2 = ($signed(sext_ln42_28_fu_1014_p1) + $signed(sext_ln73_27_fu_993_p1));

assign add_ln42_21_fu_1052_p2 = ($signed(sext_ln42_29_fu_1048_p1) + $signed(sext_ln73_30_fu_1038_p1));

assign add_ln42_22_fu_1082_p2 = ($signed(sext_ln42_30_fu_1078_p1) + $signed(sext_ln73_32_fu_1068_p1));

assign add_ln42_23_fu_1241_p2 = (mul_ln42_3_reg_727 + 26'd12288);

assign add_ln42_24_fu_1251_p2 = ($signed(mul_ln42_4_reg_731) + $signed(26'd67104768));

assign add_ln42_25_fu_1128_p2 = ($signed(sext_ln42_32_fu_1124_p1) + $signed(sext_ln73_33_fu_1103_p1));

assign add_ln42_26_fu_1162_p2 = ($signed(sext_ln42_33_fu_1158_p1) + $signed(sext_ln73_36_fu_1148_p1));

assign add_ln42_27_fu_1264_p2 = ($signed(mul_ln42_5_reg_739) + $signed(26'd67104768));

assign add_ln42_28_fu_1196_p2 = ($signed(sext_ln42_34_fu_1192_p1) + $signed(sext_ln73_38_fu_1182_p1));

assign add_ln42_29_fu_920_p2 = ($signed(sext_ln42_23_fu_916_p1) + $signed(23'd8374272));

assign add_ln42_30_fu_962_p2 = ($signed(sext_ln42_25_fu_958_p1) + $signed(23'd8372224));

assign add_ln42_31_fu_1008_p2 = ($signed(sext_ln42_27_fu_1004_p1) + $signed(24'd8192));

assign add_ln42_32_fu_1042_p2 = ($signed(sext_ln73_29_fu_1028_p1) + $signed(22'd8192));

assign add_ln42_33_fu_1072_p2 = ($signed(sext_ln73_31_fu_1058_p1) + $signed(22'd4182016));

assign add_ln42_34_fu_1118_p2 = ($signed(sext_ln42_31_fu_1114_p1) + $signed(23'd2048));

assign add_ln42_35_fu_1152_p2 = ($signed(sext_ln73_35_fu_1138_p1) + $signed(22'd4188160));

assign add_ln42_36_fu_1186_p2 = ($signed(sext_ln73_37_fu_1172_p1) + $signed(22'd4192256));

assign add_ln42_fu_972_p2 = ($signed(sext_ln42_26_fu_968_p1) + $signed(sext_ln73_26_fu_947_p1));

assign and_ln73_17_fu_986_p3 = {{tmp_9_reg_1407}, {4'd0}};

assign and_ln73_18_fu_997_p3 = {{tmp_9_reg_1407}, {2'd0}};

assign and_ln73_19_fu_1096_p3 = {{tmp_10_reg_1413}, {4'd0}};

assign and_ln73_20_fu_1107_p3 = {{tmp_10_reg_1413}, {1'd0}};

assign and_ln73_s_fu_951_p3 = {{tmp_s_reg_1401}, {1'd0}};

assign and_ln_fu_940_p3 = {{tmp_s_reg_1401}, {4'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer15_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer17_out_din = $signed(tmp_fu_1291_p17);

assign mul_ln42_1_fu_157_p1 = 26'd19;

assign mul_ln42_2_fu_154_p1 = 26'd21;

assign mul_ln42_3_fu_164_p1 = 26'd23;

assign mul_ln42_4_fu_160_p1 = 26'd22;

assign mul_ln42_5_fu_165_p1 = 26'd21;

assign mul_ln42_fu_158_p1 = 26'd23;

assign mul_ln73_1_fu_163_p1 = 27'd19;

assign mul_ln73_fu_166_p1 = 27'd23;

assign sext_ln42_14_fu_1235_p1 = $signed(add_ln42_20_reg_1429);

assign sext_ln42_15_fu_1238_p1 = $signed(add_ln42_21_reg_1434);

assign sext_ln42_18_fu_1261_p1 = $signed(add_ln42_25_reg_1444);

assign sext_ln42_23_fu_916_p1 = $signed(shl_ln73_6_fu_909_p3);

assign sext_ln42_24_fu_926_p1 = $signed(add_ln42_29_fu_920_p2);

assign sext_ln42_25_fu_958_p1 = $signed(and_ln73_s_fu_951_p3);

assign sext_ln42_26_fu_968_p1 = $signed(add_ln42_30_fu_962_p2);

assign sext_ln42_27_fu_1004_p1 = $signed(and_ln73_18_fu_997_p3);

assign sext_ln42_28_fu_1014_p1 = $signed(add_ln42_31_fu_1008_p2);

assign sext_ln42_29_fu_1048_p1 = $signed(add_ln42_32_fu_1042_p2);

assign sext_ln42_30_fu_1078_p1 = $signed(add_ln42_33_fu_1072_p2);

assign sext_ln42_31_fu_1114_p1 = $signed(and_ln73_20_fu_1107_p3);

assign sext_ln42_32_fu_1124_p1 = $signed(add_ln42_34_fu_1118_p2);

assign sext_ln42_33_fu_1158_p1 = $signed(add_ln42_35_fu_1152_p2);

assign sext_ln42_34_fu_1192_p1 = $signed(add_ln42_36_fu_1186_p2);

assign sext_ln42_fu_1202_p1 = $signed(add_ln42_17_reg_1419);

assign sext_ln46_5_fu_1277_p1 = $signed(mul_ln73_reg_723);

assign sext_ln46_6_fu_1281_p1 = $signed(add_ln42_22_reg_1439);

assign sext_ln46_7_fu_1284_p1 = $signed(mul_ln73_1_reg_735);

assign sext_ln46_8_fu_1288_p1 = $signed(add_ln42_26_reg_1449);

assign sext_ln46_fu_1274_p1 = $signed(add_ln42_reg_1424);

assign sext_ln70_1_fu_1221_p1 = $signed(add_ln42_18_fu_1215_p2);

assign sext_ln70_2_fu_1231_p1 = $signed(add_ln42_19_fu_1225_p2);

assign sext_ln70_3_fu_1247_p1 = $signed(add_ln42_23_fu_1241_p2);

assign sext_ln70_4_fu_1257_p1 = $signed(add_ln42_24_fu_1251_p2);

assign sext_ln70_5_fu_1270_p1 = $signed(add_ln42_27_fu_1264_p2);

assign sext_ln70_fu_1211_p1 = $signed(add_ln42_16_fu_1205_p2);

assign sext_ln73_26_fu_947_p1 = $signed(and_ln_fu_940_p3);

assign sext_ln73_27_fu_993_p1 = $signed(and_ln73_17_fu_986_p3);

assign sext_ln73_29_fu_1028_p1 = a_9_reg_1351;

assign sext_ln73_30_fu_1038_p1 = $signed(shl_ln73_7_fu_1031_p3);

assign sext_ln73_31_fu_1058_p1 = a_1_reg_1357;

assign sext_ln73_32_fu_1068_p1 = $signed(shl_ln73_8_fu_1061_p3);

assign sext_ln73_33_fu_1103_p1 = $signed(and_ln73_19_fu_1096_p3);

assign sext_ln73_35_fu_1138_p1 = a_5_reg_1378;

assign sext_ln73_36_fu_1148_p1 = $signed(shl_ln73_9_fu_1141_p3);

assign sext_ln73_37_fu_1172_p1 = a_10_reg_1389;

assign sext_ln73_38_fu_1182_p1 = $signed(shl_ln73_s_fu_1175_p3);

assign sext_ln73_fu_905_p1 = $signed(shl_ln_fu_898_p3);

assign shl_ln73_6_fu_909_p3 = {{trunc_ln73_reg_1395}, {1'd0}};

assign shl_ln73_7_fu_1031_p3 = {{a_9_reg_1351}, {4'd0}};

assign shl_ln73_8_fu_1061_p3 = {{a_1_reg_1357}, {4'd0}};

assign shl_ln73_9_fu_1141_p3 = {{a_5_reg_1378}, {4'd0}};

assign shl_ln73_s_fu_1175_p3 = {{a_10_reg_1389}, {4'd0}};

assign shl_ln_fu_898_p3 = {{trunc_ln73_reg_1395}, {4'd0}};

assign start_out = real_start;

assign tmp_fu_1291_p17 = {{{{{{{{{{{{{{{{add_ln42_28_reg_1454}, {sext_ln70_5_fu_1270_p1}}, {sext_ln46_8_fu_1288_p1}}, {sext_ln46_7_fu_1284_p1}}, {sext_ln42_18_fu_1261_p1}}, {sext_ln70_4_fu_1257_p1}}, {sext_ln70_3_fu_1247_p1}}, {sext_ln46_6_fu_1281_p1}}, {sext_ln42_15_fu_1238_p1}}, {sext_ln46_5_fu_1277_p1}}, {sext_ln42_14_fu_1235_p1}}, {sext_ln70_2_fu_1231_p1}}, {sext_ln70_1_fu_1221_p1}}, {sext_ln46_fu_1274_p1}}, {sext_ln70_fu_1211_p1}}, {sext_ln42_fu_1202_p1}};

assign trunc_ln73_fu_864_p1 = layer15_out_dout[20:0];

always @ (posedge ap_clk) begin
    add_ln42_17_reg_1419[0] <= 1'b0;
    add_ln42_reg_1424[0] <= 1'b0;
    add_ln42_20_reg_1429[1:0] <= 2'b00;
    add_ln42_25_reg_1444[0] <= 1'b0;
end

endmodule //myproject_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_s
