// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer19_out_dout,
        layer19_out_num_data_valid,
        layer19_out_fifo_cap,
        layer19_out_empty_n,
        layer19_out_read,
        layer21_out_TDATA,
        layer21_out_TVALID,
        layer21_out_TREADY
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [209:0] layer19_out_dout;
input  [1:0] layer19_out_num_data_valid;
input  [1:0] layer19_out_fifo_cap;
input   layer19_out_empty_n;
output   layer19_out_read;
output  [79:0] layer21_out_TDATA;
output   layer21_out_TVALID;
input   layer21_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer19_out_read;
reg layer21_out_TVALID;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] exp_table_address0;
reg    exp_table_ce0;
wire   [16:0] exp_table_q0;
reg   [9:0] exp_table_address1;
reg    exp_table_ce1;
wire   [16:0] exp_table_q1;
wire   [9:0] exp_table_address2;
reg    exp_table_ce2;
wire   [16:0] exp_table_q2;
wire   [9:0] exp_table_address3;
reg    exp_table_ce3;
wire   [16:0] exp_table_q3;
wire   [9:0] exp_table_address4;
reg    exp_table_ce4;
wire   [16:0] exp_table_q4;
wire   [9:0] exp_table_address5;
reg    exp_table_ce5;
wire   [16:0] exp_table_q5;
wire   [9:0] exp_table_address6;
reg    exp_table_ce6;
wire   [16:0] exp_table_q6;
wire   [9:0] exp_table_address7;
reg    exp_table_ce7;
wire   [16:0] exp_table_q7;
wire   [9:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
reg    layer19_out_blk_n;
reg    layer21_out_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire  signed [20:0] data_array_fu_644_p1;
reg  signed [20:0] data_array_reg_2340;
wire  signed [20:0] data_array_1_fu_648_p4;
reg  signed [20:0] data_array_1_reg_2345;
wire  signed [20:0] data_array_2_fu_658_p4;
reg  signed [20:0] data_array_2_reg_2350;
wire  signed [20:0] data_array_3_fu_668_p4;
reg  signed [20:0] data_array_3_reg_2355;
wire  signed [20:0] data_array_4_fu_678_p4;
reg  signed [20:0] data_array_4_reg_2360;
wire  signed [20:0] data_array_5_fu_688_p4;
reg  signed [20:0] data_array_5_reg_2365;
wire  signed [20:0] data_array_6_fu_698_p4;
reg  signed [20:0] data_array_6_reg_2370;
wire  signed [20:0] data_array_7_fu_708_p4;
reg  signed [20:0] data_array_7_reg_2375;
reg  signed [20:0] data_array_8_reg_2380;
reg  signed [20:0] data_array_9_reg_2387;
wire   [20:0] select_ln66_fu_750_p3;
reg   [20:0] select_ln66_reg_2394;
wire   [20:0] select_ln66_1_fu_770_p3;
reg   [20:0] select_ln66_1_reg_2400;
wire   [20:0] select_ln66_3_fu_790_p3;
reg   [20:0] select_ln66_3_reg_2406;
wire   [20:0] select_ln66_4_fu_810_p3;
reg   [20:0] select_ln66_4_reg_2412;
wire   [20:0] select_ln66_6_fu_862_p3;
reg   [20:0] select_ln66_6_reg_2418;
wire    ap_CS_fsm_state2;
wire   [20:0] select_ln66_7_fu_880_p3;
reg   [20:0] select_ln66_7_reg_2423;
wire   [0:0] icmp_ln66_8_fu_886_p2;
reg   [0:0] icmp_ln66_8_reg_2428;
wire    ap_CS_fsm_state3;
wire   [9:0] select_ln215_17_fu_1603_p3;
reg   [9:0] select_ln215_17_reg_2473;
wire   [9:0] select_ln215_19_fu_1629_p3;
reg   [9:0] select_ln215_19_reg_2478;
reg   [16:0] exp_res_reg_2483;
wire    ap_CS_fsm_state4;
reg   [16:0] exp_res_1_reg_2488;
reg   [16:0] exp_res_2_reg_2493;
reg   [16:0] exp_res_3_reg_2498;
reg   [16:0] exp_res_4_reg_2503;
reg   [16:0] exp_res_5_reg_2508;
reg   [16:0] exp_res_6_reg_2513;
reg   [16:0] exp_res_7_reg_2518;
wire   [17:0] add_ln51_10_fu_1713_p2;
reg   [17:0] add_ln51_10_reg_2533;
reg   [0:0] tmp_32_reg_2539;
reg   [0:0] tmp_33_reg_2546;
wire   [17:0] add_ln51_11_fu_1809_p2;
reg   [17:0] add_ln51_11_reg_2553;
reg   [0:0] tmp_36_reg_2559;
reg   [0:0] tmp_37_reg_2566;
reg   [16:0] exp_res_8_reg_2573;
wire    ap_CS_fsm_state5;
reg   [16:0] exp_res_9_reg_2578;
reg   [0:0] tmp_41_reg_2583;
reg   [0:0] tmp_42_reg_2590;
reg   [9:0] tmp_9_reg_2597;
wire    ap_CS_fsm_state6;
reg   [17:0] inv_exp_sum_reg_2608;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln225_fu_1363_p1;
wire   [63:0] zext_ln225_1_fu_1394_p1;
wire   [63:0] zext_ln225_2_fu_1425_p1;
wire   [63:0] zext_ln225_3_fu_1456_p1;
wire   [63:0] zext_ln225_4_fu_1487_p1;
wire   [63:0] zext_ln225_5_fu_1518_p1;
wire   [63:0] zext_ln225_6_fu_1549_p1;
wire   [63:0] zext_ln225_7_fu_1580_p1;
wire   [63:0] zext_ln225_8_fu_1637_p1;
wire   [63:0] zext_ln225_9_fu_1641_p1;
wire   [63:0] zext_ln235_fu_2157_p1;
reg    ap_block_state1;
wire  signed [17:0] mul_ln244_fu_273_p0;
wire  signed [23:0] sext_ln244_fu_2162_p1;
wire   [16:0] mul_ln244_fu_273_p1;
wire  signed [17:0] mul_ln244_2_fu_274_p0;
wire   [16:0] mul_ln244_2_fu_274_p1;
wire  signed [17:0] mul_ln244_4_fu_275_p0;
wire   [16:0] mul_ln244_4_fu_275_p1;
wire  signed [17:0] mul_ln244_6_fu_276_p0;
wire   [16:0] mul_ln244_6_fu_276_p1;
wire  signed [17:0] mul_ln244_3_fu_277_p0;
wire   [16:0] mul_ln244_3_fu_277_p1;
wire  signed [17:0] mul_ln244_7_fu_278_p0;
wire   [16:0] mul_ln244_7_fu_278_p1;
wire  signed [17:0] mul_ln244_5_fu_279_p0;
wire   [16:0] mul_ln244_5_fu_279_p1;
wire  signed [17:0] mul_ln244_1_fu_280_p0;
wire   [16:0] mul_ln244_1_fu_280_p1;
wire  signed [17:0] mul_ln244_8_fu_281_p0;
wire   [16:0] mul_ln244_8_fu_281_p1;
wire  signed [17:0] mul_ln244_9_fu_282_p0;
wire   [16:0] mul_ln244_9_fu_282_p1;
wire   [0:0] icmp_ln66_fu_738_p2;
wire   [0:0] xor_ln66_fu_744_p2;
wire   [0:0] icmp_ln66_1_fu_758_p2;
wire   [0:0] xor_ln66_1_fu_764_p2;
wire   [0:0] icmp_ln66_3_fu_778_p2;
wire   [0:0] xor_ln66_3_fu_784_p2;
wire   [0:0] icmp_ln66_4_fu_798_p2;
wire   [0:0] xor_ln66_4_fu_804_p2;
wire   [0:0] icmp_ln66_2_fu_818_p2;
wire   [0:0] xor_ln66_2_fu_822_p2;
wire   [0:0] icmp_ln66_5_fu_834_p2;
wire   [0:0] xor_ln66_5_fu_838_p2;
wire   [20:0] select_ln66_2_fu_828_p3;
wire   [20:0] select_ln66_5_fu_844_p3;
wire   [0:0] icmp_ln66_6_fu_850_p2;
wire   [0:0] xor_ln66_6_fu_856_p2;
wire   [0:0] icmp_ln66_7_fu_870_p2;
wire   [0:0] xor_ln66_7_fu_874_p2;
wire   [0:0] xor_ln66_8_fu_892_p2;
wire   [20:0] x_max_fu_897_p3;
wire  signed [21:0] sext_ln215_fu_903_p1;
wire  signed [21:0] sext_ln215_1_fu_906_p1;
wire   [21:0] sub_ln215_fu_910_p2;
wire   [0:0] tmp_10_fu_916_p3;
wire   [0:0] tmp_11_fu_924_p3;
wire   [0:0] xor_ln215_fu_932_p2;
wire  signed [21:0] sext_ln215_2_fu_950_p1;
wire   [21:0] sub_ln215_1_fu_953_p2;
wire   [0:0] tmp_12_fu_959_p3;
wire   [0:0] tmp_13_fu_967_p3;
wire   [0:0] xor_ln215_2_fu_975_p2;
wire  signed [21:0] sext_ln215_3_fu_993_p1;
wire   [21:0] sub_ln215_2_fu_996_p2;
wire   [0:0] tmp_14_fu_1002_p3;
wire   [0:0] tmp_15_fu_1010_p3;
wire   [0:0] xor_ln215_4_fu_1018_p2;
wire  signed [21:0] sext_ln215_4_fu_1036_p1;
wire   [21:0] sub_ln215_3_fu_1039_p2;
wire   [0:0] tmp_16_fu_1045_p3;
wire   [0:0] tmp_17_fu_1053_p3;
wire   [0:0] xor_ln215_6_fu_1061_p2;
wire  signed [21:0] sext_ln215_5_fu_1079_p1;
wire   [21:0] sub_ln215_4_fu_1082_p2;
wire   [0:0] tmp_18_fu_1088_p3;
wire   [0:0] tmp_19_fu_1096_p3;
wire   [0:0] xor_ln215_8_fu_1104_p2;
wire  signed [21:0] sext_ln215_6_fu_1122_p1;
wire   [21:0] sub_ln215_5_fu_1125_p2;
wire   [0:0] tmp_20_fu_1131_p3;
wire   [0:0] tmp_21_fu_1139_p3;
wire   [0:0] xor_ln215_10_fu_1147_p2;
wire  signed [21:0] sext_ln215_7_fu_1165_p1;
wire   [21:0] sub_ln215_6_fu_1168_p2;
wire   [0:0] tmp_22_fu_1174_p3;
wire   [0:0] tmp_23_fu_1182_p3;
wire   [0:0] xor_ln215_12_fu_1190_p2;
wire  signed [21:0] sext_ln215_8_fu_1208_p1;
wire   [21:0] sub_ln215_7_fu_1211_p2;
wire   [0:0] tmp_24_fu_1217_p3;
wire   [0:0] tmp_25_fu_1225_p3;
wire   [0:0] xor_ln215_14_fu_1233_p2;
wire  signed [21:0] sext_ln215_9_fu_1251_p1;
wire   [21:0] sub_ln215_8_fu_1254_p2;
wire   [0:0] tmp_26_fu_1260_p3;
wire   [0:0] tmp_27_fu_1268_p3;
wire   [0:0] xor_ln215_16_fu_1276_p2;
wire  signed [21:0] sext_ln215_10_fu_1294_p1;
wire   [21:0] sub_ln215_9_fu_1297_p2;
wire   [0:0] tmp_28_fu_1303_p3;
wire   [0:0] tmp_29_fu_1311_p3;
wire   [0:0] xor_ln215_18_fu_1319_p2;
wire   [0:0] and_ln215_fu_938_p2;
wire   [0:0] xor_ln215_1_fu_944_p2;
wire   [9:0] select_ln215_fu_1337_p3;
wire   [9:0] tmp_fu_1345_p4;
wire   [9:0] select_ln215_1_fu_1355_p3;
wire   [0:0] and_ln215_1_fu_981_p2;
wire   [0:0] xor_ln215_3_fu_987_p2;
wire   [9:0] select_ln215_2_fu_1368_p3;
wire   [9:0] tmp_1_fu_1376_p4;
wire   [9:0] select_ln215_3_fu_1386_p3;
wire   [0:0] and_ln215_2_fu_1024_p2;
wire   [0:0] xor_ln215_5_fu_1030_p2;
wire   [9:0] select_ln215_4_fu_1399_p3;
wire   [9:0] tmp_2_fu_1407_p4;
wire   [9:0] select_ln215_5_fu_1417_p3;
wire   [0:0] and_ln215_3_fu_1067_p2;
wire   [0:0] xor_ln215_7_fu_1073_p2;
wire   [9:0] select_ln215_6_fu_1430_p3;
wire   [9:0] tmp_3_fu_1438_p4;
wire   [9:0] select_ln215_7_fu_1448_p3;
wire   [0:0] and_ln215_4_fu_1110_p2;
wire   [0:0] xor_ln215_9_fu_1116_p2;
wire   [9:0] select_ln215_8_fu_1461_p3;
wire   [9:0] tmp_4_fu_1469_p4;
wire   [9:0] select_ln215_9_fu_1479_p3;
wire   [0:0] and_ln215_5_fu_1153_p2;
wire   [0:0] xor_ln215_11_fu_1159_p2;
wire   [9:0] select_ln215_10_fu_1492_p3;
wire   [9:0] tmp_5_fu_1500_p4;
wire   [9:0] select_ln215_11_fu_1510_p3;
wire   [0:0] and_ln215_6_fu_1196_p2;
wire   [0:0] xor_ln215_13_fu_1202_p2;
wire   [9:0] select_ln215_12_fu_1523_p3;
wire   [9:0] tmp_6_fu_1531_p4;
wire   [9:0] select_ln215_13_fu_1541_p3;
wire   [0:0] and_ln215_7_fu_1239_p2;
wire   [0:0] xor_ln215_15_fu_1245_p2;
wire   [9:0] select_ln215_14_fu_1554_p3;
wire   [9:0] tmp_7_fu_1562_p4;
wire   [9:0] select_ln215_15_fu_1572_p3;
wire   [0:0] and_ln215_8_fu_1282_p2;
wire   [0:0] xor_ln215_17_fu_1288_p2;
wire   [9:0] select_ln215_16_fu_1585_p3;
wire   [9:0] tmp_8_fu_1593_p4;
wire   [0:0] and_ln215_9_fu_1325_p2;
wire   [0:0] xor_ln215_19_fu_1331_p2;
wire   [9:0] select_ln215_18_fu_1611_p3;
wire   [9:0] tmp_s_fu_1619_p4;
wire   [17:0] zext_ln51_3_fu_1649_p1;
wire   [17:0] zext_ln51_2_fu_1645_p1;
wire   [17:0] add_ln51_3_fu_1653_p2;
wire   [0:0] tmp_30_fu_1659_p3;
wire   [17:0] zext_ln51_5_fu_1679_p1;
wire   [17:0] zext_ln51_4_fu_1675_p1;
wire   [17:0] add_ln51_4_fu_1683_p2;
wire   [0:0] tmp_31_fu_1689_p3;
wire  signed [17:0] select_ln51_3_fu_1667_p3;
wire  signed [17:0] select_ln51_4_fu_1697_p3;
wire  signed [18:0] sext_ln51_5_fu_1709_p1;
wire  signed [18:0] sext_ln51_4_fu_1705_p1;
wire   [18:0] add_ln51_5_fu_1719_p2;
wire   [17:0] zext_ln51_7_fu_1745_p1;
wire   [17:0] zext_ln51_6_fu_1741_p1;
wire   [17:0] add_ln51_6_fu_1749_p2;
wire   [0:0] tmp_34_fu_1755_p3;
wire   [17:0] zext_ln51_9_fu_1775_p1;
wire   [17:0] zext_ln51_8_fu_1771_p1;
wire   [17:0] add_ln51_7_fu_1779_p2;
wire   [0:0] tmp_35_fu_1785_p3;
wire  signed [17:0] select_ln51_8_fu_1763_p3;
wire  signed [17:0] select_ln51_9_fu_1793_p3;
wire  signed [18:0] sext_ln51_7_fu_1805_p1;
wire  signed [18:0] sext_ln51_6_fu_1801_p1;
wire   [18:0] add_ln51_8_fu_1815_p2;
wire   [0:0] xor_ln51_2_fu_1837_p2;
wire   [0:0] xor_ln51_7_fu_1847_p2;
wire   [0:0] xor_ln51_8_fu_1857_p2;
wire   [0:0] and_ln51_3_fu_1842_p2;
wire   [0:0] xor_ln51_9_fu_1861_p2;
wire   [0:0] and_ln51_4_fu_1852_p2;
wire   [0:0] or_ln51_1_fu_1867_p2;
wire   [17:0] select_ln51_5_fu_1873_p3;
wire   [17:0] select_ln51_6_fu_1880_p3;
wire   [0:0] xor_ln51_10_fu_1895_p2;
wire   [0:0] xor_ln51_11_fu_1905_p2;
wire   [0:0] xor_ln51_12_fu_1915_p2;
wire   [0:0] and_ln51_5_fu_1900_p2;
wire   [0:0] xor_ln51_13_fu_1919_p2;
wire   [0:0] and_ln51_6_fu_1910_p2;
wire   [0:0] or_ln51_2_fu_1925_p2;
wire   [17:0] select_ln51_10_fu_1931_p3;
wire   [17:0] select_ln51_11_fu_1938_p3;
wire  signed [17:0] select_ln51_7_fu_1887_p3;
wire  signed [17:0] select_ln51_12_fu_1945_p3;
wire  signed [18:0] sext_ln51_fu_1953_p1;
wire  signed [18:0] sext_ln51_1_fu_1957_p1;
wire   [18:0] add_ln51_fu_1967_p2;
wire   [17:0] add_ln51_12_fu_1961_p2;
wire   [0:0] tmp_38_fu_1973_p3;
wire   [0:0] tmp_39_fu_1981_p3;
wire   [0:0] xor_ln51_fu_1989_p2;
wire   [0:0] and_ln51_fu_1995_p2;
wire   [0:0] xor_ln51_1_fu_2001_p2;
wire   [17:0] select_ln51_fu_2007_p3;
wire   [17:0] zext_ln51_1_fu_2027_p1;
wire   [17:0] zext_ln51_fu_2023_p1;
wire   [17:0] add_ln51_1_fu_2031_p2;
wire   [0:0] tmp_40_fu_2037_p3;
wire  signed [17:0] select_ln51_1_fu_2015_p3;
wire  signed [17:0] select_ln51_2_fu_2045_p3;
wire  signed [18:0] sext_ln51_2_fu_2053_p1;
wire  signed [18:0] sext_ln51_3_fu_2057_p1;
wire   [18:0] add_ln51_2_fu_2067_p2;
wire   [17:0] add_ln51_9_fu_2061_p2;
wire   [0:0] xor_ln51_3_fu_2099_p2;
wire   [0:0] xor_ln51_4_fu_2109_p2;
wire   [0:0] xor_ln51_5_fu_2119_p2;
wire   [0:0] and_ln51_1_fu_2104_p2;
wire   [0:0] xor_ln51_6_fu_2123_p2;
wire   [0:0] and_ln51_2_fu_2114_p2;
wire   [0:0] or_ln51_fu_2129_p2;
wire   [9:0] select_ln51_13_fu_2135_p3;
wire   [9:0] select_ln51_14_fu_2142_p3;
wire   [9:0] select_ln51_15_fu_2149_p3;
wire   [23:0] mul_ln244_fu_273_p2;
wire   [23:0] mul_ln244_1_fu_280_p2;
wire   [23:0] mul_ln244_2_fu_274_p2;
wire   [23:0] mul_ln244_3_fu_277_p2;
wire   [23:0] mul_ln244_4_fu_275_p2;
wire   [23:0] mul_ln244_5_fu_279_p2;
wire   [23:0] mul_ln244_6_fu_276_p2;
wire   [23:0] mul_ln244_7_fu_278_p2;
wire   [23:0] mul_ln244_8_fu_281_p2;
wire   [23:0] mul_ln244_9_fu_282_p2;
wire   [7:0] trunc_ln244_9_fu_2305_p4;
wire   [7:0] trunc_ln244_8_fu_2291_p4;
wire   [7:0] trunc_ln244_7_fu_2277_p4;
wire   [7:0] trunc_ln244_6_fu_2263_p4;
wire   [7:0] trunc_ln244_5_fu_2249_p4;
wire   [7:0] trunc_ln244_4_fu_2235_p4;
wire   [7:0] trunc_ln244_3_fu_2221_p4;
wire   [7:0] trunc_ln244_2_fu_2207_p4;
wire   [7:0] trunc_ln244_1_fu_2193_p4;
wire   [7:0] trunc_ln1_fu_2179_p4;
wire    ap_CS_fsm_state9;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire   [23:0] mul_ln244_1_fu_280_p10;
wire   [23:0] mul_ln244_2_fu_274_p10;
wire   [23:0] mul_ln244_3_fu_277_p10;
wire   [23:0] mul_ln244_4_fu_275_p10;
wire   [23:0] mul_ln244_5_fu_279_p10;
wire   [23:0] mul_ln244_6_fu_276_p10;
wire   [23:0] mul_ln244_7_fu_278_p10;
wire   [23:0] mul_ln244_8_fu_281_p10;
wire   [23:0] mul_ln244_9_fu_282_p10;
wire   [23:0] mul_ln244_fu_273_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_exp_tablZio #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5),
    .q5(exp_table_q5),
    .address6(exp_table_address6),
    .ce6(exp_table_ce6),
    .q6(exp_table_q6),
    .address7(exp_table_address7),
    .ce7(exp_table_ce7),
    .q7(exp_table_q7)
);

myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_invert_t0iy #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1124(
    .din0(mul_ln244_fu_273_p0),
    .din1(mul_ln244_fu_273_p1),
    .dout(mul_ln244_fu_273_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1125(
    .din0(mul_ln244_2_fu_274_p0),
    .din1(mul_ln244_2_fu_274_p1),
    .dout(mul_ln244_2_fu_274_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1126(
    .din0(mul_ln244_4_fu_275_p0),
    .din1(mul_ln244_4_fu_275_p1),
    .dout(mul_ln244_4_fu_275_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1127(
    .din0(mul_ln244_6_fu_276_p0),
    .din1(mul_ln244_6_fu_276_p1),
    .dout(mul_ln244_6_fu_276_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1128(
    .din0(mul_ln244_3_fu_277_p0),
    .din1(mul_ln244_3_fu_277_p1),
    .dout(mul_ln244_3_fu_277_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1129(
    .din0(mul_ln244_7_fu_278_p0),
    .din1(mul_ln244_7_fu_278_p1),
    .dout(mul_ln244_7_fu_278_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1130(
    .din0(mul_ln244_5_fu_279_p0),
    .din1(mul_ln244_5_fu_279_p1),
    .dout(mul_ln244_5_fu_279_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1131(
    .din0(mul_ln244_1_fu_280_p0),
    .din1(mul_ln244_1_fu_280_p1),
    .dout(mul_ln244_1_fu_280_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1132(
    .din0(mul_ln244_8_fu_281_p0),
    .din1(mul_ln244_8_fu_281_p1),
    .dout(mul_ln244_8_fu_281_p2)
);

myproject_mul_18s_17ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_18s_17ns_24_1_1_U1133(
    .din0(mul_ln244_9_fu_282_p0),
    .din1(mul_ln244_9_fu_282_p1),
    .dout(mul_ln244_9_fu_282_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln51_10_reg_2533 <= add_ln51_10_fu_1713_p2;
        add_ln51_11_reg_2553 <= add_ln51_11_fu_1809_p2;
        exp_res_1_reg_2488 <= exp_table_q6;
        exp_res_2_reg_2493 <= exp_table_q5;
        exp_res_3_reg_2498 <= exp_table_q4;
        exp_res_4_reg_2503 <= exp_table_q3;
        exp_res_5_reg_2508 <= exp_table_q2;
        exp_res_6_reg_2513 <= exp_table_q1;
        exp_res_7_reg_2518 <= exp_table_q0;
        exp_res_reg_2483 <= exp_table_q7;
        tmp_32_reg_2539 <= add_ln51_5_fu_1719_p2[32'd18];
        tmp_33_reg_2546 <= add_ln51_10_fu_1713_p2[32'd17];
        tmp_36_reg_2559 <= add_ln51_8_fu_1815_p2[32'd18];
        tmp_37_reg_2566 <= add_ln51_11_fu_1809_p2[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_array_1_reg_2345 <= {{layer19_out_dout[41:21]}};
        data_array_2_reg_2350 <= {{layer19_out_dout[62:42]}};
        data_array_3_reg_2355 <= {{layer19_out_dout[83:63]}};
        data_array_4_reg_2360 <= {{layer19_out_dout[104:84]}};
        data_array_5_reg_2365 <= {{layer19_out_dout[125:105]}};
        data_array_6_reg_2370 <= {{layer19_out_dout[146:126]}};
        data_array_7_reg_2375 <= {{layer19_out_dout[167:147]}};
        data_array_8_reg_2380 <= {{layer19_out_dout[188:168]}};
        data_array_9_reg_2387 <= {{layer19_out_dout[209:189]}};
        data_array_reg_2340 <= data_array_fu_644_p1;
        select_ln66_1_reg_2400 <= select_ln66_1_fu_770_p3;
        select_ln66_3_reg_2406 <= select_ln66_3_fu_790_p3;
        select_ln66_4_reg_2412 <= select_ln66_4_fu_810_p3;
        select_ln66_reg_2394 <= select_ln66_fu_750_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        exp_res_8_reg_2573 <= exp_table_q1;
        exp_res_9_reg_2578 <= exp_table_q0;
        tmp_41_reg_2583 <= add_ln51_2_fu_2067_p2[32'd18];
        tmp_42_reg_2590 <= add_ln51_9_fu_2061_p2[32'd17];
        tmp_9_reg_2597 <= {{add_ln51_9_fu_2061_p2[17:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln66_8_reg_2428 <= icmp_ln66_8_fu_886_p2;
        select_ln66_6_reg_2418 <= select_ln66_6_fu_862_p3;
        select_ln66_7_reg_2423 <= select_ln66_7_fu_880_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        inv_exp_sum_reg_2608 <= invert_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        select_ln215_17_reg_2473 <= select_ln215_17_fu_1603_p3;
        select_ln215_19_reg_2478 <= select_ln215_19_fu_1629_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((layer21_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_table_address0 = zext_ln225_9_fu_1641_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_address0 = zext_ln225_7_fu_1580_p1;
    end else begin
        exp_table_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_table_address1 = zext_ln225_8_fu_1637_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_address1 = zext_ln225_6_fu_1549_p1;
    end else begin
        exp_table_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce2 = 1'b1;
    end else begin
        exp_table_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce3 = 1'b1;
    end else begin
        exp_table_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce4 = 1'b1;
    end else begin
        exp_table_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce5 = 1'b1;
    end else begin
        exp_table_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce6 = 1'b1;
    end else begin
        exp_table_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce7 = 1'b1;
    end else begin
        exp_table_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        layer19_out_blk_n = layer19_out_empty_n;
    end else begin
        layer19_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer19_out_read = 1'b1;
    end else begin
        layer19_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        layer21_out_TDATA_blk_n = layer21_out_TREADY;
    end else begin
        layer21_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer21_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        layer21_out_TVALID = 1'b1;
    end else begin
        layer21_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((layer21_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_10_fu_1713_p2 = ($signed(select_ln51_4_fu_1697_p3) + $signed(select_ln51_3_fu_1667_p3));

assign add_ln51_11_fu_1809_p2 = ($signed(select_ln51_9_fu_1793_p3) + $signed(select_ln51_8_fu_1763_p3));

assign add_ln51_12_fu_1961_p2 = ($signed(select_ln51_7_fu_1887_p3) + $signed(select_ln51_12_fu_1945_p3));

assign add_ln51_1_fu_2031_p2 = (zext_ln51_1_fu_2027_p1 + zext_ln51_fu_2023_p1);

assign add_ln51_2_fu_2067_p2 = ($signed(sext_ln51_2_fu_2053_p1) + $signed(sext_ln51_3_fu_2057_p1));

assign add_ln51_3_fu_1653_p2 = (zext_ln51_3_fu_1649_p1 + zext_ln51_2_fu_1645_p1);

assign add_ln51_4_fu_1683_p2 = (zext_ln51_5_fu_1679_p1 + zext_ln51_4_fu_1675_p1);

assign add_ln51_5_fu_1719_p2 = ($signed(sext_ln51_5_fu_1709_p1) + $signed(sext_ln51_4_fu_1705_p1));

assign add_ln51_6_fu_1749_p2 = (zext_ln51_7_fu_1745_p1 + zext_ln51_6_fu_1741_p1);

assign add_ln51_7_fu_1779_p2 = (zext_ln51_9_fu_1775_p1 + zext_ln51_8_fu_1771_p1);

assign add_ln51_8_fu_1815_p2 = ($signed(sext_ln51_7_fu_1805_p1) + $signed(sext_ln51_6_fu_1801_p1));

assign add_ln51_9_fu_2061_p2 = ($signed(select_ln51_1_fu_2015_p3) + $signed(select_ln51_2_fu_2045_p3));

assign add_ln51_fu_1967_p2 = ($signed(sext_ln51_fu_1953_p1) + $signed(sext_ln51_1_fu_1957_p1));

assign and_ln215_1_fu_981_p2 = (xor_ln215_2_fu_975_p2 & tmp_13_fu_967_p3);

assign and_ln215_2_fu_1024_p2 = (xor_ln215_4_fu_1018_p2 & tmp_15_fu_1010_p3);

assign and_ln215_3_fu_1067_p2 = (xor_ln215_6_fu_1061_p2 & tmp_17_fu_1053_p3);

assign and_ln215_4_fu_1110_p2 = (xor_ln215_8_fu_1104_p2 & tmp_19_fu_1096_p3);

assign and_ln215_5_fu_1153_p2 = (xor_ln215_10_fu_1147_p2 & tmp_21_fu_1139_p3);

assign and_ln215_6_fu_1196_p2 = (xor_ln215_12_fu_1190_p2 & tmp_23_fu_1182_p3);

assign and_ln215_7_fu_1239_p2 = (xor_ln215_14_fu_1233_p2 & tmp_25_fu_1225_p3);

assign and_ln215_8_fu_1282_p2 = (xor_ln215_16_fu_1276_p2 & tmp_27_fu_1268_p3);

assign and_ln215_9_fu_1325_p2 = (xor_ln215_18_fu_1319_p2 & tmp_29_fu_1311_p3);

assign and_ln215_fu_938_p2 = (xor_ln215_fu_932_p2 & tmp_11_fu_924_p3);

assign and_ln51_1_fu_2104_p2 = (xor_ln51_3_fu_2099_p2 & tmp_42_reg_2590);

assign and_ln51_2_fu_2114_p2 = (xor_ln51_4_fu_2109_p2 & tmp_41_reg_2583);

assign and_ln51_3_fu_1842_p2 = (xor_ln51_2_fu_1837_p2 & tmp_33_reg_2546);

assign and_ln51_4_fu_1852_p2 = (xor_ln51_7_fu_1847_p2 & tmp_32_reg_2539);

assign and_ln51_5_fu_1900_p2 = (xor_ln51_10_fu_1895_p2 & tmp_37_reg_2566);

assign and_ln51_6_fu_1910_p2 = (xor_ln51_11_fu_1905_p2 & tmp_36_reg_2559);

assign and_ln51_fu_1995_p2 = (xor_ln51_fu_1989_p2 & tmp_39_fu_1981_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((layer19_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign data_array_1_fu_648_p4 = {{layer19_out_dout[41:21]}};

assign data_array_2_fu_658_p4 = {{layer19_out_dout[62:42]}};

assign data_array_3_fu_668_p4 = {{layer19_out_dout[83:63]}};

assign data_array_4_fu_678_p4 = {{layer19_out_dout[104:84]}};

assign data_array_5_fu_688_p4 = {{layer19_out_dout[125:105]}};

assign data_array_6_fu_698_p4 = {{layer19_out_dout[146:126]}};

assign data_array_7_fu_708_p4 = {{layer19_out_dout[167:147]}};

assign data_array_fu_644_p1 = layer19_out_dout[20:0];

assign exp_table_address2 = zext_ln225_5_fu_1518_p1;

assign exp_table_address3 = zext_ln225_4_fu_1487_p1;

assign exp_table_address4 = zext_ln225_3_fu_1456_p1;

assign exp_table_address5 = zext_ln225_2_fu_1425_p1;

assign exp_table_address6 = zext_ln225_1_fu_1394_p1;

assign exp_table_address7 = zext_ln225_fu_1363_p1;

assign icmp_ln66_1_fu_758_p2 = (($signed(data_array_2_fu_658_p4) < $signed(data_array_3_fu_668_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_818_p2 = (($signed(select_ln66_reg_2394) < $signed(select_ln66_1_reg_2400)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_778_p2 = (($signed(data_array_4_fu_678_p4) < $signed(data_array_5_fu_688_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_798_p2 = (($signed(data_array_6_fu_698_p4) < $signed(data_array_7_fu_708_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_834_p2 = (($signed(select_ln66_3_reg_2406) < $signed(select_ln66_4_reg_2412)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_850_p2 = (($signed(select_ln66_2_fu_828_p3) < $signed(select_ln66_5_fu_844_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_870_p2 = (($signed(data_array_8_reg_2380) < $signed(data_array_9_reg_2387)) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_886_p2 = (($signed(select_ln66_6_fu_862_p3) < $signed(select_ln66_7_fu_880_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_738_p2 = (($signed(data_array_fu_644_p1) < $signed(data_array_1_fu_648_p4)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln235_fu_2157_p1;

assign layer21_out_TDATA = {{{{{{{{{{trunc_ln244_9_fu_2305_p4}, {trunc_ln244_8_fu_2291_p4}}, {trunc_ln244_7_fu_2277_p4}}, {trunc_ln244_6_fu_2263_p4}}, {trunc_ln244_5_fu_2249_p4}}, {trunc_ln244_4_fu_2235_p4}}, {trunc_ln244_3_fu_2221_p4}}, {trunc_ln244_2_fu_2207_p4}}, {trunc_ln244_1_fu_2193_p4}}, {trunc_ln1_fu_2179_p4}};

assign mul_ln244_1_fu_280_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_1_fu_280_p1 = mul_ln244_1_fu_280_p10;

assign mul_ln244_1_fu_280_p10 = exp_res_1_reg_2488;

assign mul_ln244_2_fu_274_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_2_fu_274_p1 = mul_ln244_2_fu_274_p10;

assign mul_ln244_2_fu_274_p10 = exp_res_2_reg_2493;

assign mul_ln244_3_fu_277_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_3_fu_277_p1 = mul_ln244_3_fu_277_p10;

assign mul_ln244_3_fu_277_p10 = exp_res_3_reg_2498;

assign mul_ln244_4_fu_275_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_4_fu_275_p1 = mul_ln244_4_fu_275_p10;

assign mul_ln244_4_fu_275_p10 = exp_res_4_reg_2503;

assign mul_ln244_5_fu_279_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_5_fu_279_p1 = mul_ln244_5_fu_279_p10;

assign mul_ln244_5_fu_279_p10 = exp_res_5_reg_2508;

assign mul_ln244_6_fu_276_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_6_fu_276_p1 = mul_ln244_6_fu_276_p10;

assign mul_ln244_6_fu_276_p10 = exp_res_6_reg_2513;

assign mul_ln244_7_fu_278_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_7_fu_278_p1 = mul_ln244_7_fu_278_p10;

assign mul_ln244_7_fu_278_p10 = exp_res_7_reg_2518;

assign mul_ln244_8_fu_281_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_8_fu_281_p1 = mul_ln244_8_fu_281_p10;

assign mul_ln244_8_fu_281_p10 = exp_res_8_reg_2573;

assign mul_ln244_9_fu_282_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_9_fu_282_p1 = mul_ln244_9_fu_282_p10;

assign mul_ln244_9_fu_282_p10 = exp_res_9_reg_2578;

assign mul_ln244_fu_273_p0 = sext_ln244_fu_2162_p1;

assign mul_ln244_fu_273_p1 = mul_ln244_fu_273_p10;

assign mul_ln244_fu_273_p10 = exp_res_reg_2483;

assign or_ln51_1_fu_1867_p2 = (xor_ln51_9_fu_1861_p2 | and_ln51_3_fu_1842_p2);

assign or_ln51_2_fu_1925_p2 = (xor_ln51_13_fu_1919_p2 | and_ln51_5_fu_1900_p2);

assign or_ln51_fu_2129_p2 = (xor_ln51_6_fu_2123_p2 | and_ln51_1_fu_2104_p2);

assign select_ln215_10_fu_1492_p3 = ((and_ln215_5_fu_1153_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_11_fu_1510_p3 = ((xor_ln215_11_fu_1159_p2[0:0] == 1'b1) ? select_ln215_10_fu_1492_p3 : tmp_5_fu_1500_p4);

assign select_ln215_12_fu_1523_p3 = ((and_ln215_6_fu_1196_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_13_fu_1541_p3 = ((xor_ln215_13_fu_1202_p2[0:0] == 1'b1) ? select_ln215_12_fu_1523_p3 : tmp_6_fu_1531_p4);

assign select_ln215_14_fu_1554_p3 = ((and_ln215_7_fu_1239_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_15_fu_1572_p3 = ((xor_ln215_15_fu_1245_p2[0:0] == 1'b1) ? select_ln215_14_fu_1554_p3 : tmp_7_fu_1562_p4);

assign select_ln215_16_fu_1585_p3 = ((and_ln215_8_fu_1282_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_17_fu_1603_p3 = ((xor_ln215_17_fu_1288_p2[0:0] == 1'b1) ? select_ln215_16_fu_1585_p3 : tmp_8_fu_1593_p4);

assign select_ln215_18_fu_1611_p3 = ((and_ln215_9_fu_1325_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_19_fu_1629_p3 = ((xor_ln215_19_fu_1331_p2[0:0] == 1'b1) ? select_ln215_18_fu_1611_p3 : tmp_s_fu_1619_p4);

assign select_ln215_1_fu_1355_p3 = ((xor_ln215_1_fu_944_p2[0:0] == 1'b1) ? select_ln215_fu_1337_p3 : tmp_fu_1345_p4);

assign select_ln215_2_fu_1368_p3 = ((and_ln215_1_fu_981_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_3_fu_1386_p3 = ((xor_ln215_3_fu_987_p2[0:0] == 1'b1) ? select_ln215_2_fu_1368_p3 : tmp_1_fu_1376_p4);

assign select_ln215_4_fu_1399_p3 = ((and_ln215_2_fu_1024_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_5_fu_1417_p3 = ((xor_ln215_5_fu_1030_p2[0:0] == 1'b1) ? select_ln215_4_fu_1399_p3 : tmp_2_fu_1407_p4);

assign select_ln215_6_fu_1430_p3 = ((and_ln215_3_fu_1067_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_7_fu_1448_p3 = ((xor_ln215_7_fu_1073_p2[0:0] == 1'b1) ? select_ln215_6_fu_1430_p3 : tmp_3_fu_1438_p4);

assign select_ln215_8_fu_1461_p3 = ((and_ln215_4_fu_1110_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_9_fu_1479_p3 = ((xor_ln215_9_fu_1116_p2[0:0] == 1'b1) ? select_ln215_8_fu_1461_p3 : tmp_4_fu_1469_p4);

assign select_ln215_fu_1337_p3 = ((and_ln215_fu_938_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln51_10_fu_1931_p3 = ((xor_ln51_12_fu_1915_p2[0:0] == 1'b1) ? 18'd131071 : add_ln51_11_reg_2553);

assign select_ln51_11_fu_1938_p3 = ((and_ln51_6_fu_1910_p2[0:0] == 1'b1) ? 18'd131072 : add_ln51_11_reg_2553);

assign select_ln51_12_fu_1945_p3 = ((or_ln51_2_fu_1925_p2[0:0] == 1'b1) ? select_ln51_10_fu_1931_p3 : select_ln51_11_fu_1938_p3);

assign select_ln51_13_fu_2135_p3 = ((xor_ln51_5_fu_2119_p2[0:0] == 1'b1) ? 10'd511 : tmp_9_reg_2597);

assign select_ln51_14_fu_2142_p3 = ((and_ln51_2_fu_2114_p2[0:0] == 1'b1) ? 10'd512 : tmp_9_reg_2597);

assign select_ln51_15_fu_2149_p3 = ((or_ln51_fu_2129_p2[0:0] == 1'b1) ? select_ln51_13_fu_2135_p3 : select_ln51_14_fu_2142_p3);

assign select_ln51_1_fu_2015_p3 = ((xor_ln51_1_fu_2001_p2[0:0] == 1'b1) ? select_ln51_fu_2007_p3 : add_ln51_12_fu_1961_p2);

assign select_ln51_2_fu_2045_p3 = ((tmp_40_fu_2037_p3[0:0] == 1'b1) ? 18'd131071 : add_ln51_1_fu_2031_p2);

assign select_ln51_3_fu_1667_p3 = ((tmp_30_fu_1659_p3[0:0] == 1'b1) ? 18'd131071 : add_ln51_3_fu_1653_p2);

assign select_ln51_4_fu_1697_p3 = ((tmp_31_fu_1689_p3[0:0] == 1'b1) ? 18'd131071 : add_ln51_4_fu_1683_p2);

assign select_ln51_5_fu_1873_p3 = ((xor_ln51_8_fu_1857_p2[0:0] == 1'b1) ? 18'd131071 : add_ln51_10_reg_2533);

assign select_ln51_6_fu_1880_p3 = ((and_ln51_4_fu_1852_p2[0:0] == 1'b1) ? 18'd131072 : add_ln51_10_reg_2533);

assign select_ln51_7_fu_1887_p3 = ((or_ln51_1_fu_1867_p2[0:0] == 1'b1) ? select_ln51_5_fu_1873_p3 : select_ln51_6_fu_1880_p3);

assign select_ln51_8_fu_1763_p3 = ((tmp_34_fu_1755_p3[0:0] == 1'b1) ? 18'd131071 : add_ln51_6_fu_1749_p2);

assign select_ln51_9_fu_1793_p3 = ((tmp_35_fu_1785_p3[0:0] == 1'b1) ? 18'd131071 : add_ln51_7_fu_1779_p2);

assign select_ln51_fu_2007_p3 = ((and_ln51_fu_1995_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln66_1_fu_770_p3 = ((xor_ln66_1_fu_764_p2[0:0] == 1'b1) ? data_array_2_fu_658_p4 : data_array_3_fu_668_p4);

assign select_ln66_2_fu_828_p3 = ((xor_ln66_2_fu_822_p2[0:0] == 1'b1) ? select_ln66_reg_2394 : select_ln66_1_reg_2400);

assign select_ln66_3_fu_790_p3 = ((xor_ln66_3_fu_784_p2[0:0] == 1'b1) ? data_array_4_fu_678_p4 : data_array_5_fu_688_p4);

assign select_ln66_4_fu_810_p3 = ((xor_ln66_4_fu_804_p2[0:0] == 1'b1) ? data_array_6_fu_698_p4 : data_array_7_fu_708_p4);

assign select_ln66_5_fu_844_p3 = ((xor_ln66_5_fu_838_p2[0:0] == 1'b1) ? select_ln66_3_reg_2406 : select_ln66_4_reg_2412);

assign select_ln66_6_fu_862_p3 = ((xor_ln66_6_fu_856_p2[0:0] == 1'b1) ? select_ln66_2_fu_828_p3 : select_ln66_5_fu_844_p3);

assign select_ln66_7_fu_880_p3 = ((xor_ln66_7_fu_874_p2[0:0] == 1'b1) ? data_array_8_reg_2380 : data_array_9_reg_2387);

assign select_ln66_fu_750_p3 = ((xor_ln66_fu_744_p2[0:0] == 1'b1) ? data_array_fu_644_p1 : data_array_1_fu_648_p4);

assign sext_ln215_10_fu_1294_p1 = data_array_9_reg_2387;

assign sext_ln215_1_fu_906_p1 = $signed(x_max_fu_897_p3);

assign sext_ln215_2_fu_950_p1 = data_array_1_reg_2345;

assign sext_ln215_3_fu_993_p1 = data_array_2_reg_2350;

assign sext_ln215_4_fu_1036_p1 = data_array_3_reg_2355;

assign sext_ln215_5_fu_1079_p1 = data_array_4_reg_2360;

assign sext_ln215_6_fu_1122_p1 = data_array_5_reg_2365;

assign sext_ln215_7_fu_1165_p1 = data_array_6_reg_2370;

assign sext_ln215_8_fu_1208_p1 = data_array_7_reg_2375;

assign sext_ln215_9_fu_1251_p1 = data_array_8_reg_2380;

assign sext_ln215_fu_903_p1 = data_array_reg_2340;

assign sext_ln244_fu_2162_p1 = $signed(inv_exp_sum_reg_2608);

assign sext_ln51_1_fu_1957_p1 = select_ln51_12_fu_1945_p3;

assign sext_ln51_2_fu_2053_p1 = select_ln51_1_fu_2015_p3;

assign sext_ln51_3_fu_2057_p1 = select_ln51_2_fu_2045_p3;

assign sext_ln51_4_fu_1705_p1 = select_ln51_3_fu_1667_p3;

assign sext_ln51_5_fu_1709_p1 = select_ln51_4_fu_1697_p3;

assign sext_ln51_6_fu_1801_p1 = select_ln51_8_fu_1763_p3;

assign sext_ln51_7_fu_1805_p1 = select_ln51_9_fu_1793_p3;

assign sext_ln51_fu_1953_p1 = select_ln51_7_fu_1887_p3;

assign sub_ln215_1_fu_953_p2 = ($signed(sext_ln215_2_fu_950_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_2_fu_996_p2 = ($signed(sext_ln215_3_fu_993_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_3_fu_1039_p2 = ($signed(sext_ln215_4_fu_1036_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_4_fu_1082_p2 = ($signed(sext_ln215_5_fu_1079_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_5_fu_1125_p2 = ($signed(sext_ln215_6_fu_1122_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_6_fu_1168_p2 = ($signed(sext_ln215_7_fu_1165_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_7_fu_1211_p2 = ($signed(sext_ln215_8_fu_1208_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_8_fu_1254_p2 = ($signed(sext_ln215_9_fu_1251_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_9_fu_1297_p2 = ($signed(sext_ln215_10_fu_1294_p1) - $signed(sext_ln215_1_fu_906_p1));

assign sub_ln215_fu_910_p2 = ($signed(sext_ln215_fu_903_p1) - $signed(sext_ln215_1_fu_906_p1));

assign tmp_10_fu_916_p3 = sub_ln215_fu_910_p2[32'd21];

assign tmp_11_fu_924_p3 = sub_ln215_fu_910_p2[32'd20];

assign tmp_12_fu_959_p3 = sub_ln215_1_fu_953_p2[32'd21];

assign tmp_13_fu_967_p3 = sub_ln215_1_fu_953_p2[32'd20];

assign tmp_14_fu_1002_p3 = sub_ln215_2_fu_996_p2[32'd21];

assign tmp_15_fu_1010_p3 = sub_ln215_2_fu_996_p2[32'd20];

assign tmp_16_fu_1045_p3 = sub_ln215_3_fu_1039_p2[32'd21];

assign tmp_17_fu_1053_p3 = sub_ln215_3_fu_1039_p2[32'd20];

assign tmp_18_fu_1088_p3 = sub_ln215_4_fu_1082_p2[32'd21];

assign tmp_19_fu_1096_p3 = sub_ln215_4_fu_1082_p2[32'd20];

assign tmp_1_fu_1376_p4 = {{sub_ln215_1_fu_953_p2[20:11]}};

assign tmp_20_fu_1131_p3 = sub_ln215_5_fu_1125_p2[32'd21];

assign tmp_21_fu_1139_p3 = sub_ln215_5_fu_1125_p2[32'd20];

assign tmp_22_fu_1174_p3 = sub_ln215_6_fu_1168_p2[32'd21];

assign tmp_23_fu_1182_p3 = sub_ln215_6_fu_1168_p2[32'd20];

assign tmp_24_fu_1217_p3 = sub_ln215_7_fu_1211_p2[32'd21];

assign tmp_25_fu_1225_p3 = sub_ln215_7_fu_1211_p2[32'd20];

assign tmp_26_fu_1260_p3 = sub_ln215_8_fu_1254_p2[32'd21];

assign tmp_27_fu_1268_p3 = sub_ln215_8_fu_1254_p2[32'd20];

assign tmp_28_fu_1303_p3 = sub_ln215_9_fu_1297_p2[32'd21];

assign tmp_29_fu_1311_p3 = sub_ln215_9_fu_1297_p2[32'd20];

assign tmp_2_fu_1407_p4 = {{sub_ln215_2_fu_996_p2[20:11]}};

assign tmp_30_fu_1659_p3 = add_ln51_3_fu_1653_p2[32'd17];

assign tmp_31_fu_1689_p3 = add_ln51_4_fu_1683_p2[32'd17];

assign tmp_34_fu_1755_p3 = add_ln51_6_fu_1749_p2[32'd17];

assign tmp_35_fu_1785_p3 = add_ln51_7_fu_1779_p2[32'd17];

assign tmp_38_fu_1973_p3 = add_ln51_fu_1967_p2[32'd18];

assign tmp_39_fu_1981_p3 = add_ln51_12_fu_1961_p2[32'd17];

assign tmp_3_fu_1438_p4 = {{sub_ln215_3_fu_1039_p2[20:11]}};

assign tmp_40_fu_2037_p3 = add_ln51_1_fu_2031_p2[32'd17];

assign tmp_4_fu_1469_p4 = {{sub_ln215_4_fu_1082_p2[20:11]}};

assign tmp_5_fu_1500_p4 = {{sub_ln215_5_fu_1125_p2[20:11]}};

assign tmp_6_fu_1531_p4 = {{sub_ln215_6_fu_1168_p2[20:11]}};

assign tmp_7_fu_1562_p4 = {{sub_ln215_7_fu_1211_p2[20:11]}};

assign tmp_8_fu_1593_p4 = {{sub_ln215_8_fu_1254_p2[20:11]}};

assign tmp_fu_1345_p4 = {{sub_ln215_fu_910_p2[20:11]}};

assign tmp_s_fu_1619_p4 = {{sub_ln215_9_fu_1297_p2[20:11]}};

assign trunc_ln1_fu_2179_p4 = {{mul_ln244_fu_273_p2[23:16]}};

assign trunc_ln244_1_fu_2193_p4 = {{mul_ln244_1_fu_280_p2[23:16]}};

assign trunc_ln244_2_fu_2207_p4 = {{mul_ln244_2_fu_274_p2[23:16]}};

assign trunc_ln244_3_fu_2221_p4 = {{mul_ln244_3_fu_277_p2[23:16]}};

assign trunc_ln244_4_fu_2235_p4 = {{mul_ln244_4_fu_275_p2[23:16]}};

assign trunc_ln244_5_fu_2249_p4 = {{mul_ln244_5_fu_279_p2[23:16]}};

assign trunc_ln244_6_fu_2263_p4 = {{mul_ln244_6_fu_276_p2[23:16]}};

assign trunc_ln244_7_fu_2277_p4 = {{mul_ln244_7_fu_278_p2[23:16]}};

assign trunc_ln244_8_fu_2291_p4 = {{mul_ln244_8_fu_281_p2[23:16]}};

assign trunc_ln244_9_fu_2305_p4 = {{mul_ln244_9_fu_282_p2[23:16]}};

assign x_max_fu_897_p3 = ((xor_ln66_8_fu_892_p2[0:0] == 1'b1) ? select_ln66_6_reg_2418 : select_ln66_7_reg_2423);

assign xor_ln215_10_fu_1147_p2 = (tmp_20_fu_1131_p3 ^ 1'd1);

assign xor_ln215_11_fu_1159_p2 = (tmp_21_fu_1139_p3 ^ tmp_20_fu_1131_p3);

assign xor_ln215_12_fu_1190_p2 = (tmp_22_fu_1174_p3 ^ 1'd1);

assign xor_ln215_13_fu_1202_p2 = (tmp_23_fu_1182_p3 ^ tmp_22_fu_1174_p3);

assign xor_ln215_14_fu_1233_p2 = (tmp_24_fu_1217_p3 ^ 1'd1);

assign xor_ln215_15_fu_1245_p2 = (tmp_25_fu_1225_p3 ^ tmp_24_fu_1217_p3);

assign xor_ln215_16_fu_1276_p2 = (tmp_26_fu_1260_p3 ^ 1'd1);

assign xor_ln215_17_fu_1288_p2 = (tmp_27_fu_1268_p3 ^ tmp_26_fu_1260_p3);

assign xor_ln215_18_fu_1319_p2 = (tmp_28_fu_1303_p3 ^ 1'd1);

assign xor_ln215_19_fu_1331_p2 = (tmp_29_fu_1311_p3 ^ tmp_28_fu_1303_p3);

assign xor_ln215_1_fu_944_p2 = (tmp_11_fu_924_p3 ^ tmp_10_fu_916_p3);

assign xor_ln215_2_fu_975_p2 = (tmp_12_fu_959_p3 ^ 1'd1);

assign xor_ln215_3_fu_987_p2 = (tmp_13_fu_967_p3 ^ tmp_12_fu_959_p3);

assign xor_ln215_4_fu_1018_p2 = (tmp_14_fu_1002_p3 ^ 1'd1);

assign xor_ln215_5_fu_1030_p2 = (tmp_15_fu_1010_p3 ^ tmp_14_fu_1002_p3);

assign xor_ln215_6_fu_1061_p2 = (tmp_16_fu_1045_p3 ^ 1'd1);

assign xor_ln215_7_fu_1073_p2 = (tmp_17_fu_1053_p3 ^ tmp_16_fu_1045_p3);

assign xor_ln215_8_fu_1104_p2 = (tmp_18_fu_1088_p3 ^ 1'd1);

assign xor_ln215_9_fu_1116_p2 = (tmp_19_fu_1096_p3 ^ tmp_18_fu_1088_p3);

assign xor_ln215_fu_932_p2 = (tmp_10_fu_916_p3 ^ 1'd1);

assign xor_ln51_10_fu_1895_p2 = (tmp_36_reg_2559 ^ 1'd1);

assign xor_ln51_11_fu_1905_p2 = (tmp_37_reg_2566 ^ 1'd1);

assign xor_ln51_12_fu_1915_p2 = (tmp_37_reg_2566 ^ tmp_36_reg_2559);

assign xor_ln51_13_fu_1919_p2 = (xor_ln51_12_fu_1915_p2 ^ 1'd1);

assign xor_ln51_1_fu_2001_p2 = (tmp_39_fu_1981_p3 ^ tmp_38_fu_1973_p3);

assign xor_ln51_2_fu_1837_p2 = (tmp_32_reg_2539 ^ 1'd1);

assign xor_ln51_3_fu_2099_p2 = (tmp_41_reg_2583 ^ 1'd1);

assign xor_ln51_4_fu_2109_p2 = (tmp_42_reg_2590 ^ 1'd1);

assign xor_ln51_5_fu_2119_p2 = (tmp_42_reg_2590 ^ tmp_41_reg_2583);

assign xor_ln51_6_fu_2123_p2 = (xor_ln51_5_fu_2119_p2 ^ 1'd1);

assign xor_ln51_7_fu_1847_p2 = (tmp_33_reg_2546 ^ 1'd1);

assign xor_ln51_8_fu_1857_p2 = (tmp_33_reg_2546 ^ tmp_32_reg_2539);

assign xor_ln51_9_fu_1861_p2 = (xor_ln51_8_fu_1857_p2 ^ 1'd1);

assign xor_ln51_fu_1989_p2 = (tmp_38_fu_1973_p3 ^ 1'd1);

assign xor_ln66_1_fu_764_p2 = (icmp_ln66_1_fu_758_p2 ^ 1'd1);

assign xor_ln66_2_fu_822_p2 = (icmp_ln66_2_fu_818_p2 ^ 1'd1);

assign xor_ln66_3_fu_784_p2 = (icmp_ln66_3_fu_778_p2 ^ 1'd1);

assign xor_ln66_4_fu_804_p2 = (icmp_ln66_4_fu_798_p2 ^ 1'd1);

assign xor_ln66_5_fu_838_p2 = (icmp_ln66_5_fu_834_p2 ^ 1'd1);

assign xor_ln66_6_fu_856_p2 = (icmp_ln66_6_fu_850_p2 ^ 1'd1);

assign xor_ln66_7_fu_874_p2 = (icmp_ln66_7_fu_870_p2 ^ 1'd1);

assign xor_ln66_8_fu_892_p2 = (icmp_ln66_8_reg_2428 ^ 1'd1);

assign xor_ln66_fu_744_p2 = (icmp_ln66_fu_738_p2 ^ 1'd1);

assign zext_ln225_1_fu_1394_p1 = select_ln215_3_fu_1386_p3;

assign zext_ln225_2_fu_1425_p1 = select_ln215_5_fu_1417_p3;

assign zext_ln225_3_fu_1456_p1 = select_ln215_7_fu_1448_p3;

assign zext_ln225_4_fu_1487_p1 = select_ln215_9_fu_1479_p3;

assign zext_ln225_5_fu_1518_p1 = select_ln215_11_fu_1510_p3;

assign zext_ln225_6_fu_1549_p1 = select_ln215_13_fu_1541_p3;

assign zext_ln225_7_fu_1580_p1 = select_ln215_15_fu_1572_p3;

assign zext_ln225_8_fu_1637_p1 = select_ln215_17_reg_2473;

assign zext_ln225_9_fu_1641_p1 = select_ln215_19_reg_2478;

assign zext_ln225_fu_1363_p1 = select_ln215_1_fu_1355_p3;

assign zext_ln235_fu_2157_p1 = select_ln51_15_fu_2149_p3;

assign zext_ln51_1_fu_2027_p1 = exp_table_q0;

assign zext_ln51_2_fu_1645_p1 = exp_table_q7;

assign zext_ln51_3_fu_1649_p1 = exp_table_q6;

assign zext_ln51_4_fu_1675_p1 = exp_table_q5;

assign zext_ln51_5_fu_1679_p1 = exp_table_q4;

assign zext_ln51_6_fu_1741_p1 = exp_table_q3;

assign zext_ln51_7_fu_1745_p1 = exp_table_q2;

assign zext_ln51_8_fu_1771_p1 = exp_table_q1;

assign zext_ln51_9_fu_1775_p1 = exp_table_q0;

assign zext_ln51_fu_2023_p1 = exp_table_q1;

endmodule //myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s
