-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer15_out_dout : IN STD_LOGIC_VECTOR (335 downto 0);
    layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer15_out_empty_n : IN STD_LOGIC;
    layer15_out_read : OUT STD_LOGIC;
    layer17_out_din : OUT STD_LOGIC_VECTOR (479 downto 0);
    layer17_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_full_n : IN STD_LOGIC;
    layer17_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010101";
    constant ap_const_lv26_13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010011";
    constant ap_const_lv26_17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010111";
    constant ap_const_lv26_16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010110";
    constant ap_const_lv27_13 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000010011";
    constant ap_const_lv27_17 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000010111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010010";
    constant ap_const_lv32_93 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010011";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111100";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_111 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010001";
    constant ap_const_lv32_125 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100101";
    constant ap_const_lv32_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100110";
    constant ap_const_lv32_13A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111010";
    constant ap_const_lv32_13B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111011";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101001";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv23_7FC800 : STD_LOGIC_VECTOR (22 downto 0) := "11111111100100000000000";
    constant ap_const_lv23_7FC000 : STD_LOGIC_VECTOR (22 downto 0) := "11111111100000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv24_2000 : STD_LOGIC_VECTOR (23 downto 0) := "000000000010000000000000";
    constant ap_const_lv22_2000 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_const_lv22_3FD000 : STD_LOGIC_VECTOR (21 downto 0) := "1111111101000000000000";
    constant ap_const_lv23_800 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000100000000000";
    constant ap_const_lv22_3FE800 : STD_LOGIC_VECTOR (21 downto 0) := "1111111110100000000000";
    constant ap_const_lv22_3FF800 : STD_LOGIC_VECTOR (21 downto 0) := "1111111111100000000000";
    constant ap_const_lv26_3FFC800 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111100100000000000";
    constant ap_const_lv26_3FFB800 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111011100000000000";
    constant ap_const_lv26_3FFD800 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111101100000000000";
    constant ap_const_lv26_3000 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000011000000000000";
    constant ap_const_lv26_3FFF000 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer15_out_blk_n : STD_LOGIC;
    signal layer17_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mul_ln42_fu_158_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_reg_711 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln42_1_fu_157_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_reg_715 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_154_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_reg_719 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_fu_166_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln73_reg_723 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_3_fu_164_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_reg_727 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_4_fu_160_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_4_reg_731 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_1_fu_163_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln73_1_reg_735 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_5_fu_165_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_5_reg_739 : STD_LOGIC_VECTOR (25 downto 0);
    signal a_reg_1331 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal a_6_reg_1336 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_7_reg_1341 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_8_reg_1346 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_9_reg_1351 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_1_reg_1357 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_2_reg_1363 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_3_reg_1368 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_4_reg_1373 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_5_reg_1378 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_11_reg_1384 : STD_LOGIC_VECTOR (20 downto 0);
    signal a_10_reg_1389 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln73_fu_864_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln73_reg_1395 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_s_reg_1401 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_9_reg_1407 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_10_reg_1413 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln42_17_fu_930_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_17_reg_1419 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_fu_972_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_reg_1424 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_20_fu_1018_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_20_reg_1429 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_21_fu_1052_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_21_reg_1434 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_22_fu_1082_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_22_reg_1439 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_25_fu_1128_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_25_reg_1444 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_26_fu_1162_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_26_reg_1449 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_28_fu_1196_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_28_reg_1454 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_154_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_1_fu_157_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_fu_158_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_4_fu_160_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln73_1_fu_163_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_3_fu_164_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_5_fu_165_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln73_fu_166_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_898_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln73_6_fu_909_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_23_fu_916_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln42_29_fu_920_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_24_fu_926_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_fu_905_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln_fu_940_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal and_ln73_s_fu_951_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_25_fu_958_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln42_30_fu_962_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_26_fu_968_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_26_fu_947_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln73_17_fu_986_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal and_ln73_18_fu_997_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_27_fu_1004_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln42_31_fu_1008_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln42_28_fu_1014_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_27_fu_993_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln73_7_fu_1031_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_29_fu_1028_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln42_32_fu_1042_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_29_fu_1048_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_30_fu_1038_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln73_8_fu_1061_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_31_fu_1058_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln42_33_fu_1072_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_30_fu_1078_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_32_fu_1068_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln73_19_fu_1096_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal and_ln73_20_fu_1107_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_31_fu_1114_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln42_34_fu_1118_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_32_fu_1124_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_33_fu_1103_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln73_9_fu_1141_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_35_fu_1138_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln42_35_fu_1152_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_33_fu_1158_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_36_fu_1148_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln73_s_fu_1175_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_37_fu_1172_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln42_36_fu_1186_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_34_fu_1192_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_38_fu_1182_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_16_fu_1205_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_18_fu_1215_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_19_fu_1225_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_23_fu_1241_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_24_fu_1251_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_27_fu_1264_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_5_fu_1270_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_8_fu_1288_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_7_fu_1284_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln42_18_fu_1261_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln70_4_fu_1257_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln70_3_fu_1247_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_6_fu_1281_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln42_15_fu_1238_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_5_fu_1277_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln42_14_fu_1235_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln70_2_fu_1231_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln70_1_fu_1221_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln46_fu_1274_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln70_fu_1211_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln42_fu_1202_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_1291_p17 : STD_LOGIC_VECTOR (475 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_21s_6ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_21s_6ns_27_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;



begin
    mul_21s_6ns_26_1_1_U1058 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_7_reg_1341,
        din1 => mul_ln42_2_fu_154_p1,
        dout => mul_ln42_2_fu_154_p2);

    mul_21s_6ns_26_1_1_U1059 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_6_reg_1336,
        din1 => mul_ln42_1_fu_157_p1,
        dout => mul_ln42_1_fu_157_p2);

    mul_21s_6ns_26_1_1_U1060 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_reg_1331,
        din1 => mul_ln42_fu_158_p1,
        dout => mul_ln42_fu_158_p2);

    mul_21s_6ns_26_1_1_U1061 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_3_reg_1368,
        din1 => mul_ln42_4_fu_160_p1,
        dout => mul_ln42_4_fu_160_p2);

    mul_21s_6ns_27_1_1_U1062 : component myproject_mul_21s_6ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 27)
    port map (
        din0 => a_4_reg_1373,
        din1 => mul_ln73_1_fu_163_p1,
        dout => mul_ln73_1_fu_163_p2);

    mul_21s_6ns_26_1_1_U1063 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_2_reg_1363,
        din1 => mul_ln42_3_fu_164_p1,
        dout => mul_ln42_3_fu_164_p2);

    mul_21s_6ns_26_1_1_U1064 : component myproject_mul_21s_6ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 26)
    port map (
        din0 => a_11_reg_1384,
        din1 => mul_ln42_5_fu_165_p1,
        dout => mul_ln42_5_fu_165_p2);

    mul_21s_6ns_27_1_1_U1065 : component myproject_mul_21s_6ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 6,
        dout_WIDTH => 27)
    port map (
        din0 => a_8_reg_1346,
        din1 => mul_ln73_fu_166_p1,
        dout => mul_ln73_fu_166_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                a_10_reg_1389 <= layer15_out_dout(335 downto 315);
                a_11_reg_1384 <= layer15_out_dout(314 downto 294);
                a_1_reg_1357 <= layer15_out_dout(188 downto 168);
                a_2_reg_1363 <= layer15_out_dout(209 downto 189);
                a_3_reg_1368 <= layer15_out_dout(230 downto 210);
                a_4_reg_1373 <= layer15_out_dout(272 downto 252);
                a_5_reg_1378 <= layer15_out_dout(293 downto 273);
                a_6_reg_1336 <= layer15_out_dout(83 downto 63);
                a_7_reg_1341 <= layer15_out_dout(104 downto 84);
                a_8_reg_1346 <= layer15_out_dout(146 downto 126);
                a_9_reg_1351 <= layer15_out_dout(167 downto 147);
                a_reg_1331 <= layer15_out_dout(41 downto 21);
                tmp_10_reg_1413 <= layer15_out_dout(251 downto 231);
                tmp_9_reg_1407 <= layer15_out_dout(125 downto 105);
                tmp_s_reg_1401 <= layer15_out_dout(62 downto 42);
                trunc_ln73_reg_1395 <= trunc_ln73_fu_864_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    add_ln42_17_reg_1419(25 downto 1) <= add_ln42_17_fu_930_p2(25 downto 1);
                    add_ln42_20_reg_1429(25 downto 2) <= add_ln42_20_fu_1018_p2(25 downto 2);
                add_ln42_21_reg_1434 <= add_ln42_21_fu_1052_p2;
                add_ln42_22_reg_1439 <= add_ln42_22_fu_1082_p2;
                    add_ln42_25_reg_1444(25 downto 1) <= add_ln42_25_fu_1128_p2(25 downto 1);
                add_ln42_26_reg_1449 <= add_ln42_26_fu_1162_p2;
                add_ln42_28_reg_1454 <= add_ln42_28_fu_1196_p2;
                    add_ln42_reg_1424(25 downto 1) <= add_ln42_fu_972_p2(25 downto 1);
                mul_ln42_1_reg_715 <= mul_ln42_1_fu_157_p2;
                mul_ln42_2_reg_719 <= mul_ln42_2_fu_154_p2;
                mul_ln42_3_reg_727 <= mul_ln42_3_fu_164_p2;
                mul_ln42_4_reg_731 <= mul_ln42_4_fu_160_p2;
                mul_ln42_5_reg_739 <= mul_ln42_5_fu_165_p2;
                mul_ln42_reg_711 <= mul_ln42_fu_158_p2;
                mul_ln73_1_reg_735 <= mul_ln73_1_fu_163_p2;
                mul_ln73_reg_723 <= mul_ln73_fu_166_p2;
            end if;
        end if;
    end process;
    add_ln42_17_reg_1419(0) <= '0';
    add_ln42_reg_1424(0) <= '0';
    add_ln42_20_reg_1429(1 downto 0) <= "00";
    add_ln42_25_reg_1444(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer17_out_full_n, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln42_16_fu_1205_p2 <= std_logic_vector(unsigned(mul_ln42_reg_711) + unsigned(ap_const_lv26_3FFC800));
    add_ln42_17_fu_930_p2 <= std_logic_vector(signed(sext_ln42_24_fu_926_p1) + signed(sext_ln73_fu_905_p1));
    add_ln42_18_fu_1215_p2 <= std_logic_vector(unsigned(mul_ln42_1_reg_715) + unsigned(ap_const_lv26_3FFB800));
    add_ln42_19_fu_1225_p2 <= std_logic_vector(unsigned(mul_ln42_2_reg_719) + unsigned(ap_const_lv26_3FFD800));
    add_ln42_20_fu_1018_p2 <= std_logic_vector(signed(sext_ln42_28_fu_1014_p1) + signed(sext_ln73_27_fu_993_p1));
    add_ln42_21_fu_1052_p2 <= std_logic_vector(signed(sext_ln42_29_fu_1048_p1) + signed(sext_ln73_30_fu_1038_p1));
    add_ln42_22_fu_1082_p2 <= std_logic_vector(signed(sext_ln42_30_fu_1078_p1) + signed(sext_ln73_32_fu_1068_p1));
    add_ln42_23_fu_1241_p2 <= std_logic_vector(unsigned(mul_ln42_3_reg_727) + unsigned(ap_const_lv26_3000));
    add_ln42_24_fu_1251_p2 <= std_logic_vector(unsigned(mul_ln42_4_reg_731) + unsigned(ap_const_lv26_3FFF000));
    add_ln42_25_fu_1128_p2 <= std_logic_vector(signed(sext_ln42_32_fu_1124_p1) + signed(sext_ln73_33_fu_1103_p1));
    add_ln42_26_fu_1162_p2 <= std_logic_vector(signed(sext_ln42_33_fu_1158_p1) + signed(sext_ln73_36_fu_1148_p1));
    add_ln42_27_fu_1264_p2 <= std_logic_vector(unsigned(mul_ln42_5_reg_739) + unsigned(ap_const_lv26_3FFF000));
    add_ln42_28_fu_1196_p2 <= std_logic_vector(signed(sext_ln42_34_fu_1192_p1) + signed(sext_ln73_38_fu_1182_p1));
    add_ln42_29_fu_920_p2 <= std_logic_vector(signed(sext_ln42_23_fu_916_p1) + signed(ap_const_lv23_7FC800));
    add_ln42_30_fu_962_p2 <= std_logic_vector(signed(sext_ln42_25_fu_958_p1) + signed(ap_const_lv23_7FC000));
    add_ln42_31_fu_1008_p2 <= std_logic_vector(signed(sext_ln42_27_fu_1004_p1) + signed(ap_const_lv24_2000));
    add_ln42_32_fu_1042_p2 <= std_logic_vector(signed(sext_ln73_29_fu_1028_p1) + signed(ap_const_lv22_2000));
    add_ln42_33_fu_1072_p2 <= std_logic_vector(signed(sext_ln73_31_fu_1058_p1) + signed(ap_const_lv22_3FD000));
    add_ln42_34_fu_1118_p2 <= std_logic_vector(signed(sext_ln42_31_fu_1114_p1) + signed(ap_const_lv23_800));
    add_ln42_35_fu_1152_p2 <= std_logic_vector(signed(sext_ln73_35_fu_1138_p1) + signed(ap_const_lv22_3FE800));
    add_ln42_36_fu_1186_p2 <= std_logic_vector(signed(sext_ln73_37_fu_1172_p1) + signed(ap_const_lv22_3FF800));
    add_ln42_fu_972_p2 <= std_logic_vector(signed(sext_ln42_26_fu_968_p1) + signed(sext_ln73_26_fu_947_p1));
    and_ln73_17_fu_986_p3 <= (tmp_9_reg_1407 & ap_const_lv4_0);
    and_ln73_18_fu_997_p3 <= (tmp_9_reg_1407 & ap_const_lv2_0);
    and_ln73_19_fu_1096_p3 <= (tmp_10_reg_1413 & ap_const_lv4_0);
    and_ln73_20_fu_1107_p3 <= (tmp_10_reg_1413 & ap_const_lv1_0);
    and_ln73_s_fu_951_p3 <= (tmp_s_reg_1401 & ap_const_lv1_0);
    and_ln_fu_940_p3 <= (tmp_s_reg_1401 & ap_const_lv4_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer17_out_full_n)
    begin
        if ((layer17_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer15_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer15_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer17_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    internal_ap_ready_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer15_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer15_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer15_out_blk_n <= layer15_out_empty_n;
        else 
            layer15_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer15_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer15_out_read <= ap_const_logic_1;
        else 
            layer15_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_blk_n_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer17_out_blk_n <= layer17_out_full_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer17_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_1291_p17),480));


    layer17_out_write_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer17_out_write <= ap_const_logic_1;
        else 
            layer17_out_write <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln42_1_fu_157_p1 <= ap_const_lv26_13(6 - 1 downto 0);
    mul_ln42_2_fu_154_p1 <= ap_const_lv26_15(6 - 1 downto 0);
    mul_ln42_3_fu_164_p1 <= ap_const_lv26_17(6 - 1 downto 0);
    mul_ln42_4_fu_160_p1 <= ap_const_lv26_16(6 - 1 downto 0);
    mul_ln42_5_fu_165_p1 <= ap_const_lv26_15(6 - 1 downto 0);
    mul_ln42_fu_158_p1 <= ap_const_lv26_17(6 - 1 downto 0);
    mul_ln73_1_fu_163_p1 <= ap_const_lv27_13(6 - 1 downto 0);
    mul_ln73_fu_166_p1 <= ap_const_lv27_17(6 - 1 downto 0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln42_14_fu_1235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_20_reg_1429),30));

        sext_ln42_15_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_21_reg_1434),30));

        sext_ln42_18_fu_1261_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_25_reg_1444),30));

        sext_ln42_23_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_6_fu_909_p3),23));

        sext_ln42_24_fu_926_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_29_fu_920_p2),26));

        sext_ln42_25_fu_958_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_s_fu_951_p3),23));

        sext_ln42_26_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_30_fu_962_p2),26));

        sext_ln42_27_fu_1004_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_18_fu_997_p3),24));

        sext_ln42_28_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_31_fu_1008_p2),26));

        sext_ln42_29_fu_1048_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_32_fu_1042_p2),26));

        sext_ln42_30_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_33_fu_1072_p2),26));

        sext_ln42_31_fu_1114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_20_fu_1107_p3),23));

        sext_ln42_32_fu_1124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_34_fu_1118_p2),26));

        sext_ln42_33_fu_1158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_35_fu_1152_p2),26));

        sext_ln42_34_fu_1192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_36_fu_1186_p2),26));

        sext_ln42_fu_1202_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_17_reg_1419),30));

        sext_ln46_5_fu_1277_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln73_reg_723),30));

        sext_ln46_6_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_22_reg_1439),30));

        sext_ln46_7_fu_1284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln73_1_reg_735),30));

        sext_ln46_8_fu_1288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_26_reg_1449),30));

        sext_ln46_fu_1274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_reg_1424),30));

        sext_ln70_1_fu_1221_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_18_fu_1215_p2),30));

        sext_ln70_2_fu_1231_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_19_fu_1225_p2),30));

        sext_ln70_3_fu_1247_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_23_fu_1241_p2),30));

        sext_ln70_4_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_24_fu_1251_p2),30));

        sext_ln70_5_fu_1270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_27_fu_1264_p2),30));

        sext_ln70_fu_1211_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_16_fu_1205_p2),30));

        sext_ln73_26_fu_947_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln_fu_940_p3),26));

        sext_ln73_27_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_17_fu_986_p3),26));

        sext_ln73_29_fu_1028_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_9_reg_1351),22));

        sext_ln73_30_fu_1038_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_7_fu_1031_p3),26));

        sext_ln73_31_fu_1058_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_1_reg_1357),22));

        sext_ln73_32_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_8_fu_1061_p3),26));

        sext_ln73_33_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_19_fu_1096_p3),26));

        sext_ln73_35_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_5_reg_1378),22));

        sext_ln73_36_fu_1148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_9_fu_1141_p3),26));

        sext_ln73_37_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_10_reg_1389),22));

        sext_ln73_38_fu_1182_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_s_fu_1175_p3),26));

        sext_ln73_fu_905_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_898_p3),26));

    shl_ln73_6_fu_909_p3 <= (trunc_ln73_reg_1395 & ap_const_lv1_0);
    shl_ln73_7_fu_1031_p3 <= (a_9_reg_1351 & ap_const_lv4_0);
    shl_ln73_8_fu_1061_p3 <= (a_1_reg_1357 & ap_const_lv4_0);
    shl_ln73_9_fu_1141_p3 <= (a_5_reg_1378 & ap_const_lv4_0);
    shl_ln73_s_fu_1175_p3 <= (a_10_reg_1389 & ap_const_lv4_0);
    shl_ln_fu_898_p3 <= (trunc_ln73_reg_1395 & ap_const_lv4_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_1291_p17 <= (((((((((((((((add_ln42_28_reg_1454 & sext_ln70_5_fu_1270_p1) & sext_ln46_8_fu_1288_p1) & sext_ln46_7_fu_1284_p1) & sext_ln42_18_fu_1261_p1) & sext_ln70_4_fu_1257_p1) & sext_ln70_3_fu_1247_p1) & sext_ln46_6_fu_1281_p1) & sext_ln42_15_fu_1238_p1) & sext_ln46_5_fu_1277_p1) & sext_ln42_14_fu_1235_p1) & sext_ln70_2_fu_1231_p1) & sext_ln70_1_fu_1221_p1) & sext_ln46_fu_1274_p1) & sext_ln70_fu_1211_p1) & sext_ln42_fu_1202_p1);
    trunc_ln73_fu_864_p1 <= layer15_out_dout(21 - 1 downto 0);
end behav;
