-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer19_out_dout : IN STD_LOGIC_VECTOR (209 downto 0);
    layer19_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer19_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer19_out_empty_n : IN STD_LOGIC;
    layer19_out_read : OUT STD_LOGIC;
    layer21_out_TDATA : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer21_out_TVALID : OUT STD_LOGIC;
    layer21_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101001";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010010";
    constant ap_const_lv32_93 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010011";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce0 : STD_LOGIC;
    signal exp_table_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce1 : STD_LOGIC;
    signal exp_table_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce2 : STD_LOGIC;
    signal exp_table_q2 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce3 : STD_LOGIC;
    signal exp_table_q3 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce4 : STD_LOGIC;
    signal exp_table_q4 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce5 : STD_LOGIC;
    signal exp_table_q5 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address6 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce6 : STD_LOGIC;
    signal exp_table_q6 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address7 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce7 : STD_LOGIC;
    signal exp_table_q7 : STD_LOGIC_VECTOR (16 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0 : STD_LOGIC;
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal layer19_out_blk_n : STD_LOGIC;
    signal layer21_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal data_array_fu_644_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_reg_2340 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_1_fu_648_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_1_reg_2345 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_2_fu_658_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_2_reg_2350 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_3_fu_668_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_3_reg_2355 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_4_fu_678_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_4_reg_2360 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_5_fu_688_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_5_reg_2365 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_6_fu_698_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_6_reg_2370 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_7_fu_708_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_7_reg_2375 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_8_reg_2380 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_array_9_reg_2387 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_fu_750_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_reg_2394 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_1_fu_770_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_1_reg_2400 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_3_fu_790_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_3_reg_2406 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_4_fu_810_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_4_reg_2412 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_6_fu_862_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_6_reg_2418 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln66_7_fu_880_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_7_reg_2423 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln66_8_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_8_reg_2428 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal select_ln215_17_fu_1603_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_17_reg_2473 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_19_fu_1629_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_19_reg_2478 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_res_reg_2483 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal exp_res_1_reg_2488 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_reg_2493 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_reg_2498 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_reg_2503 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_5_reg_2508 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_6_reg_2513 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_7_reg_2518 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln51_10_fu_1713_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_10_reg_2533 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_32_reg_2539 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_reg_2546 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln51_11_fu_1809_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_11_reg_2553 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_36_reg_2559 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_reg_2566 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_res_8_reg_2573 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exp_res_9_reg_2578 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_41_reg_2583 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_reg_2590 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_2597 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal inv_exp_sum_reg_2608 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln225_fu_1363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_1_fu_1394_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_2_fu_1425_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_3_fu_1456_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_4_fu_1487_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_5_fu_1518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_6_fu_1549_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_7_fu_1580_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_8_fu_1637_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_9_fu_1641_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln235_fu_2157_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal mul_ln244_fu_273_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln244_fu_2162_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_fu_273_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_2_fu_274_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_2_fu_274_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_4_fu_275_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_4_fu_275_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_6_fu_276_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_6_fu_276_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_3_fu_277_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_3_fu_277_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_7_fu_278_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_7_fu_278_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_5_fu_279_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_5_fu_279_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_1_fu_280_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_1_fu_280_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_8_fu_281_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_8_fu_281_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln244_9_fu_282_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln244_9_fu_282_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln66_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_4_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_5_fu_834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_5_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_2_fu_828_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln66_5_fu_844_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln66_6_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_6_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_7_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_7_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_8_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_max_fu_897_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln215_fu_903_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln215_1_fu_906_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_fu_910_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_10_fu_916_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_924_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_2_fu_950_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_1_fu_953_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_12_fu_959_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_967_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_2_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_3_fu_993_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_2_fu_996_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_14_fu_1002_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_1010_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_4_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_4_fu_1036_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_3_fu_1039_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_16_fu_1045_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_1053_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_6_fu_1061_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_5_fu_1079_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_4_fu_1082_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_18_fu_1088_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_1096_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_8_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_6_fu_1122_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_5_fu_1125_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_20_fu_1131_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_1139_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_10_fu_1147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_7_fu_1165_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_6_fu_1168_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_22_fu_1174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_1182_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_12_fu_1190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_8_fu_1208_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_7_fu_1211_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_24_fu_1217_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_1225_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_14_fu_1233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_9_fu_1251_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_8_fu_1254_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_26_fu_1260_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_1268_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_16_fu_1276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln215_10_fu_1294_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln215_9_fu_1297_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_28_fu_1303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_1311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_18_fu_1319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln215_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_1_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_fu_1337_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_1345_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_1_fu_1355_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_1_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_3_fu_987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_2_fu_1368_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_1376_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_3_fu_1386_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_2_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_5_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_4_fu_1399_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_1407_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_5_fu_1417_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_3_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_7_fu_1073_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_6_fu_1430_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_1438_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_7_fu_1448_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_4_fu_1110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_9_fu_1116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_8_fu_1461_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_1469_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_9_fu_1479_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_5_fu_1153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_11_fu_1159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_10_fu_1492_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_fu_1500_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_11_fu_1510_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_6_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_13_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_12_fu_1523_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_1531_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_13_fu_1541_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_7_fu_1239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_15_fu_1245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_14_fu_1554_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_1562_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln215_15_fu_1572_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_8_fu_1282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_17_fu_1288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_16_fu_1585_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_fu_1593_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln215_9_fu_1325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln215_19_fu_1331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln215_18_fu_1611_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_1619_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_3_fu_1649_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_2_fu_1645_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_3_fu_1653_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_30_fu_1659_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln51_5_fu_1679_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_4_fu_1675_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_4_fu_1683_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_31_fu_1689_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_3_fu_1667_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_4_fu_1697_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln51_5_fu_1709_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln51_4_fu_1705_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_5_fu_1719_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln51_7_fu_1745_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_6_fu_1741_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_6_fu_1749_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_34_fu_1755_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln51_9_fu_1775_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_8_fu_1771_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_7_fu_1779_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_35_fu_1785_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_8_fu_1763_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_9_fu_1793_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln51_7_fu_1805_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln51_6_fu_1801_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_8_fu_1815_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal xor_ln51_2_fu_1837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_7_fu_1847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_8_fu_1857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_3_fu_1842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_9_fu_1861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_4_fu_1852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_1_fu_1867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_5_fu_1873_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_6_fu_1880_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal xor_ln51_10_fu_1895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_11_fu_1905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_12_fu_1915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_5_fu_1900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_13_fu_1919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_6_fu_1910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_2_fu_1925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_10_fu_1931_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_11_fu_1938_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_7_fu_1887_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_12_fu_1945_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln51_fu_1953_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln51_1_fu_1957_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_fu_1967_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_12_fu_1961_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_38_fu_1973_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_1981_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_fu_1989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_fu_1995_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_1_fu_2001_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_fu_2007_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_1_fu_2027_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln51_fu_2023_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_1_fu_2031_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_40_fu_2037_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_1_fu_2015_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln51_2_fu_2045_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln51_2_fu_2053_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln51_3_fu_2057_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_2_fu_2067_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln51_9_fu_2061_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal xor_ln51_3_fu_2099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_4_fu_2109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_5_fu_2119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_1_fu_2104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln51_6_fu_2123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_2_fu_2114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_fu_2129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_13_fu_2135_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_14_fu_2142_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_15_fu_2149_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln244_fu_273_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_1_fu_280_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_2_fu_274_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_3_fu_277_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_4_fu_275_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_5_fu_279_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_6_fu_276_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_7_fu_278_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_8_fu_281_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_9_fu_282_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln244_9_fu_2305_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_8_fu_2291_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_7_fu_2277_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_6_fu_2263_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_5_fu_2249_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_4_fu_2235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_3_fu_2221_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_2_fu_2207_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln244_1_fu_2193_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1_fu_2179_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal mul_ln244_1_fu_280_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_2_fu_274_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_3_fu_277_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_4_fu_275_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_5_fu_279_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_6_fu_276_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_7_fu_278_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_8_fu_281_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_9_fu_282_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln244_fu_273_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_17ns_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_exp_tablZio IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address6 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address7 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_invert_t0iy IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_exp_tablZio
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2,
        q2 => exp_table_q2,
        address3 => exp_table_address3,
        ce3 => exp_table_ce3,
        q3 => exp_table_q3,
        address4 => exp_table_address4,
        ce4 => exp_table_ce4,
        q4 => exp_table_q4,
        address5 => exp_table_address5,
        ce5 => exp_table_ce5,
        q5 => exp_table_q5,
        address6 => exp_table_address6,
        ce6 => exp_table_ce6,
        q6 => exp_table_q6,
        address7 => exp_table_address7,
        ce7 => exp_table_ce7,
        q7 => exp_table_q7);

    invert_table_U : component myproject_softmax_stable_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s_invert_t0iy
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0,
        q0 => invert_table_q0);

    mul_18s_17ns_24_1_1_U1124 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_fu_273_p0,
        din1 => mul_ln244_fu_273_p1,
        dout => mul_ln244_fu_273_p2);

    mul_18s_17ns_24_1_1_U1125 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_2_fu_274_p0,
        din1 => mul_ln244_2_fu_274_p1,
        dout => mul_ln244_2_fu_274_p2);

    mul_18s_17ns_24_1_1_U1126 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_4_fu_275_p0,
        din1 => mul_ln244_4_fu_275_p1,
        dout => mul_ln244_4_fu_275_p2);

    mul_18s_17ns_24_1_1_U1127 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_6_fu_276_p0,
        din1 => mul_ln244_6_fu_276_p1,
        dout => mul_ln244_6_fu_276_p2);

    mul_18s_17ns_24_1_1_U1128 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_3_fu_277_p0,
        din1 => mul_ln244_3_fu_277_p1,
        dout => mul_ln244_3_fu_277_p2);

    mul_18s_17ns_24_1_1_U1129 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_7_fu_278_p0,
        din1 => mul_ln244_7_fu_278_p1,
        dout => mul_ln244_7_fu_278_p2);

    mul_18s_17ns_24_1_1_U1130 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_5_fu_279_p0,
        din1 => mul_ln244_5_fu_279_p1,
        dout => mul_ln244_5_fu_279_p2);

    mul_18s_17ns_24_1_1_U1131 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_1_fu_280_p0,
        din1 => mul_ln244_1_fu_280_p1,
        dout => mul_ln244_1_fu_280_p2);

    mul_18s_17ns_24_1_1_U1132 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_8_fu_281_p0,
        din1 => mul_ln244_8_fu_281_p1,
        dout => mul_ln244_8_fu_281_p2);

    mul_18s_17ns_24_1_1_U1133 : component myproject_mul_18s_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln244_9_fu_282_p0,
        din1 => mul_ln244_9_fu_282_p1,
        dout => mul_ln244_9_fu_282_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln51_10_reg_2533 <= add_ln51_10_fu_1713_p2;
                add_ln51_11_reg_2553 <= add_ln51_11_fu_1809_p2;
                exp_res_1_reg_2488 <= exp_table_q6;
                exp_res_2_reg_2493 <= exp_table_q5;
                exp_res_3_reg_2498 <= exp_table_q4;
                exp_res_4_reg_2503 <= exp_table_q3;
                exp_res_5_reg_2508 <= exp_table_q2;
                exp_res_6_reg_2513 <= exp_table_q1;
                exp_res_7_reg_2518 <= exp_table_q0;
                exp_res_reg_2483 <= exp_table_q7;
                tmp_32_reg_2539 <= add_ln51_5_fu_1719_p2(18 downto 18);
                tmp_33_reg_2546 <= add_ln51_10_fu_1713_p2(17 downto 17);
                tmp_36_reg_2559 <= add_ln51_8_fu_1815_p2(18 downto 18);
                tmp_37_reg_2566 <= add_ln51_11_fu_1809_p2(17 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                data_array_1_reg_2345 <= layer19_out_dout(41 downto 21);
                data_array_2_reg_2350 <= layer19_out_dout(62 downto 42);
                data_array_3_reg_2355 <= layer19_out_dout(83 downto 63);
                data_array_4_reg_2360 <= layer19_out_dout(104 downto 84);
                data_array_5_reg_2365 <= layer19_out_dout(125 downto 105);
                data_array_6_reg_2370 <= layer19_out_dout(146 downto 126);
                data_array_7_reg_2375 <= layer19_out_dout(167 downto 147);
                data_array_8_reg_2380 <= layer19_out_dout(188 downto 168);
                data_array_9_reg_2387 <= layer19_out_dout(209 downto 189);
                data_array_reg_2340 <= data_array_fu_644_p1;
                select_ln66_1_reg_2400 <= select_ln66_1_fu_770_p3;
                select_ln66_3_reg_2406 <= select_ln66_3_fu_790_p3;
                select_ln66_4_reg_2412 <= select_ln66_4_fu_810_p3;
                select_ln66_reg_2394 <= select_ln66_fu_750_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                exp_res_8_reg_2573 <= exp_table_q1;
                exp_res_9_reg_2578 <= exp_table_q0;
                tmp_41_reg_2583 <= add_ln51_2_fu_2067_p2(18 downto 18);
                tmp_42_reg_2590 <= add_ln51_9_fu_2061_p2(17 downto 17);
                tmp_9_reg_2597 <= add_ln51_9_fu_2061_p2(17 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln66_8_reg_2428 <= icmp_ln66_8_fu_886_p2;
                select_ln66_6_reg_2418 <= select_ln66_6_fu_862_p3;
                select_ln66_7_reg_2423 <= select_ln66_7_fu_880_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                inv_exp_sum_reg_2608 <= invert_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                select_ln215_17_reg_2473 <= select_ln215_17_fu_1603_p3;
                select_ln215_19_reg_2478 <= select_ln215_19_fu_1629_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer21_out_TREADY, ap_CS_fsm_state8, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((layer21_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln51_10_fu_1713_p2 <= std_logic_vector(signed(select_ln51_4_fu_1697_p3) + signed(select_ln51_3_fu_1667_p3));
    add_ln51_11_fu_1809_p2 <= std_logic_vector(signed(select_ln51_9_fu_1793_p3) + signed(select_ln51_8_fu_1763_p3));
    add_ln51_12_fu_1961_p2 <= std_logic_vector(signed(select_ln51_7_fu_1887_p3) + signed(select_ln51_12_fu_1945_p3));
    add_ln51_1_fu_2031_p2 <= std_logic_vector(unsigned(zext_ln51_1_fu_2027_p1) + unsigned(zext_ln51_fu_2023_p1));
    add_ln51_2_fu_2067_p2 <= std_logic_vector(signed(sext_ln51_2_fu_2053_p1) + signed(sext_ln51_3_fu_2057_p1));
    add_ln51_3_fu_1653_p2 <= std_logic_vector(unsigned(zext_ln51_3_fu_1649_p1) + unsigned(zext_ln51_2_fu_1645_p1));
    add_ln51_4_fu_1683_p2 <= std_logic_vector(unsigned(zext_ln51_5_fu_1679_p1) + unsigned(zext_ln51_4_fu_1675_p1));
    add_ln51_5_fu_1719_p2 <= std_logic_vector(signed(sext_ln51_5_fu_1709_p1) + signed(sext_ln51_4_fu_1705_p1));
    add_ln51_6_fu_1749_p2 <= std_logic_vector(unsigned(zext_ln51_7_fu_1745_p1) + unsigned(zext_ln51_6_fu_1741_p1));
    add_ln51_7_fu_1779_p2 <= std_logic_vector(unsigned(zext_ln51_9_fu_1775_p1) + unsigned(zext_ln51_8_fu_1771_p1));
    add_ln51_8_fu_1815_p2 <= std_logic_vector(signed(sext_ln51_7_fu_1805_p1) + signed(sext_ln51_6_fu_1801_p1));
    add_ln51_9_fu_2061_p2 <= std_logic_vector(signed(select_ln51_1_fu_2015_p3) + signed(select_ln51_2_fu_2045_p3));
    add_ln51_fu_1967_p2 <= std_logic_vector(signed(sext_ln51_fu_1953_p1) + signed(sext_ln51_1_fu_1957_p1));
    and_ln215_1_fu_981_p2 <= (xor_ln215_2_fu_975_p2 and tmp_13_fu_967_p3);
    and_ln215_2_fu_1024_p2 <= (xor_ln215_4_fu_1018_p2 and tmp_15_fu_1010_p3);
    and_ln215_3_fu_1067_p2 <= (xor_ln215_6_fu_1061_p2 and tmp_17_fu_1053_p3);
    and_ln215_4_fu_1110_p2 <= (xor_ln215_8_fu_1104_p2 and tmp_19_fu_1096_p3);
    and_ln215_5_fu_1153_p2 <= (xor_ln215_10_fu_1147_p2 and tmp_21_fu_1139_p3);
    and_ln215_6_fu_1196_p2 <= (xor_ln215_12_fu_1190_p2 and tmp_23_fu_1182_p3);
    and_ln215_7_fu_1239_p2 <= (xor_ln215_14_fu_1233_p2 and tmp_25_fu_1225_p3);
    and_ln215_8_fu_1282_p2 <= (xor_ln215_16_fu_1276_p2 and tmp_27_fu_1268_p3);
    and_ln215_9_fu_1325_p2 <= (xor_ln215_18_fu_1319_p2 and tmp_29_fu_1311_p3);
    and_ln215_fu_938_p2 <= (xor_ln215_fu_932_p2 and tmp_11_fu_924_p3);
    and_ln51_1_fu_2104_p2 <= (xor_ln51_3_fu_2099_p2 and tmp_42_reg_2590);
    and_ln51_2_fu_2114_p2 <= (xor_ln51_4_fu_2109_p2 and tmp_41_reg_2583);
    and_ln51_3_fu_1842_p2 <= (xor_ln51_2_fu_1837_p2 and tmp_33_reg_2546);
    and_ln51_4_fu_1852_p2 <= (xor_ln51_7_fu_1847_p2 and tmp_32_reg_2539);
    and_ln51_5_fu_1900_p2 <= (xor_ln51_10_fu_1895_p2 and tmp_37_reg_2566);
    and_ln51_6_fu_1910_p2 <= (xor_ln51_11_fu_1905_p2 and tmp_36_reg_2559);
    and_ln51_fu_1995_p2 <= (xor_ln51_fu_1989_p2 and tmp_39_fu_1981_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(layer21_out_TREADY)
    begin
        if ((layer21_out_TREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, layer19_out_empty_n)
    begin
                ap_block_state1 <= ((layer19_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    data_array_1_fu_648_p4 <= layer19_out_dout(41 downto 21);
    data_array_2_fu_658_p4 <= layer19_out_dout(62 downto 42);
    data_array_3_fu_668_p4 <= layer19_out_dout(83 downto 63);
    data_array_4_fu_678_p4 <= layer19_out_dout(104 downto 84);
    data_array_5_fu_688_p4 <= layer19_out_dout(125 downto 105);
    data_array_6_fu_698_p4 <= layer19_out_dout(146 downto 126);
    data_array_7_fu_708_p4 <= layer19_out_dout(167 downto 147);
    data_array_fu_644_p1 <= layer19_out_dout(21 - 1 downto 0);

    exp_table_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, zext_ln225_7_fu_1580_p1, zext_ln225_9_fu_1641_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            exp_table_address0 <= zext_ln225_9_fu_1641_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_address0 <= zext_ln225_7_fu_1580_p1(10 - 1 downto 0);
        else 
            exp_table_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table_address1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, zext_ln225_6_fu_1549_p1, zext_ln225_8_fu_1637_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            exp_table_address1 <= zext_ln225_8_fu_1637_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_address1 <= zext_ln225_6_fu_1549_p1(10 - 1 downto 0);
        else 
            exp_table_address1 <= "XXXXXXXXXX";
        end if; 
    end process;

    exp_table_address2 <= zext_ln225_5_fu_1518_p1(10 - 1 downto 0);
    exp_table_address3 <= zext_ln225_4_fu_1487_p1(10 - 1 downto 0);
    exp_table_address4 <= zext_ln225_3_fu_1456_p1(10 - 1 downto 0);
    exp_table_address5 <= zext_ln225_2_fu_1425_p1(10 - 1 downto 0);
    exp_table_address6 <= zext_ln225_1_fu_1394_p1(10 - 1 downto 0);
    exp_table_address7 <= zext_ln225_fu_1363_p1(10 - 1 downto 0);

    exp_table_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            exp_table_ce0 <= ap_const_logic_1;
        else 
            exp_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            exp_table_ce1 <= ap_const_logic_1;
        else 
            exp_table_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce2 <= ap_const_logic_1;
        else 
            exp_table_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce3_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce3 <= ap_const_logic_1;
        else 
            exp_table_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce4_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce4 <= ap_const_logic_1;
        else 
            exp_table_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce5_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce5 <= ap_const_logic_1;
        else 
            exp_table_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce6_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce6 <= ap_const_logic_1;
        else 
            exp_table_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce7_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_ce7 <= ap_const_logic_1;
        else 
            exp_table_ce7 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_1_fu_758_p2 <= "1" when (signed(data_array_2_fu_658_p4) < signed(data_array_3_fu_668_p4)) else "0";
    icmp_ln66_2_fu_818_p2 <= "1" when (signed(select_ln66_reg_2394) < signed(select_ln66_1_reg_2400)) else "0";
    icmp_ln66_3_fu_778_p2 <= "1" when (signed(data_array_4_fu_678_p4) < signed(data_array_5_fu_688_p4)) else "0";
    icmp_ln66_4_fu_798_p2 <= "1" when (signed(data_array_6_fu_698_p4) < signed(data_array_7_fu_708_p4)) else "0";
    icmp_ln66_5_fu_834_p2 <= "1" when (signed(select_ln66_3_reg_2406) < signed(select_ln66_4_reg_2412)) else "0";
    icmp_ln66_6_fu_850_p2 <= "1" when (signed(select_ln66_2_fu_828_p3) < signed(select_ln66_5_fu_844_p3)) else "0";
    icmp_ln66_7_fu_870_p2 <= "1" when (signed(data_array_8_reg_2380) < signed(data_array_9_reg_2387)) else "0";
    icmp_ln66_8_fu_886_p2 <= "1" when (signed(select_ln66_6_fu_862_p3) < signed(select_ln66_7_fu_880_p3)) else "0";
    icmp_ln66_fu_738_p2 <= "1" when (signed(data_array_fu_644_p1) < signed(data_array_1_fu_648_p4)) else "0";
    invert_table_address0 <= zext_ln235_fu_2157_p1(10 - 1 downto 0);

    invert_table_ce0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            invert_table_ce0 <= ap_const_logic_1;
        else 
            invert_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    layer19_out_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, layer19_out_empty_n)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            layer19_out_blk_n <= layer19_out_empty_n;
        else 
            layer19_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer19_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer19_out_read <= ap_const_logic_1;
        else 
            layer19_out_read <= ap_const_logic_0;
        end if; 
    end process;

    layer21_out_TDATA <= (((((((((trunc_ln244_9_fu_2305_p4 & trunc_ln244_8_fu_2291_p4) & trunc_ln244_7_fu_2277_p4) & trunc_ln244_6_fu_2263_p4) & trunc_ln244_5_fu_2249_p4) & trunc_ln244_4_fu_2235_p4) & trunc_ln244_3_fu_2221_p4) & trunc_ln244_2_fu_2207_p4) & trunc_ln244_1_fu_2193_p4) & trunc_ln1_fu_2179_p4);

    layer21_out_TDATA_blk_n_assign_proc : process(layer21_out_TREADY, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            layer21_out_TDATA_blk_n <= layer21_out_TREADY;
        else 
            layer21_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer21_out_TVALID_assign_proc : process(layer21_out_TREADY, ap_CS_fsm_state8)
    begin
        if (((layer21_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            layer21_out_TVALID <= ap_const_logic_1;
        else 
            layer21_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln244_1_fu_280_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_1_fu_280_p1 <= mul_ln244_1_fu_280_p10(17 - 1 downto 0);
    mul_ln244_1_fu_280_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_1_reg_2488),24));
    mul_ln244_2_fu_274_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_2_fu_274_p1 <= mul_ln244_2_fu_274_p10(17 - 1 downto 0);
    mul_ln244_2_fu_274_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_2_reg_2493),24));
    mul_ln244_3_fu_277_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_3_fu_277_p1 <= mul_ln244_3_fu_277_p10(17 - 1 downto 0);
    mul_ln244_3_fu_277_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_3_reg_2498),24));
    mul_ln244_4_fu_275_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_4_fu_275_p1 <= mul_ln244_4_fu_275_p10(17 - 1 downto 0);
    mul_ln244_4_fu_275_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_4_reg_2503),24));
    mul_ln244_5_fu_279_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_5_fu_279_p1 <= mul_ln244_5_fu_279_p10(17 - 1 downto 0);
    mul_ln244_5_fu_279_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_5_reg_2508),24));
    mul_ln244_6_fu_276_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_6_fu_276_p1 <= mul_ln244_6_fu_276_p10(17 - 1 downto 0);
    mul_ln244_6_fu_276_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_6_reg_2513),24));
    mul_ln244_7_fu_278_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_7_fu_278_p1 <= mul_ln244_7_fu_278_p10(17 - 1 downto 0);
    mul_ln244_7_fu_278_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_7_reg_2518),24));
    mul_ln244_8_fu_281_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_8_fu_281_p1 <= mul_ln244_8_fu_281_p10(17 - 1 downto 0);
    mul_ln244_8_fu_281_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_8_reg_2573),24));
    mul_ln244_9_fu_282_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_9_fu_282_p1 <= mul_ln244_9_fu_282_p10(17 - 1 downto 0);
    mul_ln244_9_fu_282_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_9_reg_2578),24));
    mul_ln244_fu_273_p0 <= sext_ln244_fu_2162_p1(18 - 1 downto 0);
    mul_ln244_fu_273_p1 <= mul_ln244_fu_273_p10(17 - 1 downto 0);
    mul_ln244_fu_273_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_reg_2483),24));
    or_ln51_1_fu_1867_p2 <= (xor_ln51_9_fu_1861_p2 or and_ln51_3_fu_1842_p2);
    or_ln51_2_fu_1925_p2 <= (xor_ln51_13_fu_1919_p2 or and_ln51_5_fu_1900_p2);
    or_ln51_fu_2129_p2 <= (xor_ln51_6_fu_2123_p2 or and_ln51_1_fu_2104_p2);
    select_ln215_10_fu_1492_p3 <= 
        ap_const_lv10_1FF when (and_ln215_5_fu_1153_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_11_fu_1510_p3 <= 
        select_ln215_10_fu_1492_p3 when (xor_ln215_11_fu_1159_p2(0) = '1') else 
        tmp_5_fu_1500_p4;
    select_ln215_12_fu_1523_p3 <= 
        ap_const_lv10_1FF when (and_ln215_6_fu_1196_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_13_fu_1541_p3 <= 
        select_ln215_12_fu_1523_p3 when (xor_ln215_13_fu_1202_p2(0) = '1') else 
        tmp_6_fu_1531_p4;
    select_ln215_14_fu_1554_p3 <= 
        ap_const_lv10_1FF when (and_ln215_7_fu_1239_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_15_fu_1572_p3 <= 
        select_ln215_14_fu_1554_p3 when (xor_ln215_15_fu_1245_p2(0) = '1') else 
        tmp_7_fu_1562_p4;
    select_ln215_16_fu_1585_p3 <= 
        ap_const_lv10_1FF when (and_ln215_8_fu_1282_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_17_fu_1603_p3 <= 
        select_ln215_16_fu_1585_p3 when (xor_ln215_17_fu_1288_p2(0) = '1') else 
        tmp_8_fu_1593_p4;
    select_ln215_18_fu_1611_p3 <= 
        ap_const_lv10_1FF when (and_ln215_9_fu_1325_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_19_fu_1629_p3 <= 
        select_ln215_18_fu_1611_p3 when (xor_ln215_19_fu_1331_p2(0) = '1') else 
        tmp_s_fu_1619_p4;
    select_ln215_1_fu_1355_p3 <= 
        select_ln215_fu_1337_p3 when (xor_ln215_1_fu_944_p2(0) = '1') else 
        tmp_fu_1345_p4;
    select_ln215_2_fu_1368_p3 <= 
        ap_const_lv10_1FF when (and_ln215_1_fu_981_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_3_fu_1386_p3 <= 
        select_ln215_2_fu_1368_p3 when (xor_ln215_3_fu_987_p2(0) = '1') else 
        tmp_1_fu_1376_p4;
    select_ln215_4_fu_1399_p3 <= 
        ap_const_lv10_1FF when (and_ln215_2_fu_1024_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_5_fu_1417_p3 <= 
        select_ln215_4_fu_1399_p3 when (xor_ln215_5_fu_1030_p2(0) = '1') else 
        tmp_2_fu_1407_p4;
    select_ln215_6_fu_1430_p3 <= 
        ap_const_lv10_1FF when (and_ln215_3_fu_1067_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_7_fu_1448_p3 <= 
        select_ln215_6_fu_1430_p3 when (xor_ln215_7_fu_1073_p2(0) = '1') else 
        tmp_3_fu_1438_p4;
    select_ln215_8_fu_1461_p3 <= 
        ap_const_lv10_1FF when (and_ln215_4_fu_1110_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln215_9_fu_1479_p3 <= 
        select_ln215_8_fu_1461_p3 when (xor_ln215_9_fu_1116_p2(0) = '1') else 
        tmp_4_fu_1469_p4;
    select_ln215_fu_1337_p3 <= 
        ap_const_lv10_1FF when (and_ln215_fu_938_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln51_10_fu_1931_p3 <= 
        ap_const_lv18_1FFFF when (xor_ln51_12_fu_1915_p2(0) = '1') else 
        add_ln51_11_reg_2553;
    select_ln51_11_fu_1938_p3 <= 
        ap_const_lv18_20000 when (and_ln51_6_fu_1910_p2(0) = '1') else 
        add_ln51_11_reg_2553;
    select_ln51_12_fu_1945_p3 <= 
        select_ln51_10_fu_1931_p3 when (or_ln51_2_fu_1925_p2(0) = '1') else 
        select_ln51_11_fu_1938_p3;
    select_ln51_13_fu_2135_p3 <= 
        ap_const_lv10_1FF when (xor_ln51_5_fu_2119_p2(0) = '1') else 
        tmp_9_reg_2597;
    select_ln51_14_fu_2142_p3 <= 
        ap_const_lv10_200 when (and_ln51_2_fu_2114_p2(0) = '1') else 
        tmp_9_reg_2597;
    select_ln51_15_fu_2149_p3 <= 
        select_ln51_13_fu_2135_p3 when (or_ln51_fu_2129_p2(0) = '1') else 
        select_ln51_14_fu_2142_p3;
    select_ln51_1_fu_2015_p3 <= 
        select_ln51_fu_2007_p3 when (xor_ln51_1_fu_2001_p2(0) = '1') else 
        add_ln51_12_fu_1961_p2;
    select_ln51_2_fu_2045_p3 <= 
        ap_const_lv18_1FFFF when (tmp_40_fu_2037_p3(0) = '1') else 
        add_ln51_1_fu_2031_p2;
    select_ln51_3_fu_1667_p3 <= 
        ap_const_lv18_1FFFF when (tmp_30_fu_1659_p3(0) = '1') else 
        add_ln51_3_fu_1653_p2;
    select_ln51_4_fu_1697_p3 <= 
        ap_const_lv18_1FFFF when (tmp_31_fu_1689_p3(0) = '1') else 
        add_ln51_4_fu_1683_p2;
    select_ln51_5_fu_1873_p3 <= 
        ap_const_lv18_1FFFF when (xor_ln51_8_fu_1857_p2(0) = '1') else 
        add_ln51_10_reg_2533;
    select_ln51_6_fu_1880_p3 <= 
        ap_const_lv18_20000 when (and_ln51_4_fu_1852_p2(0) = '1') else 
        add_ln51_10_reg_2533;
    select_ln51_7_fu_1887_p3 <= 
        select_ln51_5_fu_1873_p3 when (or_ln51_1_fu_1867_p2(0) = '1') else 
        select_ln51_6_fu_1880_p3;
    select_ln51_8_fu_1763_p3 <= 
        ap_const_lv18_1FFFF when (tmp_34_fu_1755_p3(0) = '1') else 
        add_ln51_6_fu_1749_p2;
    select_ln51_9_fu_1793_p3 <= 
        ap_const_lv18_1FFFF when (tmp_35_fu_1785_p3(0) = '1') else 
        add_ln51_7_fu_1779_p2;
    select_ln51_fu_2007_p3 <= 
        ap_const_lv18_1FFFF when (and_ln51_fu_1995_p2(0) = '1') else 
        ap_const_lv18_20000;
    select_ln66_1_fu_770_p3 <= 
        data_array_2_fu_658_p4 when (xor_ln66_1_fu_764_p2(0) = '1') else 
        data_array_3_fu_668_p4;
    select_ln66_2_fu_828_p3 <= 
        select_ln66_reg_2394 when (xor_ln66_2_fu_822_p2(0) = '1') else 
        select_ln66_1_reg_2400;
    select_ln66_3_fu_790_p3 <= 
        data_array_4_fu_678_p4 when (xor_ln66_3_fu_784_p2(0) = '1') else 
        data_array_5_fu_688_p4;
    select_ln66_4_fu_810_p3 <= 
        data_array_6_fu_698_p4 when (xor_ln66_4_fu_804_p2(0) = '1') else 
        data_array_7_fu_708_p4;
    select_ln66_5_fu_844_p3 <= 
        select_ln66_3_reg_2406 when (xor_ln66_5_fu_838_p2(0) = '1') else 
        select_ln66_4_reg_2412;
    select_ln66_6_fu_862_p3 <= 
        select_ln66_2_fu_828_p3 when (xor_ln66_6_fu_856_p2(0) = '1') else 
        select_ln66_5_fu_844_p3;
    select_ln66_7_fu_880_p3 <= 
        data_array_8_reg_2380 when (xor_ln66_7_fu_874_p2(0) = '1') else 
        data_array_9_reg_2387;
    select_ln66_fu_750_p3 <= 
        data_array_fu_644_p1 when (xor_ln66_fu_744_p2(0) = '1') else 
        data_array_1_fu_648_p4;
        sext_ln215_10_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_9_reg_2387),22));

        sext_ln215_1_fu_906_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_max_fu_897_p3),22));

        sext_ln215_2_fu_950_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_1_reg_2345),22));

        sext_ln215_3_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_2_reg_2350),22));

        sext_ln215_4_fu_1036_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_3_reg_2355),22));

        sext_ln215_5_fu_1079_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_4_reg_2360),22));

        sext_ln215_6_fu_1122_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_5_reg_2365),22));

        sext_ln215_7_fu_1165_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_6_reg_2370),22));

        sext_ln215_8_fu_1208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_7_reg_2375),22));

        sext_ln215_9_fu_1251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_8_reg_2380),22));

        sext_ln215_fu_903_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_array_reg_2340),22));

        sext_ln244_fu_2162_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_reg_2608),24));

        sext_ln51_1_fu_1957_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_12_fu_1945_p3),19));

        sext_ln51_2_fu_2053_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_1_fu_2015_p3),19));

        sext_ln51_3_fu_2057_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_2_fu_2045_p3),19));

        sext_ln51_4_fu_1705_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_3_fu_1667_p3),19));

        sext_ln51_5_fu_1709_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_4_fu_1697_p3),19));

        sext_ln51_6_fu_1801_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_8_fu_1763_p3),19));

        sext_ln51_7_fu_1805_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_9_fu_1793_p3),19));

        sext_ln51_fu_1953_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln51_7_fu_1887_p3),19));

    sub_ln215_1_fu_953_p2 <= std_logic_vector(signed(sext_ln215_2_fu_950_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_2_fu_996_p2 <= std_logic_vector(signed(sext_ln215_3_fu_993_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_3_fu_1039_p2 <= std_logic_vector(signed(sext_ln215_4_fu_1036_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_4_fu_1082_p2 <= std_logic_vector(signed(sext_ln215_5_fu_1079_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_5_fu_1125_p2 <= std_logic_vector(signed(sext_ln215_6_fu_1122_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_6_fu_1168_p2 <= std_logic_vector(signed(sext_ln215_7_fu_1165_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_7_fu_1211_p2 <= std_logic_vector(signed(sext_ln215_8_fu_1208_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_8_fu_1254_p2 <= std_logic_vector(signed(sext_ln215_9_fu_1251_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_9_fu_1297_p2 <= std_logic_vector(signed(sext_ln215_10_fu_1294_p1) - signed(sext_ln215_1_fu_906_p1));
    sub_ln215_fu_910_p2 <= std_logic_vector(signed(sext_ln215_fu_903_p1) - signed(sext_ln215_1_fu_906_p1));
    tmp_10_fu_916_p3 <= sub_ln215_fu_910_p2(21 downto 21);
    tmp_11_fu_924_p3 <= sub_ln215_fu_910_p2(20 downto 20);
    tmp_12_fu_959_p3 <= sub_ln215_1_fu_953_p2(21 downto 21);
    tmp_13_fu_967_p3 <= sub_ln215_1_fu_953_p2(20 downto 20);
    tmp_14_fu_1002_p3 <= sub_ln215_2_fu_996_p2(21 downto 21);
    tmp_15_fu_1010_p3 <= sub_ln215_2_fu_996_p2(20 downto 20);
    tmp_16_fu_1045_p3 <= sub_ln215_3_fu_1039_p2(21 downto 21);
    tmp_17_fu_1053_p3 <= sub_ln215_3_fu_1039_p2(20 downto 20);
    tmp_18_fu_1088_p3 <= sub_ln215_4_fu_1082_p2(21 downto 21);
    tmp_19_fu_1096_p3 <= sub_ln215_4_fu_1082_p2(20 downto 20);
    tmp_1_fu_1376_p4 <= sub_ln215_1_fu_953_p2(20 downto 11);
    tmp_20_fu_1131_p3 <= sub_ln215_5_fu_1125_p2(21 downto 21);
    tmp_21_fu_1139_p3 <= sub_ln215_5_fu_1125_p2(20 downto 20);
    tmp_22_fu_1174_p3 <= sub_ln215_6_fu_1168_p2(21 downto 21);
    tmp_23_fu_1182_p3 <= sub_ln215_6_fu_1168_p2(20 downto 20);
    tmp_24_fu_1217_p3 <= sub_ln215_7_fu_1211_p2(21 downto 21);
    tmp_25_fu_1225_p3 <= sub_ln215_7_fu_1211_p2(20 downto 20);
    tmp_26_fu_1260_p3 <= sub_ln215_8_fu_1254_p2(21 downto 21);
    tmp_27_fu_1268_p3 <= sub_ln215_8_fu_1254_p2(20 downto 20);
    tmp_28_fu_1303_p3 <= sub_ln215_9_fu_1297_p2(21 downto 21);
    tmp_29_fu_1311_p3 <= sub_ln215_9_fu_1297_p2(20 downto 20);
    tmp_2_fu_1407_p4 <= sub_ln215_2_fu_996_p2(20 downto 11);
    tmp_30_fu_1659_p3 <= add_ln51_3_fu_1653_p2(17 downto 17);
    tmp_31_fu_1689_p3 <= add_ln51_4_fu_1683_p2(17 downto 17);
    tmp_34_fu_1755_p3 <= add_ln51_6_fu_1749_p2(17 downto 17);
    tmp_35_fu_1785_p3 <= add_ln51_7_fu_1779_p2(17 downto 17);
    tmp_38_fu_1973_p3 <= add_ln51_fu_1967_p2(18 downto 18);
    tmp_39_fu_1981_p3 <= add_ln51_12_fu_1961_p2(17 downto 17);
    tmp_3_fu_1438_p4 <= sub_ln215_3_fu_1039_p2(20 downto 11);
    tmp_40_fu_2037_p3 <= add_ln51_1_fu_2031_p2(17 downto 17);
    tmp_4_fu_1469_p4 <= sub_ln215_4_fu_1082_p2(20 downto 11);
    tmp_5_fu_1500_p4 <= sub_ln215_5_fu_1125_p2(20 downto 11);
    tmp_6_fu_1531_p4 <= sub_ln215_6_fu_1168_p2(20 downto 11);
    tmp_7_fu_1562_p4 <= sub_ln215_7_fu_1211_p2(20 downto 11);
    tmp_8_fu_1593_p4 <= sub_ln215_8_fu_1254_p2(20 downto 11);
    tmp_fu_1345_p4 <= sub_ln215_fu_910_p2(20 downto 11);
    tmp_s_fu_1619_p4 <= sub_ln215_9_fu_1297_p2(20 downto 11);
    trunc_ln1_fu_2179_p4 <= mul_ln244_fu_273_p2(23 downto 16);
    trunc_ln244_1_fu_2193_p4 <= mul_ln244_1_fu_280_p2(23 downto 16);
    trunc_ln244_2_fu_2207_p4 <= mul_ln244_2_fu_274_p2(23 downto 16);
    trunc_ln244_3_fu_2221_p4 <= mul_ln244_3_fu_277_p2(23 downto 16);
    trunc_ln244_4_fu_2235_p4 <= mul_ln244_4_fu_275_p2(23 downto 16);
    trunc_ln244_5_fu_2249_p4 <= mul_ln244_5_fu_279_p2(23 downto 16);
    trunc_ln244_6_fu_2263_p4 <= mul_ln244_6_fu_276_p2(23 downto 16);
    trunc_ln244_7_fu_2277_p4 <= mul_ln244_7_fu_278_p2(23 downto 16);
    trunc_ln244_8_fu_2291_p4 <= mul_ln244_8_fu_281_p2(23 downto 16);
    trunc_ln244_9_fu_2305_p4 <= mul_ln244_9_fu_282_p2(23 downto 16);
    x_max_fu_897_p3 <= 
        select_ln66_6_reg_2418 when (xor_ln66_8_fu_892_p2(0) = '1') else 
        select_ln66_7_reg_2423;
    xor_ln215_10_fu_1147_p2 <= (tmp_20_fu_1131_p3 xor ap_const_lv1_1);
    xor_ln215_11_fu_1159_p2 <= (tmp_21_fu_1139_p3 xor tmp_20_fu_1131_p3);
    xor_ln215_12_fu_1190_p2 <= (tmp_22_fu_1174_p3 xor ap_const_lv1_1);
    xor_ln215_13_fu_1202_p2 <= (tmp_23_fu_1182_p3 xor tmp_22_fu_1174_p3);
    xor_ln215_14_fu_1233_p2 <= (tmp_24_fu_1217_p3 xor ap_const_lv1_1);
    xor_ln215_15_fu_1245_p2 <= (tmp_25_fu_1225_p3 xor tmp_24_fu_1217_p3);
    xor_ln215_16_fu_1276_p2 <= (tmp_26_fu_1260_p3 xor ap_const_lv1_1);
    xor_ln215_17_fu_1288_p2 <= (tmp_27_fu_1268_p3 xor tmp_26_fu_1260_p3);
    xor_ln215_18_fu_1319_p2 <= (tmp_28_fu_1303_p3 xor ap_const_lv1_1);
    xor_ln215_19_fu_1331_p2 <= (tmp_29_fu_1311_p3 xor tmp_28_fu_1303_p3);
    xor_ln215_1_fu_944_p2 <= (tmp_11_fu_924_p3 xor tmp_10_fu_916_p3);
    xor_ln215_2_fu_975_p2 <= (tmp_12_fu_959_p3 xor ap_const_lv1_1);
    xor_ln215_3_fu_987_p2 <= (tmp_13_fu_967_p3 xor tmp_12_fu_959_p3);
    xor_ln215_4_fu_1018_p2 <= (tmp_14_fu_1002_p3 xor ap_const_lv1_1);
    xor_ln215_5_fu_1030_p2 <= (tmp_15_fu_1010_p3 xor tmp_14_fu_1002_p3);
    xor_ln215_6_fu_1061_p2 <= (tmp_16_fu_1045_p3 xor ap_const_lv1_1);
    xor_ln215_7_fu_1073_p2 <= (tmp_17_fu_1053_p3 xor tmp_16_fu_1045_p3);
    xor_ln215_8_fu_1104_p2 <= (tmp_18_fu_1088_p3 xor ap_const_lv1_1);
    xor_ln215_9_fu_1116_p2 <= (tmp_19_fu_1096_p3 xor tmp_18_fu_1088_p3);
    xor_ln215_fu_932_p2 <= (tmp_10_fu_916_p3 xor ap_const_lv1_1);
    xor_ln51_10_fu_1895_p2 <= (tmp_36_reg_2559 xor ap_const_lv1_1);
    xor_ln51_11_fu_1905_p2 <= (tmp_37_reg_2566 xor ap_const_lv1_1);
    xor_ln51_12_fu_1915_p2 <= (tmp_37_reg_2566 xor tmp_36_reg_2559);
    xor_ln51_13_fu_1919_p2 <= (xor_ln51_12_fu_1915_p2 xor ap_const_lv1_1);
    xor_ln51_1_fu_2001_p2 <= (tmp_39_fu_1981_p3 xor tmp_38_fu_1973_p3);
    xor_ln51_2_fu_1837_p2 <= (tmp_32_reg_2539 xor ap_const_lv1_1);
    xor_ln51_3_fu_2099_p2 <= (tmp_41_reg_2583 xor ap_const_lv1_1);
    xor_ln51_4_fu_2109_p2 <= (tmp_42_reg_2590 xor ap_const_lv1_1);
    xor_ln51_5_fu_2119_p2 <= (tmp_42_reg_2590 xor tmp_41_reg_2583);
    xor_ln51_6_fu_2123_p2 <= (xor_ln51_5_fu_2119_p2 xor ap_const_lv1_1);
    xor_ln51_7_fu_1847_p2 <= (tmp_33_reg_2546 xor ap_const_lv1_1);
    xor_ln51_8_fu_1857_p2 <= (tmp_33_reg_2546 xor tmp_32_reg_2539);
    xor_ln51_9_fu_1861_p2 <= (xor_ln51_8_fu_1857_p2 xor ap_const_lv1_1);
    xor_ln51_fu_1989_p2 <= (tmp_38_fu_1973_p3 xor ap_const_lv1_1);
    xor_ln66_1_fu_764_p2 <= (icmp_ln66_1_fu_758_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_822_p2 <= (icmp_ln66_2_fu_818_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_784_p2 <= (icmp_ln66_3_fu_778_p2 xor ap_const_lv1_1);
    xor_ln66_4_fu_804_p2 <= (icmp_ln66_4_fu_798_p2 xor ap_const_lv1_1);
    xor_ln66_5_fu_838_p2 <= (icmp_ln66_5_fu_834_p2 xor ap_const_lv1_1);
    xor_ln66_6_fu_856_p2 <= (icmp_ln66_6_fu_850_p2 xor ap_const_lv1_1);
    xor_ln66_7_fu_874_p2 <= (icmp_ln66_7_fu_870_p2 xor ap_const_lv1_1);
    xor_ln66_8_fu_892_p2 <= (icmp_ln66_8_reg_2428 xor ap_const_lv1_1);
    xor_ln66_fu_744_p2 <= (icmp_ln66_fu_738_p2 xor ap_const_lv1_1);
    zext_ln225_1_fu_1394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_3_fu_1386_p3),64));
    zext_ln225_2_fu_1425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_5_fu_1417_p3),64));
    zext_ln225_3_fu_1456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_7_fu_1448_p3),64));
    zext_ln225_4_fu_1487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_9_fu_1479_p3),64));
    zext_ln225_5_fu_1518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_11_fu_1510_p3),64));
    zext_ln225_6_fu_1549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_13_fu_1541_p3),64));
    zext_ln225_7_fu_1580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_15_fu_1572_p3),64));
    zext_ln225_8_fu_1637_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_17_reg_2473),64));
    zext_ln225_9_fu_1641_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_19_reg_2478),64));
    zext_ln225_fu_1363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln215_1_fu_1355_p3),64));
    zext_ln235_fu_2157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_15_fu_2149_p3),64));
    zext_ln51_1_fu_2027_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),18));
    zext_ln51_2_fu_1645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q7),18));
    zext_ln51_3_fu_1649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q6),18));
    zext_ln51_4_fu_1675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q5),18));
    zext_ln51_5_fu_1679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q4),18));
    zext_ln51_6_fu_1741_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q3),18));
    zext_ln51_7_fu_1745_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q2),18));
    zext_ln51_8_fu_1771_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q1),18));
    zext_ln51_9_fu_1775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),18));
    zext_ln51_fu_2023_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q1),18));
end behav;
