-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer11_out_dout : IN STD_LOGIC_VECTOR (399 downto 0);
    layer11_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer11_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer11_out_empty_n : IN STD_LOGIC;
    layer11_out_read : OUT STD_LOGIC;
    layer13_out_din : OUT STD_LOGIC_VECTOR (543 downto 0);
    layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer13_out_full_n : IN STD_LOGIC;
    layer13_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_4A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001010";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_E1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100001";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_145 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000101";
    constant ap_const_lv32_15D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv26_800 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_const_lv26_5000 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000101000000000000";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv26_3800 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000011100000000000";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv26_3FFC800 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111100100000000000";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010010";
    constant ap_const_lv32_113 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010011";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000100";
    constant ap_const_lv32_15E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011110";
    constant ap_const_lv32_176 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110110";
    constant ap_const_lv32_177 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110111";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv28_4800 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000100100000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv29_3000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000011000000000000";
    constant ap_const_lv29_8000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000001000000000000000";
    constant ap_const_lv29_1FFFD000 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111101000000000000";
    constant ap_const_lv29_1FFFE800 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111110100000000000";
    constant ap_const_lv29_1FFFB800 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111011100000000000";
    constant ap_const_lv28_5000 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000101000000000000";
    constant ap_const_lv29_9000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000001001000000000000";
    constant ap_const_lv28_FFFC800 : STD_LOGIC_VECTOR (27 downto 0) := "1111111111111100100000000000";
    constant ap_const_lv29_5000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000101000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer11_out_blk_n : STD_LOGIC;
    signal layer13_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal a_fu_141_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_reg_865 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal a_1_fu_151_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_1_reg_870 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_2_fu_161_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_2_reg_875 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_3_fu_171_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_3_reg_880 : STD_LOGIC_VECTOR (24 downto 0);
    signal a_4_reg_885 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln73_fu_191_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln73_reg_891 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_2_reg_896 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln42_16_fu_209_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_16_reg_902 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_17_fu_219_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_17_reg_907 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_6_reg_912 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln42_18_fu_239_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_18_reg_918 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_9_reg_923 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_s_reg_929 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_reg_935 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln42_19_fu_279_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_19_reg_941 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_3_reg_946 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_4_reg_951 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_5_reg_957 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_7_reg_963 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_8_reg_968 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_2_fu_205_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_4_fu_215_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_8_fu_235_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_16_fu_275_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln_fu_335_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_11_fu_342_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_fu_346_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln_fu_356_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_1_fu_367_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_fu_363_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_1_fu_374_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_fu_378_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_1_fu_384_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln73_1_fu_394_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_14_fu_405_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln73_3_fu_401_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln73_2_fu_414_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_15_fu_425_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln73_5_fu_421_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_3_fu_428_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_2_fu_438_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_3_fu_449_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_6_fu_445_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_7_fu_456_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_1_fu_460_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_4_fu_466_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln73_3_fu_476_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_16_fu_487_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln73_9_fu_483_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_5_fu_490_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_4_fu_500_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_5_fu_511_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_10_fu_507_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_11_fu_518_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_2_fu_522_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_6_fu_528_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal and_ln73_6_fu_538_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_7_fu_549_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_12_fu_545_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_13_fu_556_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_3_fu_560_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_7_fu_566_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal and_ln73_8_fu_576_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_9_fu_587_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_14_fu_583_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_15_fu_594_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_4_fu_598_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_8_fu_604_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln73_4_fu_614_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_17_fu_625_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln73_17_fu_621_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_9_fu_628_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_s_fu_638_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_12_fu_645_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_10_fu_655_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_11_fu_666_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_18_fu_662_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_19_fu_673_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_5_fu_677_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_11_fu_683_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal and_ln73_12_fu_693_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_13_fu_704_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_20_fu_700_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_21_fu_711_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_6_fu_715_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln73_5_fu_730_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln73_23_fu_737_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_22_fu_727_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_7_fu_741_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_13_fu_747_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal and_ln73_14_fu_757_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln42_13_fu_764_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_15_fu_774_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln73_16_fu_785_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_24_fu_781_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln73_25_fu_792_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln73_8_fu_796_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_2_fu_408_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_10_fu_649_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_12_fu_721_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln42_14_fu_768_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_15_fu_802_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_3_fu_820_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_10_fu_753_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln46_2_fu_816_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_9_fu_689_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln46_1_fu_812_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_8_fu_634_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_7_fu_610_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_6_fu_572_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_5_fu_534_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_4_fu_496_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_3_fu_472_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_2_fu_434_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln46_fu_808_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_1_fu_390_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln42_fu_352_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_fu_824_p17 : STD_LOGIC_VECTOR (538 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer13_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                a_1_reg_870 <= layer11_out_dout(99 downto 75);
                a_2_reg_875 <= layer11_out_dout(149 downto 125);
                a_3_reg_880 <= layer11_out_dout(249 downto 225);
                a_4_reg_885 <= layer11_out_dout(349 downto 325);
                a_reg_865 <= layer11_out_dout(74 downto 50);
                add_ln42_16_reg_902 <= add_ln42_16_fu_209_p2;
                add_ln42_17_reg_907 <= add_ln42_17_fu_219_p2;
                add_ln42_18_reg_918 <= add_ln42_18_fu_239_p2;
                add_ln42_19_reg_941 <= add_ln42_19_fu_279_p2;
                tmp_1_reg_935 <= layer11_out_dout(224 downto 200);
                tmp_2_reg_896 <= layer11_out_dout(49 downto 25);
                tmp_3_reg_946 <= layer11_out_dout(274 downto 250);
                tmp_4_reg_951 <= layer11_out_dout(299 downto 275);
                tmp_5_reg_957 <= layer11_out_dout(324 downto 300);
                tmp_6_reg_912 <= layer11_out_dout(124 downto 100);
                tmp_7_reg_963 <= layer11_out_dout(374 downto 350);
                tmp_8_reg_968 <= layer11_out_dout(399 downto 375);
                tmp_9_reg_923 <= layer11_out_dout(174 downto 150);
                tmp_s_reg_929 <= layer11_out_dout(199 downto 175);
                trunc_ln73_reg_891 <= trunc_ln73_fu_191_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer13_out_full_n, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer13_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    a_1_fu_151_p4 <= layer11_out_dout(99 downto 75);
    a_2_fu_161_p4 <= layer11_out_dout(149 downto 125);
    a_3_fu_171_p4 <= layer11_out_dout(249 downto 225);
    a_fu_141_p4 <= layer11_out_dout(74 downto 50);
    add_ln42_10_fu_649_p2 <= std_logic_vector(signed(sext_ln42_12_fu_645_p1) + signed(ap_const_lv28_5000));
    add_ln42_11_fu_683_p2 <= std_logic_vector(unsigned(sub_ln73_5_fu_677_p2) + unsigned(ap_const_lv29_3000));
    add_ln42_12_fu_721_p2 <= std_logic_vector(unsigned(sub_ln73_6_fu_715_p2) + unsigned(ap_const_lv29_1FFFE800));
    add_ln42_13_fu_747_p2 <= std_logic_vector(unsigned(sub_ln73_7_fu_741_p2) + unsigned(ap_const_lv29_9000));
    add_ln42_14_fu_768_p2 <= std_logic_vector(signed(sext_ln42_13_fu_764_p1) + signed(ap_const_lv28_FFFC800));
    add_ln42_15_fu_802_p2 <= std_logic_vector(unsigned(sub_ln73_8_fu_796_p2) + unsigned(ap_const_lv29_5000));
    add_ln42_16_fu_209_p2 <= std_logic_vector(signed(sext_ln73_2_fu_205_p1) + signed(ap_const_lv26_800));
    add_ln42_17_fu_219_p2 <= std_logic_vector(signed(sext_ln73_4_fu_215_p1) + signed(ap_const_lv26_5000));
    add_ln42_18_fu_239_p2 <= std_logic_vector(signed(sext_ln73_8_fu_235_p1) + signed(ap_const_lv26_3800));
    add_ln42_19_fu_279_p2 <= std_logic_vector(signed(sext_ln73_16_fu_275_p1) + signed(ap_const_lv26_3FFC800));
    add_ln42_1_fu_384_p2 <= std_logic_vector(unsigned(sub_ln73_fu_378_p2) + unsigned(ap_const_lv29_3000));
    add_ln42_2_fu_408_p2 <= std_logic_vector(signed(sext_ln42_14_fu_405_p1) + signed(sext_ln73_3_fu_401_p1));
    add_ln42_3_fu_428_p2 <= std_logic_vector(signed(sext_ln42_15_fu_425_p1) + signed(sext_ln73_5_fu_421_p1));
    add_ln42_4_fu_466_p2 <= std_logic_vector(unsigned(sub_ln73_1_fu_460_p2) + unsigned(ap_const_lv29_8000));
    add_ln42_5_fu_490_p2 <= std_logic_vector(signed(sext_ln42_16_fu_487_p1) + signed(sext_ln73_9_fu_483_p1));
    add_ln42_6_fu_528_p2 <= std_logic_vector(unsigned(sub_ln73_2_fu_522_p2) + unsigned(ap_const_lv29_1FFFD000));
    add_ln42_7_fu_566_p2 <= std_logic_vector(unsigned(sub_ln73_3_fu_560_p2) + unsigned(ap_const_lv29_1FFFE800));
    add_ln42_8_fu_604_p2 <= std_logic_vector(unsigned(sub_ln73_4_fu_598_p2) + unsigned(ap_const_lv29_1FFFB800));
    add_ln42_9_fu_628_p2 <= std_logic_vector(signed(sext_ln42_17_fu_625_p1) + signed(sext_ln73_17_fu_621_p1));
    add_ln42_fu_346_p2 <= std_logic_vector(signed(sext_ln42_11_fu_342_p1) + signed(ap_const_lv28_4800));
    and_ln73_10_fu_655_p3 <= (tmp_4_reg_951 & ap_const_lv3_0);
    and_ln73_11_fu_666_p3 <= (tmp_4_reg_951 & ap_const_lv1_0);
    and_ln73_12_fu_693_p3 <= (tmp_5_reg_957 & ap_const_lv3_0);
    and_ln73_13_fu_704_p3 <= (tmp_5_reg_957 & ap_const_lv1_0);
    and_ln73_14_fu_757_p3 <= (tmp_7_reg_963 & ap_const_lv2_0);
    and_ln73_15_fu_774_p3 <= (tmp_8_reg_968 & ap_const_lv3_0);
    and_ln73_16_fu_785_p3 <= (tmp_8_reg_968 & ap_const_lv1_0);
    and_ln73_1_fu_367_p3 <= (tmp_2_reg_896 & ap_const_lv1_0);
    and_ln73_2_fu_438_p3 <= (tmp_6_reg_912 & ap_const_lv3_0);
    and_ln73_3_fu_449_p3 <= (tmp_6_reg_912 & ap_const_lv1_0);
    and_ln73_4_fu_500_p3 <= (tmp_9_reg_923 & ap_const_lv3_0);
    and_ln73_5_fu_511_p3 <= (tmp_9_reg_923 & ap_const_lv1_0);
    and_ln73_6_fu_538_p3 <= (tmp_s_reg_929 & ap_const_lv3_0);
    and_ln73_7_fu_549_p3 <= (tmp_s_reg_929 & ap_const_lv1_0);
    and_ln73_8_fu_576_p3 <= (tmp_1_reg_935 & ap_const_lv3_0);
    and_ln73_9_fu_587_p3 <= (tmp_1_reg_935 & ap_const_lv1_0);
    and_ln73_s_fu_638_p3 <= (tmp_3_reg_946 & ap_const_lv2_0);
    and_ln_fu_356_p3 <= (tmp_2_reg_896 & ap_const_lv3_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer13_out_full_n)
    begin
        if ((layer13_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer11_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer11_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer13_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer13_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    internal_ap_ready_assign_proc : process(layer13_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer13_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer11_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer11_out_blk_n <= layer11_out_empty_n;
        else 
            layer11_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer11_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer11_out_read <= ap_const_logic_1;
        else 
            layer11_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer13_out_blk_n_assign_proc : process(layer13_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer13_out_blk_n <= layer13_out_full_n;
        else 
            layer13_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer13_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_824_p17),544));


    layer13_out_write_assign_proc : process(layer13_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer13_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer13_out_write <= ap_const_logic_1;
        else 
            layer13_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln42_10_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_13_fu_747_p2),34));

        sext_ln42_11_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_335_p3),28));

        sext_ln42_12_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_s_fu_638_p3),28));

        sext_ln42_13_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_14_fu_757_p3),28));

        sext_ln42_14_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_16_reg_902),28));

        sext_ln42_15_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_17_reg_907),28));

        sext_ln42_16_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_18_reg_918),28));

        sext_ln42_17_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_19_reg_941),28));

        sext_ln42_1_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_1_fu_384_p2),34));

        sext_ln42_2_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_3_fu_428_p2),34));

        sext_ln42_3_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_4_fu_466_p2),34));

        sext_ln42_4_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_5_fu_490_p2),34));

        sext_ln42_5_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_6_fu_528_p2),34));

        sext_ln42_6_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_7_fu_566_p2),34));

        sext_ln42_7_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_8_fu_604_p2),34));

        sext_ln42_8_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_9_fu_628_p2),34));

        sext_ln42_9_fu_689_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_11_fu_683_p2),34));

        sext_ln42_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_fu_346_p2),34));

        sext_ln46_1_fu_812_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_10_fu_649_p2),34));

        sext_ln46_2_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_12_fu_721_p2),34));

        sext_ln46_3_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_14_fu_768_p2),34));

        sext_ln46_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_2_fu_408_p2),34));

        sext_ln73_10_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_4_fu_500_p3),29));

        sext_ln73_11_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_5_fu_511_p3),29));

        sext_ln73_12_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_6_fu_538_p3),29));

        sext_ln73_13_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_7_fu_549_p3),29));

        sext_ln73_14_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_8_fu_576_p3),29));

        sext_ln73_15_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_9_fu_587_p3),29));

        sext_ln73_16_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_3_fu_171_p4),26));

        sext_ln73_17_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_4_fu_614_p3),28));

        sext_ln73_18_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_10_fu_655_p3),29));

        sext_ln73_19_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_11_fu_666_p3),29));

        sext_ln73_1_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_1_fu_367_p3),29));

        sext_ln73_20_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_12_fu_693_p3),29));

        sext_ln73_21_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_13_fu_704_p3),29));

        sext_ln73_22_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_4_reg_885),29));

        sext_ln73_23_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_5_fu_730_p3),29));

        sext_ln73_24_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_15_fu_774_p3),29));

        sext_ln73_25_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_16_fu_785_p3),29));

        sext_ln73_2_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_fu_141_p4),26));

        sext_ln73_3_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_1_fu_394_p3),28));

        sext_ln73_4_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_1_fu_151_p4),26));

        sext_ln73_5_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_2_fu_414_p3),28));

        sext_ln73_6_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_2_fu_438_p3),29));

        sext_ln73_7_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_3_fu_449_p3),29));

        sext_ln73_8_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_2_fu_161_p4),26));

        sext_ln73_9_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_3_fu_476_p3),28));

        sext_ln73_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln_fu_356_p3),29));

    shl_ln73_1_fu_394_p3 <= (a_reg_865 & ap_const_lv2_0);
    shl_ln73_2_fu_414_p3 <= (a_1_reg_870 & ap_const_lv2_0);
    shl_ln73_3_fu_476_p3 <= (a_2_reg_875 & ap_const_lv2_0);
    shl_ln73_4_fu_614_p3 <= (a_3_reg_880 & ap_const_lv2_0);
    shl_ln73_5_fu_730_p3 <= (a_4_reg_885 & ap_const_lv3_0);
    shl_ln_fu_335_p3 <= (trunc_ln73_reg_891 & ap_const_lv2_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln73_1_fu_460_p2 <= std_logic_vector(signed(sext_ln73_6_fu_445_p1) - signed(sext_ln73_7_fu_456_p1));
    sub_ln73_2_fu_522_p2 <= std_logic_vector(signed(sext_ln73_10_fu_507_p1) - signed(sext_ln73_11_fu_518_p1));
    sub_ln73_3_fu_560_p2 <= std_logic_vector(signed(sext_ln73_12_fu_545_p1) - signed(sext_ln73_13_fu_556_p1));
    sub_ln73_4_fu_598_p2 <= std_logic_vector(signed(sext_ln73_14_fu_583_p1) - signed(sext_ln73_15_fu_594_p1));
    sub_ln73_5_fu_677_p2 <= std_logic_vector(signed(sext_ln73_18_fu_662_p1) - signed(sext_ln73_19_fu_673_p1));
    sub_ln73_6_fu_715_p2 <= std_logic_vector(signed(sext_ln73_20_fu_700_p1) - signed(sext_ln73_21_fu_711_p1));
    sub_ln73_7_fu_741_p2 <= std_logic_vector(signed(sext_ln73_23_fu_737_p1) - signed(sext_ln73_22_fu_727_p1));
    sub_ln73_8_fu_796_p2 <= std_logic_vector(signed(sext_ln73_24_fu_781_p1) - signed(sext_ln73_25_fu_792_p1));
    sub_ln73_fu_378_p2 <= std_logic_vector(signed(sext_ln73_fu_363_p1) - signed(sext_ln73_1_fu_374_p1));
    tmp_fu_824_p17 <= (((((((((((((((add_ln42_15_fu_802_p2 & sext_ln46_3_fu_820_p1) & sext_ln42_10_fu_753_p1) & sext_ln46_2_fu_816_p1) & sext_ln42_9_fu_689_p1) & sext_ln46_1_fu_812_p1) & sext_ln42_8_fu_634_p1) & sext_ln42_7_fu_610_p1) & sext_ln42_6_fu_572_p1) & sext_ln42_5_fu_534_p1) & sext_ln42_4_fu_496_p1) & sext_ln42_3_fu_472_p1) & sext_ln42_2_fu_434_p1) & sext_ln46_fu_808_p1) & sext_ln42_1_fu_390_p1) & sext_ln42_fu_352_p1);
    trunc_ln73_fu_191_p1 <= layer11_out_dout(25 - 1 downto 0);
end behav;
