// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.646500,HLS_SYN_LAT=2374,HLS_SYN_TPT=2356,HLS_SYN_MEM=58,HLS_SYN_DSP=0,HLS_SYN_FF=36198,HLS_SYN_LUT=145061,HLS_VERSION=2023_2}" *)

module myproject (
        input_layer_TDATA,
        layer21_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_TVALID,
        input_layer_TREADY,
        ap_start,
        layer21_out_TVALID,
        layer21_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] input_layer_TDATA;
output  [79:0] layer21_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_TVALID;
output   input_layer_TREADY;
input   ap_start;
output   layer21_out_TVALID;
input   layer21_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_input_layer_TREADY;
wire   [131:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_start;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_done;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_continue;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_idle;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_ready;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer2_out_read;
wire   [47:0] hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_din;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_start_out;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_ready;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer4_out_read;
wire   [47:0] pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_din;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_write;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer5_out_read;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_start_write;
wire   [399:0] conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_din;
wire    conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_start;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_done;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_continue;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_idle;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_ready;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer6_out_read;
wire   [127:0] hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_din;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_start_out;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_ready;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer8_out_read;
wire   [127:0] pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_din;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_write;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_start_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_start;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_done;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_continue;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_idle;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_ready;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_start_out;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_start_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer9_out_read;
wire   [399:0] dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_din;
wire    dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_start;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_done;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_continue;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_idle;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_ready;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_start_out;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_start_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer11_out_read;
wire   [543:0] normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_din;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_start;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_done;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_continue;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_idle;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_ready;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_start_out;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_start_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer13_out_read;
wire   [127:0] hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_din;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_start;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_done;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_continue;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_idle;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_ready;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_start_out;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_start_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer14_out_read;
wire   [335:0] dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_din;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_start;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_done;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_continue;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_idle;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_ready;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_start_out;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_start_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer15_out_read;
wire   [479:0] normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_din;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_start;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_done;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_continue;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_idle;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_ready;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_start_out;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_start_write;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer17_out_read;
wire   [127:0] hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_din;
wire    hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_start;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_done;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_continue;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_idle;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_ready;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_start_out;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_start_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer18_out_read;
wire   [209:0] dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_din;
wire    dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_write;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_start;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_done;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_continue;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_idle;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_ready;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer19_out_read;
wire   [79:0] softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TDATA;
wire    softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TVALID;
wire    layer2_out_full_n;
wire   [131:0] layer2_out_dout;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer4_out_full_n;
wire   [47:0] layer4_out_dout;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [47:0] layer5_out_dout;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [399:0] layer6_out_dout;
wire   [6:0] layer6_out_num_data_valid;
wire   [6:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer8_out_full_n;
wire   [127:0] layer8_out_dout;
wire   [6:0] layer8_out_num_data_valid;
wire   [6:0] layer8_out_fifo_cap;
wire    layer8_out_empty_n;
wire    layer9_out_full_n;
wire   [127:0] layer9_out_dout;
wire   [4:0] layer9_out_num_data_valid;
wire   [4:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire    layer11_out_full_n;
wire   [399:0] layer11_out_dout;
wire   [1:0] layer11_out_num_data_valid;
wire   [1:0] layer11_out_fifo_cap;
wire    layer11_out_empty_n;
wire    layer13_out_full_n;
wire   [543:0] layer13_out_dout;
wire   [1:0] layer13_out_num_data_valid;
wire   [1:0] layer13_out_fifo_cap;
wire    layer13_out_empty_n;
wire    layer14_out_full_n;
wire   [127:0] layer14_out_dout;
wire   [1:0] layer14_out_num_data_valid;
wire   [1:0] layer14_out_fifo_cap;
wire    layer14_out_empty_n;
wire    layer15_out_full_n;
wire   [335:0] layer15_out_dout;
wire   [1:0] layer15_out_num_data_valid;
wire   [1:0] layer15_out_fifo_cap;
wire    layer15_out_empty_n;
wire    layer17_out_full_n;
wire   [479:0] layer17_out_dout;
wire   [1:0] layer17_out_num_data_valid;
wire   [1:0] layer17_out_fifo_cap;
wire    layer17_out_empty_n;
wire    layer18_out_full_n;
wire   [127:0] layer18_out_dout;
wire   [1:0] layer18_out_num_data_valid;
wire   [1:0] layer18_out_fifo_cap;
wire    layer18_out_empty_n;
wire    layer19_out_full_n;
wire   [209:0] layer19_out_dout;
wire   [1:0] layer19_out_num_data_valid;
wire   [1:0] layer19_out_fifo_cap;
wire    layer19_out_empty_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_din;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_full_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_dout;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_empty_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_din;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_full_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_dout;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_din;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_dout;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_din;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_dout;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_empty_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_din;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_full_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_dout;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_din;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_dout;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_din;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_dout;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_empty_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_din;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_full_n;
wire   [0:0] start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_dout;
wire    start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_din;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_dout;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_empty_n;
wire   [0:0] start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_din;
wire    start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_full_n;
wire   [0:0] start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_dout;
wire    start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_empty_n;

myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_start),
    .start_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_ready),
    .input_layer_TVALID(input_layer_TVALID),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_start_write),
    .input_layer_TDATA(input_layer_TDATA),
    .input_layer_TREADY(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_input_layer_TREADY),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_write)
);

myproject_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_s hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_full_n),
    .ap_done(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_done),
    .ap_continue(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_continue),
    .ap_idle(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_idle),
    .ap_ready(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer2_out_read),
    .layer4_out_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_write),
    .start_out(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_start_out),
    .start_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_start_write)
);

myproject_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_s pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer4_out_read),
    .layer5_out_din(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_write),
    .start_out(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_start_write)
);

myproject_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_s conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_start),
    .start_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_ready),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer5_out_read),
    .start_out(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_start_write),
    .layer6_out_din(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_write)
);

myproject_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_s hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_full_n),
    .ap_done(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_done),
    .ap_continue(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_continue),
    .ap_idle(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_idle),
    .ap_ready(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer6_out_read),
    .layer8_out_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_din),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_write),
    .start_out(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_start_out),
    .start_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_start_write)
);

myproject_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_s pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_ready),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer8_out_read),
    .layer9_out_din(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_write),
    .start_out(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_start_write)
);

myproject_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_s dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_full_n),
    .ap_done(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_ready),
    .start_out(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_start_out),
    .start_write(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_start_write),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer9_out_read),
    .layer11_out_din(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_din),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_write)
);

myproject_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_s normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_start),
    .start_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_full_n),
    .ap_done(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_start_out),
    .start_write(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_start_write),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer11_out_read),
    .layer13_out_din(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_din),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_write)
);

myproject_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_s hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_full_n),
    .ap_done(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_done),
    .ap_continue(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_continue),
    .ap_idle(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_idle),
    .ap_ready(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_ready),
    .start_out(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_start_out),
    .start_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_start_write),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer13_out_read),
    .layer14_out_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_din),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer14_out_full_n(layer14_out_full_n),
    .layer14_out_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_write)
);

myproject_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_s dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_full_n),
    .ap_done(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_ready),
    .start_out(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_start_out),
    .start_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_start_write),
    .layer14_out_dout(layer14_out_dout),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer14_out_empty_n(layer14_out_empty_n),
    .layer14_out_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer14_out_read),
    .layer15_out_din(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_din),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_full_n(layer15_out_full_n),
    .layer15_out_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_write)
);

myproject_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_s normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_start),
    .start_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_full_n),
    .ap_done(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_start_out),
    .start_write(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_start_write),
    .layer15_out_dout(layer15_out_dout),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_empty_n(layer15_out_empty_n),
    .layer15_out_read(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer15_out_read),
    .layer17_out_din(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_din),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_write)
);

myproject_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_s hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_full_n),
    .ap_done(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_done),
    .ap_continue(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_continue),
    .ap_idle(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_idle),
    .ap_ready(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_ready),
    .start_out(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_start_out),
    .start_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_start_write),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer17_out_read),
    .layer18_out_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_din),
    .layer18_out_num_data_valid(layer18_out_num_data_valid),
    .layer18_out_fifo_cap(layer18_out_fifo_cap),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_write)
);

myproject_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_s dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_start),
    .start_full_n(start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_full_n),
    .ap_done(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_ready),
    .start_out(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_start_out),
    .start_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_start_write),
    .layer18_out_dout(layer18_out_dout),
    .layer18_out_num_data_valid(layer18_out_num_data_valid),
    .layer18_out_fifo_cap(layer18_out_fifo_cap),
    .layer18_out_empty_n(layer18_out_empty_n),
    .layer18_out_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer18_out_read),
    .layer19_out_din(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_din),
    .layer19_out_num_data_valid(layer19_out_num_data_valid),
    .layer19_out_fifo_cap(layer19_out_fifo_cap),
    .layer19_out_full_n(layer19_out_full_n),
    .layer19_out_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_write)
);

myproject_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_s softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_start),
    .ap_done(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_done),
    .ap_continue(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_continue),
    .ap_idle(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_idle),
    .ap_ready(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_ready),
    .layer19_out_dout(layer19_out_dout),
    .layer19_out_num_data_valid(layer19_out_num_data_valid),
    .layer19_out_fifo_cap(layer19_out_fifo_cap),
    .layer19_out_empty_n(layer19_out_empty_n),
    .layer19_out_read(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer19_out_read),
    .layer21_out_TDATA(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TDATA),
    .layer21_out_TVALID(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TVALID),
    .layer21_out_TREADY(layer21_out_TREADY)
);

myproject_fifo_w132_d576_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer2_out_read)
);

myproject_fifo_w48_d576_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer4_out_read)
);

myproject_fifo_w48_d144_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer5_out_read)
);

myproject_fifo_w400_d64_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer6_out_read)
);

myproject_fifo_w128_d64_A layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer8_out_read)
);

myproject_fifo_w128_d16_A layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer9_out_read)
);

myproject_fifo_w400_d1_S layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap),
    .if_empty_n(layer11_out_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer11_out_read)
);

myproject_fifo_w544_d1_S layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap),
    .if_empty_n(layer13_out_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer13_out_read)
);

myproject_fifo_w128_d1_S layer14_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_din),
    .if_full_n(layer14_out_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_layer14_out_write),
    .if_dout(layer14_out_dout),
    .if_num_data_valid(layer14_out_num_data_valid),
    .if_fifo_cap(layer14_out_fifo_cap),
    .if_empty_n(layer14_out_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer14_out_read)
);

myproject_fifo_w336_d1_S layer15_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_din),
    .if_full_n(layer15_out_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_layer15_out_write),
    .if_dout(layer15_out_dout),
    .if_num_data_valid(layer15_out_num_data_valid),
    .if_fifo_cap(layer15_out_fifo_cap),
    .if_empty_n(layer15_out_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer15_out_read)
);

myproject_fifo_w480_d1_S layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap),
    .if_empty_n(layer17_out_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer17_out_read)
);

myproject_fifo_w128_d1_S layer18_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_din),
    .if_full_n(layer18_out_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_layer18_out_write),
    .if_dout(layer18_out_dout),
    .if_num_data_valid(layer18_out_num_data_valid),
    .if_fifo_cap(layer18_out_fifo_cap),
    .if_empty_n(layer18_out_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer18_out_read)
);

myproject_fifo_w210_d1_S layer19_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_din),
    .if_full_n(layer19_out_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_layer19_out_write),
    .if_dout(layer19_out_dout),
    .if_num_data_valid(layer19_out_num_data_valid),
    .if_fifo_cap(layer19_out_fifo_cap),
    .if_empty_n(layer19_out_empty_n),
    .if_read(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer19_out_read)
);

myproject_start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0 start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_din),
    .if_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_start_write),
    .if_dout(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_dout),
    .if_empty_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0 start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config61iI start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config61iI_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_ready)
);

myproject_start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0 start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_din),
    .if_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_start_write),
    .if_dout(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_dout),
    .if_empty_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config2iS start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config2iS_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0 start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13i2 start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13i2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_ready)
);

myproject_start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0 start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_din),
    .if_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_start_write),
    .if_dout(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_dout),
    .if_empty_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0 start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config14jc start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config14jc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_ready)
);

myproject_start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0 start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_din),
    .if_full_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_start_write),
    .if_dout(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_dout),
    .if_empty_n(start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_empty_n),
    .if_read(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0 start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_full_n),
    .if_write(hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_ready)
);

myproject_start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0 start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_din),
    .if_full_n(start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_start_write),
    .if_dout(start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_dout),
    .if_empty_n(start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_empty_n),
    .if_read(softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_ready)
);

assign ap_done = softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_done;

assign ap_idle = (softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_idle & pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_idle & pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_idle & normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_idle & normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_idle & hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_idle & hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_idle & hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_idle & hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_idle & dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_idle & dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_idle & dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_idle & conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_idle);

assign ap_ready = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_ap_start = ap_start;

assign conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_empty_n;

assign dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_ap_start = start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_empty_n;

assign dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_ap_start = start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_empty_n;

assign dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_ap_start = start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_empty_n;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_continue = 1'b1;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_ap_start = start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_empty_n;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_continue = 1'b1;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_ap_start = start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_empty_n;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_continue = 1'b1;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_ap_start = start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_empty_n;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_continue = 1'b1;

assign hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_ap_start = start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_empty_n;

assign input_layer_TREADY = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_14_5_3_0_6u_config2_U0_input_layer_TREADY;

assign layer21_out_TDATA = softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TDATA;

assign layer21_out_TVALID = softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_layer21_out_TVALID;

assign normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_ap_start = start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_empty_n;

assign normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_ap_start = start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_empty_n;

assign pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_empty_n;

assign pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_empty_n;

assign softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_continue = 1'b1;

assign softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_ap_start = start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_fixed_6u_array_ap_fixed_25_14_5_3_0_16u_config6_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_10u_config19_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_16u_array_ap_fixed_21_10_5_3_0_16u_config15_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_14_5_3_0_16u_config11_U0_din = 1'b1;

assign start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config14_U0_din = 1'b1;

assign start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config18_U0_din = 1'b1;

assign start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_16u_hard_tanh_config8_U0_din = 1'b1;

assign start_for_hard_tanh_array_array_ap_fixed_8_1_4_0_0_6u_hard_tanh_config4_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_16u_array_ap_fixed_30_15_5_3_0_16u_config17_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_1_4_0_0_16u_config9_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_8_1_4_0_0_6u_config5_U0_din = 1'b1;

assign start_for_softmax_array_array_ap_fixed_8_4_5_3_0_10u_softmax_config21_U0_din = 1'b1;

endmodule //myproject
