// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_22_14_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_4,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_3,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_2,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_1,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_4;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_3;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_2;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_1;
input  [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;
output  [21:0] ap_return_0;
output  [21:0] ap_return_1;
output  [21:0] ap_return_2;
output  [21:0] ap_return_3;
output  [21:0] ap_return_4;
output  [21:0] ap_return_5;
input   ap_ce;

reg[21:0] ap_return_0;
reg[21:0] ap_return_1;
reg[21:0] ap_return_2;
reg[21:0] ap_return_3;
reg[21:0] ap_return_4;
reg[21:0] ap_return_5;

wire   [12:0] mul_ln73_46_fu_182_p2;
reg   [12:0] mul_ln73_46_reg_3790;
wire    ap_block_pp0_stage0_11001;
wire   [11:0] sub_ln73_1072_fu_5807_p2;
reg   [11:0] sub_ln73_1072_reg_7887;
wire   [11:0] sub_ln73_1077_fu_5889_p2;
reg   [11:0] sub_ln73_1077_reg_7892;
reg  signed [7:0] a_25_reg_7897;
wire  signed [9:0] shl_ln73_698_fu_5915_p3;
reg  signed [9:0] shl_ln73_698_reg_7905;
wire  signed [11:0] add_ln73_91_fu_5963_p2;
reg  signed [11:0] add_ln73_91_reg_7910;
wire   [11:0] add_ln73_92_fu_5981_p2;
reg   [11:0] add_ln73_92_reg_7915;
reg  signed [7:0] a_27_reg_7920;
wire  signed [9:0] shl_ln73_703_fu_6001_p3;
reg  signed [9:0] shl_ln73_703_reg_7925;
reg  signed [7:0] a_28_reg_7930;
wire  signed [11:0] sext_ln73_1444_fu_6042_p1;
reg  signed [11:0] sext_ln73_1444_reg_7936;
reg  signed [7:0] a_31_reg_7941;
reg  signed [7:0] a_32_reg_7947;
reg  signed [7:0] a_33_reg_7955;
wire   [13:0] add_ln58_2570_fu_6335_p2;
reg   [13:0] add_ln58_2570_reg_7963;
wire   [12:0] sub_ln58_654_fu_6349_p2;
reg   [12:0] sub_ln58_654_reg_7968;
wire   [13:0] add_ln58_2582_fu_6491_p2;
reg   [13:0] add_ln58_2582_reg_7973;
wire   [13:0] sub_ln58_655_fu_6509_p2;
reg   [13:0] sub_ln58_655_reg_7978;
wire   [13:0] add_ln58_2586_fu_6565_p2;
reg   [13:0] add_ln58_2586_reg_7983;
wire   [13:0] add_ln58_2587_fu_6591_p2;
reg   [13:0] add_ln58_2587_reg_7988;
wire   [13:0] add_ln58_2591_fu_6617_p2;
reg   [13:0] add_ln58_2591_reg_7993;
wire   [11:0] add_ln58_2594_fu_6623_p2;
reg   [11:0] add_ln58_2594_reg_7998;
wire   [14:0] add_ln58_2601_fu_6687_p2;
reg   [14:0] add_ln58_2601_reg_8003;
wire   [12:0] add_ln58_2602_fu_6701_p2;
reg   [12:0] add_ln58_2602_reg_8008;
wire   [12:0] add_ln58_2608_fu_6707_p2;
reg   [12:0] add_ln58_2608_reg_8013;
wire   [13:0] add_ln58_2617_fu_6733_p2;
reg   [13:0] add_ln58_2617_reg_8018;
wire   [13:0] add_ln58_2623_fu_6795_p2;
reg   [13:0] add_ln58_2623_reg_8023;
wire  signed [4:0] mul_ln73_47_fu_115_p1;
wire    ap_block_pp0_stage0;
wire  signed [4:0] mul_ln73_39_fu_117_p1;
wire  signed [4:0] mul_ln73_48_fu_120_p1;
wire  signed [5:0] mul_ln73_40_fu_127_p1;
wire  signed [4:0] mul_ln73_44_fu_141_p1;
wire  signed [4:0] mul_ln73_42_fu_163_p1;
wire   [5:0] mul_ln73_fu_166_p1;
wire  signed [4:0] mul_ln73_41_fu_168_p1;
wire  signed [7:0] mul_ln73_46_fu_182_p0;
wire  signed [12:0] sext_ln73_1462_fu_6095_p1;
wire  signed [4:0] mul_ln73_46_fu_182_p1;
wire   [4:0] mul_ln73_45_fu_195_p1;
wire   [4:0] mul_ln73_43_fu_196_p1;
wire  signed [7:0] sext_ln73_fu_5047_p0;
wire  signed [7:0] shl_ln_fu_5051_p1;
wire   [10:0] shl_ln_fu_5051_p3;
wire  signed [11:0] sext_ln73_1369_fu_5059_p1;
wire  signed [7:0] shl_ln73_s_fu_5069_p1;
wire   [8:0] shl_ln73_s_fu_5069_p3;
wire   [11:0] sub_ln73_fu_5063_p2;
wire  signed [11:0] sext_ln73_1370_fu_5077_p1;
wire  signed [7:0] shl_ln73_660_fu_5087_p1;
wire   [9:0] shl_ln73_660_fu_5087_p3;
wire  signed [10:0] sext_ln73_1371_fu_5095_p1;
wire  signed [10:0] sext_ln73_fu_5047_p1;
wire  signed [7:0] sext_ln73_1372_fu_5109_p0;
wire  signed [7:0] shl_ln73_661_fu_5113_p1;
wire  signed [8:0] shl_ln73_661_fu_5113_p3;
wire  signed [7:0] shl_ln73_662_fu_5129_p1;
wire   [9:0] shl_ln73_662_fu_5129_p3;
wire  signed [10:0] sext_ln73_1375_fu_5137_p1;
wire  signed [10:0] sext_ln73_1372_fu_5109_p1;
wire  signed [7:0] shl_ln73_663_fu_5147_p1;
wire   [10:0] shl_ln73_663_fu_5147_p3;
wire  signed [11:0] sext_ln73_1376_fu_5155_p1;
wire  signed [11:0] sext_ln73_1374_fu_5125_p1;
wire  signed [7:0] sext_ln73_1377_fu_5175_p0;
wire  signed [7:0] shl_ln73_664_fu_5179_p1;
wire   [9:0] shl_ln73_664_fu_5179_p3;
wire  signed [10:0] sext_ln73_1378_fu_5187_p1;
wire  signed [10:0] sext_ln73_1377_fu_5175_p1;
wire  signed [7:0] shl_ln73_665_fu_5197_p1;
wire   [10:0] shl_ln73_665_fu_5197_p3;
wire  signed [7:0] shl_ln73_666_fu_5209_p1;
wire   [8:0] shl_ln73_666_fu_5209_p3;
wire  signed [11:0] sext_ln73_1379_fu_5205_p1;
wire  signed [11:0] sext_ln73_1380_fu_5217_p1;
wire   [11:0] sub_ln73_1053_fu_5221_p2;
wire   [10:0] add_ln73_83_fu_5231_p2;
wire  signed [7:0] sext_ln73_1382_fu_5245_p0;
wire  signed [7:0] shl_ln73_667_fu_5249_p1;
wire   [10:0] shl_ln73_667_fu_5249_p3;
wire  signed [11:0] sext_ln73_1383_fu_5257_p1;
wire  signed [11:0] sext_ln73_1382_fu_5245_p1;
wire  signed [7:0] shl_ln73_668_fu_5267_p1;
wire   [8:0] shl_ln73_668_fu_5267_p3;
wire  signed [11:0] sext_ln73_1384_fu_5275_p1;
wire   [11:0] sub_ln73_1055_fu_5285_p2;
wire  signed [7:0] sext_ln73_1386_fu_5306_p0;
wire  signed [7:0] shl_ln73_669_fu_5315_p1;
wire   [9:0] shl_ln73_669_fu_5315_p3;
wire  signed [10:0] sext_ln73_1388_fu_5323_p1;
wire  signed [10:0] sext_ln73_1386_fu_5306_p1;
wire  signed [7:0] shl_ln73_670_fu_5333_p1;
wire   [10:0] shl_ln73_670_fu_5333_p3;
wire   [10:0] sub_ln73_1057_fu_5345_p2;
wire  signed [7:0] sext_ln73_1390_fu_5361_p0;
wire  signed [7:0] shl_ln73_671_fu_5365_p1;
wire  signed [9:0] shl_ln73_671_fu_5365_p3;
wire  signed [7:0] shl_ln73_672_fu_5377_p1;
wire   [10:0] shl_ln73_672_fu_5377_p3;
wire  signed [11:0] sext_ln73_1392_fu_5385_p1;
wire  signed [11:0] sext_ln73_1390_fu_5361_p1;
wire  signed [7:0] shl_ln73_673_fu_5395_p1;
wire  signed [7:0] sext_ln73_1394_fu_5412_p0;
wire  signed [7:0] shl_ln73_674_fu_5416_p1;
wire   [10:0] shl_ln73_674_fu_5416_p3;
wire  signed [11:0] sext_ln73_1394_fu_5412_p1;
wire  signed [11:0] sext_ln73_1395_fu_5424_p1;
wire  signed [7:0] shl_ln73_675_fu_5434_p1;
wire   [8:0] shl_ln73_675_fu_5434_p3;
wire  signed [11:0] sext_ln73_1396_fu_5442_p1;
wire   [11:0] sub_ln73_1060_fu_5446_p2;
wire  signed [7:0] shl_ln73_676_fu_5456_p1;
wire   [10:0] shl_ln73_677_fu_5468_p3;
wire  signed [8:0] shl_ln73_678_fu_5480_p3;
wire  signed [11:0] sext_ln73_1398_fu_5476_p1;
wire  signed [11:0] sext_ln73_1399_fu_5488_p1;
wire   [11:0] shl_ln73_679_fu_5498_p3;
wire  signed [12:0] sext_ln73_1400_fu_5506_p1;
wire  signed [7:0] sext_ln73_1401_fu_5526_p0;
wire  signed [7:0] shl_ln73_680_fu_5535_p1;
wire   [10:0] shl_ln73_680_fu_5535_p3;
wire  signed [7:0] shl_ln73_681_fu_5547_p1;
wire   [8:0] shl_ln73_681_fu_5547_p3;
wire  signed [11:0] sext_ln73_1403_fu_5543_p1;
wire  signed [11:0] sext_ln73_1404_fu_5555_p1;
wire  signed [7:0] shl_ln73_682_fu_5565_p1;
wire  signed [9:0] shl_ln73_682_fu_5565_p3;
wire  signed [11:0] sext_ln73_1401_fu_5526_p1;
wire  signed [7:0] sext_ln73_1406_fu_5587_p0;
wire  signed [7:0] shl_ln73_683_fu_5591_p1;
wire  signed [7:0] shl_ln73_684_fu_5599_p1;
wire   [9:0] shl_ln73_684_fu_5599_p3;
wire  signed [10:0] sext_ln73_1407_fu_5607_p1;
wire  signed [10:0] sext_ln73_1406_fu_5587_p1;
wire  signed [7:0] sext_ln73_1408_fu_5627_p0;
wire  signed [7:0] shl_ln73_685_fu_5631_p1;
wire   [9:0] shl_ln73_685_fu_5631_p3;
wire  signed [10:0] sext_ln73_1409_fu_5639_p1;
wire   [10:0] sub_ln73_1067_fu_5643_p2;
wire  signed [10:0] sext_ln73_1408_fu_5627_p1;
wire  signed [7:0] shl_ln73_686_fu_5655_p1;
wire   [11:0] shl_ln73_686_fu_5655_p3;
wire  signed [7:0] shl_ln73_687_fu_5667_p1;
wire   [8:0] shl_ln73_687_fu_5667_p3;
wire  signed [12:0] sext_ln73_1410_fu_5663_p1;
wire  signed [12:0] sext_ln73_1411_fu_5675_p1;
wire  signed [7:0] sext_ln73_1412_fu_5689_p0;
wire  signed [7:0] shl_ln73_688_fu_5693_p1;
wire  signed [9:0] shl_ln73_688_fu_5693_p3;
wire  signed [10:0] sext_ln73_1413_fu_5701_p1;
wire  signed [10:0] sext_ln73_1412_fu_5689_p1;
wire  signed [7:0] shl_ln73_689_fu_5711_p1;
wire   [10:0] shl_ln73_689_fu_5711_p3;
wire  signed [7:0] shl_ln73_690_fu_5723_p1;
wire   [8:0] shl_ln73_690_fu_5723_p3;
wire  signed [11:0] sext_ln73_1414_fu_5719_p1;
wire  signed [11:0] sext_ln73_1415_fu_5731_p1;
wire  signed [7:0] sext_ln73_1416_fu_5745_p0;
wire  signed [7:0] sext_ln73_1417_fu_5749_p0;
wire  signed [7:0] shl_ln73_691_fu_5753_p1;
wire   [10:0] shl_ln73_691_fu_5753_p3;
wire  signed [7:0] shl_ln73_692_fu_5765_p1;
wire   [8:0] shl_ln73_692_fu_5765_p3;
wire  signed [11:0] sext_ln73_1418_fu_5761_p1;
wire  signed [11:0] sext_ln73_1419_fu_5773_p1;
wire  signed [11:0] sext_ln73_1416_fu_5745_p1;
wire  signed [7:0] shl_ln73_693_fu_5789_p1;
wire   [9:0] shl_ln73_693_fu_5789_p3;
wire  signed [10:0] sext_ln73_1420_fu_5797_p1;
wire  signed [10:0] sext_ln73_1417_fu_5749_p1;
wire  signed [7:0] sext_ln73_1421_fu_5817_p0;
wire  signed [7:0] sext_ln73_1422_fu_5821_p0;
wire  signed [7:0] shl_ln73_694_fu_5825_p1;
wire   [10:0] shl_ln73_694_fu_5825_p3;
wire  signed [11:0] sext_ln73_1421_fu_5817_p1;
wire  signed [11:0] sext_ln73_1423_fu_5833_p1;
wire  signed [7:0] shl_ln73_695_fu_5843_p1;
wire   [9:0] shl_ln73_695_fu_5843_p3;
wire  signed [10:0] sext_ln73_1422_fu_5821_p1;
wire  signed [10:0] sext_ln73_1424_fu_5851_p1;
wire  signed [7:0] shl_ln73_696_fu_5867_p1;
wire  signed [8:0] shl_ln73_696_fu_5867_p3;
wire   [11:0] sub_ln73_1075_fu_5861_p2;
wire  signed [11:0] sext_ln73_1426_fu_5879_p1;
wire  signed [7:0] sext_ln73_1427_fu_5899_p0;
wire  signed [7:0] shl_ln73_697_fu_5903_p1;
wire   [11:0] shl_ln73_697_fu_5903_p3;
wire  signed [7:0] shl_ln73_698_fu_5915_p1;
wire  signed [12:0] sext_ln73_1431_fu_5923_p1;
wire  signed [12:0] sext_ln73_1430_fu_5911_p1;
wire  signed [10:0] sext_ln73_1427_fu_5899_p1;
wire  signed [10:0] sext_ln73_1434_fu_5933_p1;
wire  signed [7:0] sext_ln73_1435_fu_5947_p0;
wire  signed [7:0] shl_ln73_701_fu_5951_p1;
wire   [10:0] shl_ln73_701_fu_5951_p3;
wire  signed [11:0] sext_ln73_1436_fu_5959_p1;
wire  signed [11:0] sext_ln73_1435_fu_5947_p1;
wire  signed [7:0] shl_ln73_702_fu_5969_p1;
wire   [8:0] shl_ln73_702_fu_5969_p3;
wire  signed [11:0] sext_ln73_1437_fu_5977_p1;
wire  signed [7:0] sext_ln73_1438_fu_5997_p0;
wire  signed [7:0] shl_ln73_703_fu_6001_p1;
wire  signed [10:0] sext_ln73_1439_fu_6009_p1;
wire  signed [10:0] sext_ln73_1438_fu_5997_p1;
wire  signed [7:0] shl_ln73_706_fu_6034_p1;
wire   [10:0] shl_ln73_706_fu_6034_p3;
wire  signed [7:0] shl_ln73_707_fu_6052_p1;
wire   [8:0] shl_ln73_707_fu_6052_p3;
wire   [11:0] sub_ln73_1086_fu_6046_p2;
wire  signed [11:0] sext_ln73_1445_fu_6060_p1;
wire  signed [7:0] shl_ln73_717_fu_6079_p1;
wire   [10:0] shl_ln73_717_fu_6079_p3;
wire  signed [7:0] sext_ln73_1462_fu_6095_p0;
wire  signed [7:0] shl_ln73_718_fu_6100_p1;
wire   [11:0] shl_ln73_718_fu_6100_p3;
wire  signed [12:0] sext_ln73_1463_fu_6108_p1;
wire   [10:0] sub_ln73_1049_fu_5099_p2;
wire   [10:0] add_ln58_fu_6127_p2;
wire   [10:0] add_ln73_fu_5141_p2;
wire   [10:0] add_ln58_2558_fu_6137_p2;
wire  signed [11:0] sext_ln58_3695_fu_6143_p1;
wire   [11:0] sub_ln73_1048_fu_5081_p2;
wire   [11:0] add_ln58_2559_fu_6147_p2;
wire   [11:0] sub_ln73_1050_fu_5159_p2;
wire  signed [11:0] sext_ln58_fu_6133_p1;
wire   [11:0] add_ln58_2560_fu_6157_p2;
wire   [10:0] sub_ln73_1051_fu_5165_p2;
wire   [10:0] add_ln58_2561_fu_6167_p2;
wire   [10:0] sub_ln73_1052_fu_5191_p2;
wire  signed [10:0] sext_ln73_1373_fu_5121_p1;
wire   [10:0] sub_ln58_fu_6177_p2;
wire  signed [12:0] sext_ln58_2268_fu_6153_p1;
wire  signed [12:0] sext_ln73_1381_fu_5227_p1;
wire   [12:0] add_ln58_2562_fu_6187_p2;
wire   [11:0] sub_ln73_1054_fu_5261_p2;
wire   [11:0] add_ln58_2563_fu_6197_p2;
wire   [11:0] add_ln73_84_fu_5279_p2;
wire   [11:0] sub_ln73_1056_fu_5291_p2;
wire  signed [11:0] add_ln73_95_cast_fu_5237_p1;
wire   [11:0] add_ln58_2564_fu_6211_p2;
wire  signed [12:0] sext_ln58_3696_fu_6217_p1;
wire  signed [12:0] sext_ln58_2269_fu_6163_p1;
wire   [12:0] add_ln58_2565_fu_6221_p2;
wire  signed [11:0] sext_ln58_2270_fu_6173_p1;
wire   [11:0] add_ln58_2566_fu_6231_p2;
wire   [10:0] add_ln73_85_fu_5327_p2;
wire   [12:0] mul_ln73_39_fu_117_p2;
wire  signed [7:0] a_cast92_i_fu_6249_p0;
wire  signed [7:0] a_55_cast91_i_fu_6253_p0;
wire  signed [7:0] a_56_cast93_i_fu_6257_p0;
wire  signed [8:0] a_55_cast91_i_fu_6253_p1;
wire  signed [8:0] a_cast92_i_fu_6249_p1;
wire   [8:0] empty_fu_6261_p2;
wire  signed [9:0] p_cast_i_fu_6267_p1;
wire  signed [9:0] a_56_cast93_i_fu_6257_p1;
wire   [9:0] tmp1986_i_fu_6271_p2;
wire   [11:0] tmp_fu_6277_p3;
wire  signed [11:0] sext_ln73_1389_fu_5341_p1;
wire   [11:0] add_ln58_2567_fu_6289_p2;
wire  signed [12:0] sext_ln58_3700_fu_6285_p1;
wire  signed [12:0] sext_ln58_3701_fu_6295_p1;
wire   [10:0] sub_ln73_1058_fu_5351_p2;
wire  signed [11:0] sext_ln58_2271_fu_6183_p1;
wire  signed [11:0] sext_ln73_1391_fu_5373_p1;
wire   [11:0] sub_ln58_27_fu_6309_p2;
wire  signed [13:0] sext_ln58_2272_fu_6193_p1;
wire  signed [13:0] sext_ln58_2274_fu_6207_p1;
wire  signed [11:0] sext_ln58_3697_fu_6241_p1;
wire   [11:0] sub_ln58_653_fu_6325_p2;
wire  signed [13:0] sext_ln58_3698_fu_6331_p1;
wire   [13:0] add_ln58_2569_fu_6319_p2;
wire   [11:0] add_ln73_86_fu_5389_p2;
wire   [12:0] add_ln58_2568_fu_6299_p2;
wire  signed [12:0] sext_ln58_3773_fu_6345_p1;
wire   [8:0] shl_ln73_673_fu_5395_p3;
wire   [11:0] sub_ln73_1059_fu_5428_p2;
wire  signed [12:0] sext_ln58_2283_fu_6315_p1;
wire  signed [12:0] sext_ln73_1397_fu_5452_p1;
wire  signed [9:0] shl_ln73_676_fu_5456_p3;
wire  signed [12:0] sext_ln58_2276_fu_6237_p1;
wire  signed [12:0] sext_ln58_2281_fu_6305_p1;
wire  signed [10:0] sext_ln58_3704_fu_6369_p1;
wire  signed [10:0] sext_ln58_3702_fu_6355_p1;
wire   [10:0] add_ln58_2573_fu_6383_p2;
wire  signed [12:0] sext_ln58_3706_fu_6389_p1;
wire   [12:0] add_ln58_2572_fu_6377_p2;
wire   [12:0] add_ln58_2574_fu_6393_p2;
wire   [11:0] sub_ln73_1061_fu_5492_p2;
wire   [12:0] sub_ln73_1062_fu_5510_p2;
wire   [11:0] sub_ln73_1063_fu_5516_p2;
wire   [11:0] sub_ln73_1064_fu_5559_p2;
wire   [13:0] mul_ln73_fu_166_p2;
wire  signed [13:0] sext_ln58_2273_fu_6203_p1;
wire  signed [12:0] sext_ln58_3707_fu_6403_p1;
wire  signed [12:0] sext_ln58_3710_fu_6419_p1;
wire   [12:0] add_ln58_2576_fu_6429_p2;
wire  signed [12:0] sext_ln58_3703_fu_6359_p1;
wire   [12:0] add_ln58_2577_fu_6435_p2;
wire  signed [13:0] sext_ln58_3711_fu_6441_p1;
wire   [13:0] add_ln58_2575_fu_6423_p2;
wire   [13:0] add_ln58_2578_fu_6445_p2;
wire   [12:0] add_ln58_2571_fu_6363_p2;
wire  signed [12:0] sext_ln73_1405_fu_5573_p1;
wire  signed [11:0] sub_ln73_1065_fu_5577_p2;
wire  signed [13:0] sext_ln58_2275_fu_6227_p1;
wire  signed [13:0] sext_ln58_2278_fu_6245_p1;
wire  signed [11:0] sext_ln58_3705_fu_6373_p1;
wire   [11:0] add_ln58_2580_fu_6471_p2;
wire  signed [12:0] sext_ln58_3713_fu_6477_p1;
wire  signed [12:0] sext_ln58_3699_fu_6341_p1;
wire   [12:0] add_ln58_2581_fu_6481_p2;
wire  signed [13:0] sext_ln58_3714_fu_6487_p1;
wire   [13:0] add_ln58_2579_fu_6465_p2;
wire   [10:0] shl_ln73_683_fu_5591_p3;
wire   [12:0] sub_ln58_28_fu_6455_p2;
wire  signed [13:0] sext_ln58_3717_fu_6505_p1;
wire  signed [13:0] sext_ln58_3716_fu_6501_p1;
wire   [10:0] sub_ln73_1066_fu_5611_p2;
wire   [10:0] add_ln73_87_fu_5617_p2;
wire   [10:0] sub_ln73_1068_fu_5649_p2;
wire   [10:0] add_ln73_88_fu_5705_p2;
wire   [11:0] sub_ln73_1070_fu_5735_p2;
wire  signed [13:0] sext_ln58_2292_fu_6399_p1;
wire  signed [13:0] sext_ln58_2296_fu_6415_p1;
wire  signed [11:0] sext_ln58_3719_fu_6519_p1;
wire  signed [11:0] sext_ln58_3723_fu_6535_p1;
wire   [11:0] add_ln58_2584_fu_6545_p2;
wire  signed [12:0] sext_ln58_3724_fu_6551_p1;
wire  signed [12:0] sext_ln58_3712_fu_6461_p1;
wire   [12:0] add_ln58_2585_fu_6555_p2;
wire  signed [13:0] sext_ln58_3725_fu_6561_p1;
wire   [13:0] add_ln58_2583_fu_6539_p2;
wire   [11:0] add_ln73_89_fu_5777_p2;
wire   [11:0] sub_ln73_1071_fu_5783_p2;
wire   [10:0] add_ln73_90_fu_5801_p2;
wire   [11:0] sub_ln73_1073_fu_5837_p2;
wire   [10:0] sub_ln73_1074_fu_5855_p2;
wire   [13:0] mul_ln73_40_fu_127_p2;
wire  signed [13:0] sext_ln58_3708_fu_6407_p1;
wire   [12:0] mul_ln73_41_fu_168_p2;
wire  signed [12:0] sext_ln58_3727_fu_6575_p1;
wire   [12:0] add_ln58_2589_fu_6597_p2;
wire   [11:0] sub_ln73_1076_fu_5883_p2;
wire  signed [11:0] sext_ln58_3720_fu_6523_p1;
wire   [11:0] add_ln58_2590_fu_6607_p2;
wire  signed [13:0] sext_ln58_3734_fu_6613_p1;
wire  signed [13:0] sext_ln58_3733_fu_6603_p1;
wire  signed [11:0] sext_ln58_3721_fu_6527_p1;
wire  signed [11:0] sext_ln58_3731_fu_6587_p1;
wire   [10:0] sub_ln73_1082_fu_5937_p2;
wire   [11:0] sub_ln73_1083_fu_5987_p2;
wire   [10:0] add_ln73_93_fu_6013_p2;
wire   [12:0] sub_ln73_1078_fu_5927_p2;
wire  signed [12:0] sext_ln58_3726_fu_6571_p1;
wire   [12:0] add_ln58_2596_fu_6645_p2;
wire  signed [14:0] sext_ln58_3745_fu_6651_p1;
wire  signed [14:0] sext_ln58_2298_fu_6451_p1;
wire  signed [12:0] sext_ln58_3730_fu_6583_p1;
wire  signed [12:0] sext_ln58_3741_fu_6633_p1;
wire  signed [11:0] sext_ln58_3744_fu_6641_p1;
wire   [11:0] add_ln58_2599_fu_6667_p2;
wire  signed [12:0] sext_ln58_3746_fu_6673_p1;
wire   [12:0] add_ln58_2598_fu_6661_p2;
wire   [12:0] add_ln58_2600_fu_6677_p2;
wire  signed [14:0] sext_ln58_3747_fu_6683_p1;
wire   [14:0] add_ln58_2597_fu_6655_p2;
wire   [10:0] sub_ln73_1084_fu_6019_p2;
wire   [11:0] sub_ln73_1087_fu_6064_p2;
wire   [12:0] sub_ln73_1069_fu_5679_p2;
wire   [12:0] mul_ln73_45_fu_195_p2;
wire   [12:0] mul_ln73_43_fu_196_p2;
wire   [12:0] add_ln73_94_fu_6112_p2;
wire   [12:0] mul_ln73_47_fu_115_p2;
wire  signed [12:0] sext_ln58_3722_fu_6531_p1;
wire   [12:0] add_ln58_2615_fu_6713_p2;
wire  signed [12:0] sext_ln58_3743_fu_6637_p1;
wire  signed [12:0] sext_ln58_3751_fu_6697_p1;
wire   [12:0] add_ln58_2616_fu_6723_p2;
wire  signed [13:0] sext_ln58_3775_fu_6729_p1;
wire  signed [13:0] sext_ln58_3774_fu_6719_p1;
wire  signed [11:0] sext_ln58_3718_fu_6515_p1;
wire  signed [11:0] sext_ln73_1460_fu_6087_p1;
wire   [11:0] sub_ln58_658_fu_6739_p2;
wire  signed [11:0] sext_ln58_3728_fu_6579_p1;
wire  signed [11:0] sext_ln58_3739_fu_6629_p1;
wire   [11:0] add_ln58_2619_fu_6749_p2;
wire  signed [12:0] sext_ln58_3778_fu_6755_p1;
wire  signed [12:0] sext_ln58_3777_fu_6745_p1;
wire   [12:0] add_ln58_2620_fu_6759_p2;
wire  signed [11:0] sext_ln58_3749_fu_6693_p1;
wire  signed [11:0] sext_ln58_3715_fu_6497_p1;
wire  signed [9:0] sext_ln58_3709_fu_6411_p1;
wire  signed [9:0] sext_ln73_1425_fu_5875_p1;
wire   [9:0] sub_ln58_659_fu_6775_p2;
wire  signed [11:0] sext_ln58_3780_fu_6781_p1;
wire   [11:0] add_ln58_2621_fu_6769_p2;
wire   [11:0] add_ln58_2622_fu_6785_p2;
wire  signed [13:0] sext_ln58_3781_fu_6791_p1;
wire  signed [13:0] sext_ln58_3779_fu_6765_p1;
wire   [10:0] shl_ln73_699_fu_6808_p3;
wire  signed [11:0] sext_ln73_1432_fu_6815_p1;
wire   [8:0] shl_ln73_700_fu_6825_p3;
wire   [11:0] sub_ln73_1079_fu_6819_p2;
wire  signed [11:0] sext_ln73_1433_fu_6832_p1;
wire  signed [11:0] sext_ln73_1429_fu_6805_p1;
wire   [8:0] shl_ln73_704_fu_6848_p3;
wire   [9:0] shl_ln73_705_fu_6862_p3;
wire  signed [10:0] sext_ln73_1441_fu_6859_p1;
wire  signed [10:0] sext_ln73_1443_fu_6869_p1;
wire  signed [7:0] sext_ln73_1446_fu_6889_p0;
wire  signed [7:0] shl_ln73_708_fu_6893_p1;
wire  signed [7:0] shl_ln73_709_fu_6901_p1;
wire   [11:0] shl_ln73_709_fu_6901_p3;
wire  signed [7:0] shl_ln73_710_fu_6913_p1;
wire   [8:0] shl_ln73_710_fu_6913_p3;
wire  signed [12:0] sext_ln73_1448_fu_6921_p1;
wire  signed [12:0] sext_ln73_1447_fu_6909_p1;
wire  signed [7:0] shl_ln73_711_fu_6931_p1;
wire   [9:0] shl_ln73_711_fu_6931_p3;
wire  signed [10:0] sext_ln73_1449_fu_6939_p1;
wire  signed [10:0] sext_ln73_1446_fu_6889_p1;
wire  signed [7:0] sext_ln73_1451_fu_6958_p0;
wire  signed [7:0] shl_ln73_712_fu_6962_p1;
wire  signed [10:0] shl_ln73_712_fu_6962_p3;
wire  signed [7:0] shl_ln73_713_fu_6974_p1;
wire   [8:0] shl_ln73_713_fu_6974_p3;
wire  signed [11:0] sext_ln73_1453_fu_6982_p1;
wire  signed [11:0] sext_ln73_1452_fu_6970_p1;
wire  signed [7:0] shl_ln73_714_fu_6992_p1;
wire   [11:0] shl_ln73_714_fu_6992_p3;
wire  signed [7:0] shl_ln73_715_fu_7004_p1;
wire  signed [9:0] shl_ln73_715_fu_7004_p3;
wire  signed [12:0] sext_ln73_1456_fu_7016_p1;
wire  signed [12:0] sext_ln73_1454_fu_7000_p1;
wire  signed [10:0] sext_ln73_1455_fu_7012_p1;
wire  signed [10:0] sext_ln73_1451_fu_6958_p1;
wire  signed [9:0] shl_ln73_716_fu_7035_p3;
wire  signed [10:0] sext_ln73_1457_fu_7032_p1;
wire  signed [10:0] sext_ln73_1459_fu_7042_p1;
wire   [9:0] shl_ln73_719_fu_7055_p3;
wire  signed [10:0] sext_ln73_1464_fu_7062_p1;
wire  signed [10:0] sext_ln73_1461_fu_7052_p1;
wire   [10:0] shl_ln73_720_fu_7072_p3;
wire   [8:0] shl_ln73_721_fu_7083_p3;
wire  signed [11:0] sext_ln73_1465_fu_7079_p1;
wire  signed [11:0] sext_ln73_1466_fu_7090_p1;
wire   [10:0] shl_ln73_722_fu_7109_p3;
wire   [8:0] shl_ln73_723_fu_7120_p3;
wire  signed [11:0] sext_ln73_1470_fu_7127_p1;
wire  signed [11:0] sext_ln73_1469_fu_7116_p1;
wire   [9:0] shl_ln73_724_fu_7137_p3;
wire  signed [10:0] sext_ln73_1471_fu_7144_p1;
wire   [10:0] sub_ln73_1098_fu_7148_p2;
wire  signed [10:0] sext_ln73_1468_fu_7106_p1;
wire  signed [7:0] sext_ln73_1472_fu_7164_p0;
wire  signed [7:0] shl_ln73_725_fu_7173_p1;
wire   [9:0] shl_ln73_725_fu_7173_p3;
wire  signed [10:0] sext_ln73_1474_fu_7181_p1;
wire  signed [10:0] sext_ln73_1472_fu_7164_p1;
wire   [10:0] sub_ln73_1102_fu_7197_p2;
wire  signed [7:0] sext_ln73_1475_fu_7213_p0;
wire  signed [7:0] shl_ln73_726_fu_7217_p1;
wire   [9:0] shl_ln73_726_fu_7217_p3;
wire  signed [10:0] sext_ln73_1476_fu_7225_p1;
wire   [10:0] sub_ln73_1104_fu_7229_p2;
wire  signed [10:0] sext_ln73_1475_fu_7213_p1;
wire  signed [7:0] shl_ln73_727_fu_7241_p1;
wire   [10:0] shl_ln73_727_fu_7241_p3;
wire  signed [7:0] shl_ln73_728_fu_7253_p1;
wire   [8:0] shl_ln73_728_fu_7253_p3;
wire  signed [11:0] sext_ln73_1477_fu_7249_p1;
wire  signed [11:0] sext_ln73_1478_fu_7261_p1;
wire   [11:0] sub_ln73_1107_fu_7271_p2;
wire  signed [14:0] sext_ln58_3732_fu_7298_p1;
wire  signed [14:0] sext_ln58_2285_fu_7283_p1;
wire  signed [14:0] sext_ln58_3735_fu_7307_p1;
wire   [14:0] add_ln58_2588_fu_7301_p2;
wire   [14:0] add_ln58_2592_fu_7310_p2;
wire   [12:0] mul_ln73_42_fu_163_p2;
wire  signed [13:0] sext_ln58_2325_fu_7323_p1;
wire  signed [13:0] sext_ln58_3737_fu_7332_p1;
wire   [13:0] add_ln58_2593_fu_7327_p2;
wire   [13:0] add_ln58_2595_fu_7335_p2;
wire   [11:0] sub_ln73_1080_fu_6836_p2;
wire   [11:0] sub_ln73_1081_fu_6842_p2;
wire   [10:0] sub_ln73_1085_fu_6873_p2;
wire   [10:0] sub_ln73_1088_fu_6879_p2;
wire   [12:0] sub_ln73_1089_fu_6925_p2;
wire   [10:0] sub_ln73_1090_fu_6943_p2;
wire   [11:0] sub_ln73_1091_fu_6986_p2;
wire   [12:0] sub_ln73_1092_fu_7020_p2;
wire   [10:0] sub_ln73_1093_fu_7026_p2;
wire  signed [14:0] sext_ln58_3757_fu_7393_p1;
wire  signed [14:0] sext_ln58_2302_fu_7289_p1;
wire  signed [12:0] sext_ln58_3736_fu_7320_p1;
wire  signed [12:0] sext_ln58_3738_fu_7349_p1;
wire  signed [11:0] sext_ln58_3748_fu_7362_p1;
wire   [11:0] add_ln58_2605_fu_7408_p2;
wire  signed [12:0] sext_ln58_3758_fu_7413_p1;
wire   [12:0] add_ln58_2604_fu_7402_p2;
wire   [12:0] add_ln58_2606_fu_7417_p2;
wire  signed [14:0] sext_ln58_3759_fu_7423_p1;
wire   [14:0] add_ln58_2603_fu_7396_p2;
wire   [14:0] add_ln58_2607_fu_7427_p2;
wire   [10:0] sub_ln73_1094_fu_7046_p2;
wire   [10:0] add_ln73_95_fu_7066_p2;
wire   [11:0] sub_ln73_1095_fu_7094_p2;
wire   [10:0] sub_ln73_1096_fu_7100_p2;
wire   [11:0] sub_ln73_1097_fu_7131_p2;
wire  signed [15:0] sext_ln58_3766_fu_7461_p1;
wire  signed [15:0] sext_ln58_2335_fu_7359_p1;
wire  signed [12:0] sext_ln58_3765_fu_7457_p1;
wire  signed [12:0] sext_ln58_3767_fu_7470_p1;
wire   [10:0] shl_ln73_708_fu_6893_p3;
wire  signed [11:0] sext_ln58_3769_fu_7484_p1;
wire  signed [11:0] sext_ln58_3768_fu_7480_p1;
wire   [11:0] sub_ln58_657_fu_7488_p2;
wire  signed [12:0] sext_ln58_3770_fu_7494_p1;
wire   [12:0] sub_ln58_656_fu_7474_p2;
wire   [12:0] add_ln58_2610_fu_7498_p2;
wire  signed [15:0] sext_ln58_3771_fu_7504_p1;
wire   [15:0] add_ln58_2609_fu_7464_p2;
wire   [15:0] add_ln58_2611_fu_7508_p2;
wire   [10:0] sub_ln73_1099_fu_7154_p2;
wire  signed [13:0] sext_ln58_3776_fu_7286_p1;
wire  signed [13:0] sext_ln58_3782_fu_7373_p1;
wire   [13:0] add_ln58_2612_fu_7522_p2;
wire  signed [13:0] sext_ln58_3755_fu_7385_p1;
wire  signed [13:0] sext_ln58_3764_fu_7453_p1;
wire   [13:0] add_ln58_2613_fu_7532_p2;
wire  signed [14:0] sext_ln58_3805_fu_7538_p1;
wire  signed [14:0] sext_ln58_3804_fu_7528_p1;
wire  signed [14:0] sext_ln58_3806_fu_7548_p1;
wire   [14:0] add_ln58_2614_fu_7542_p2;
wire   [14:0] add_ln58_2618_fu_7551_p2;
wire  signed [15:0] sext_ln58_3808_fu_7561_p1;
wire  signed [15:0] sext_ln58_3807_fu_7557_p1;
wire   [15:0] add_ln58_2624_fu_7564_p2;
wire   [10:0] sub_ln73_1101_fu_7191_p2;
wire   [10:0] sub_ln73_1103_fu_7203_p2;
wire   [10:0] sub_ln73_1105_fu_7235_p2;
wire   [12:0] mul_ln73_44_fu_141_p2;
wire   [12:0] mul_ln73_48_fu_120_p2;
wire   [12:0] add_ln58_2625_fu_7586_p2;
wire  signed [14:0] sext_ln58_3786_fu_7592_p1;
wire  signed [14:0] sext_ln58_2326_fu_7341_p1;
wire  signed [11:0] sext_ln58_3750_fu_7365_p1;
wire   [11:0] add_ln58_2627_fu_7602_p2;
wire  signed [11:0] sext_ln58_3761_fu_7441_p1;
wire  signed [11:0] sext_ln58_3785_fu_7582_p1;
wire   [11:0] add_ln58_2628_fu_7611_p2;
wire  signed [12:0] sext_ln58_3788_fu_7617_p1;
wire  signed [12:0] sext_ln58_3787_fu_7607_p1;
wire   [12:0] add_ln58_2629_fu_7621_p2;
wire  signed [14:0] sext_ln58_3789_fu_7627_p1;
wire   [14:0] add_ln58_2626_fu_7596_p2;
wire   [14:0] add_ln58_2630_fu_7631_p2;
wire   [11:0] sub_ln73_1106_fu_7265_p2;
wire  signed [15:0] sext_ln58_2321_fu_7316_p1;
wire  signed [15:0] sext_ln58_2327_fu_7345_p1;
wire  signed [12:0] sext_ln58_3742_fu_7356_p1;
wire  signed [12:0] sext_ln58_3754_fu_7381_p1;
wire   [12:0] add_ln58_2632_fu_7651_p2;
wire  signed [15:0] sext_ln58_3791_fu_7657_p1;
wire   [15:0] add_ln58_2631_fu_7645_p2;
wire  signed [12:0] sext_ln58_3762_fu_7445_p1;
wire  signed [12:0] sext_ln58_3790_fu_7641_p1;
wire   [10:0] sub_ln73_1100_fu_7185_p2;
wire  signed [11:0] sext_ln58_3792_fu_7673_p1;
wire   [11:0] sub_ln58_660_fu_7677_p2;
wire  signed [12:0] sext_ln58_3793_fu_7683_p1;
wire   [12:0] add_ln58_2634_fu_7667_p2;
wire   [12:0] add_ln58_2635_fu_7687_p2;
wire  signed [15:0] sext_ln58_3794_fu_7693_p1;
wire   [15:0] add_ln58_2633_fu_7661_p2;
wire   [15:0] add_ln58_2636_fu_7697_p2;
wire   [11:0] sub_ln73_1108_fu_7277_p2;
wire  signed [15:0] sext_ln58_2355_fu_7433_p1;
wire  signed [15:0] sext_ln58_2378_fu_7707_p1;
wire  signed [11:0] sext_ln58_3772_fu_7518_p1;
wire  signed [11:0] sext_ln58_3783_fu_7574_p1;
wire   [11:0] add_ln58_2638_fu_7717_p2;
wire  signed [11:0] sext_ln58_3763_fu_7449_p1;
wire   [11:0] add_ln58_2639_fu_7723_p2;
wire  signed [15:0] sext_ln58_3795_fu_7729_p1;
wire   [15:0] add_ln58_2637_fu_7711_p2;
wire   [15:0] add_ln58_2640_fu_7733_p2;
wire  signed [7:0] sext_ln58_3796_fu_7743_p0;
wire  signed [12:0] sext_ln58_3729_fu_7295_p1;
wire   [12:0] add_ln58_2641_fu_7747_p2;
wire  signed [14:0] sext_ln58_3797_fu_7753_p1;
wire  signed [14:0] sext_ln58_2313_fu_7292_p1;
wire  signed [11:0] sext_ln58_3752_fu_7369_p1;
wire  signed [11:0] sext_ln58_3753_fu_7377_p1;
wire   [11:0] add_ln58_2643_fu_7763_p2;
wire  signed [12:0] sext_ln58_3798_fu_7769_p1;
wire   [12:0] add_ln58_2644_fu_7773_p2;
wire  signed [14:0] sext_ln58_3799_fu_7779_p1;
wire   [14:0] add_ln58_2642_fu_7757_p2;
wire  signed [11:0] sext_ln58_3760_fu_7437_p1;
wire   [11:0] add_ln58_2646_fu_7789_p2;
wire  signed [11:0] sext_ln58_3756_fu_7389_p1;
wire   [11:0] add_ln58_2647_fu_7795_p2;
wire  signed [11:0] sext_ln58_3784_fu_7578_p1;
wire  signed [11:0] sext_ln58_3740_fu_7353_p1;
wire  signed [9:0] sext_ln58_3796_fu_7743_p1;
wire  signed [9:0] sext_ln73_1440_fu_6855_p1;
wire   [9:0] sub_ln58_661_fu_7811_p2;
wire  signed [11:0] sext_ln58_3801_fu_7817_p1;
wire   [11:0] add_ln58_2648_fu_7805_p2;
wire   [11:0] add_ln58_2649_fu_7821_p2;
wire  signed [12:0] sext_ln58_3802_fu_7827_p1;
wire  signed [12:0] sext_ln58_3800_fu_7801_p1;
wire   [12:0] add_ln58_2650_fu_7831_p2;
wire  signed [14:0] sext_ln58_3803_fu_7837_p1;
wire   [14:0] add_ln58_2645_fu_7783_p2;
wire   [14:0] add_ln58_2651_fu_7841_p2;
wire  signed [21:0] sext_ln58_2366_fu_7514_p1;
wire  signed [21:0] sext_ln58_2375_fu_7637_p1;
wire  signed [21:0] sext_ln58_2377_fu_7703_p1;
wire  signed [21:0] sext_ln58_2379_fu_7739_p1;
wire  signed [21:0] sext_ln58_2369_fu_7570_p1;
wire  signed [21:0] sext_ln68_fu_7847_p1;
reg    ap_ce_reg;
reg   [21:0] ap_return_0_int_reg;
reg   [21:0] ap_return_1_int_reg;
reg   [21:0] ap_return_2_int_reg;
reg   [21:0] ap_return_3_int_reg;
reg   [21:0] ap_return_4_int_reg;
reg   [21:0] ap_return_5_int_reg;

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U28(
    .din0(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_2),
    .din1(mul_ln73_47_fu_115_p1),
    .dout(mul_ln73_47_fu_115_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U29(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .din1(mul_ln73_39_fu_117_p1),
    .dout(mul_ln73_39_fu_117_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U30(
    .din0(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_1),
    .din1(mul_ln73_48_fu_120_p1),
    .dout(mul_ln73_48_fu_120_p2)
);

myproject_mul_8s_6s_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_0_U31(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .din1(mul_ln73_40_fu_127_p1),
    .dout(mul_ln73_40_fu_127_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U32(
    .din0(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5),
    .din1(mul_ln73_44_fu_141_p1),
    .dout(mul_ln73_44_fu_141_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U33(
    .din0(a_25_reg_7897),
    .din1(mul_ln73_42_fu_163_p1),
    .dout(mul_ln73_42_fu_163_p2)
);

myproject_mul_8s_6ns_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_1_0_U34(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .din1(mul_ln73_fu_166_p1),
    .dout(mul_ln73_fu_166_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U35(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .din1(mul_ln73_41_fu_168_p1),
    .dout(mul_ln73_41_fu_168_p2)
);

myproject_mul_8s_5s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_0_U36(
    .din0(mul_ln73_46_fu_182_p0),
    .din1(mul_ln73_46_fu_182_p1),
    .dout(mul_ln73_46_fu_182_p2)
);

myproject_mul_8s_5ns_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_1_0_U37(
    .din0(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_4),
    .din1(mul_ln73_45_fu_195_p1),
    .dout(mul_ln73_45_fu_195_p2)
);

myproject_mul_8s_5ns_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_1_0_U38(
    .din0(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7),
    .din1(mul_ln73_43_fu_196_p1),
    .dout(mul_ln73_43_fu_196_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        a_25_reg_7897 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10;
        a_27_reg_7920 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8;
        a_28_reg_7930 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7;
        a_31_reg_7941 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_4;
        a_32_reg_7947 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_3;
        a_33_reg_7955 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_2;
        add_ln58_2570_reg_7963 <= add_ln58_2570_fu_6335_p2;
        add_ln58_2582_reg_7973 <= add_ln58_2582_fu_6491_p2;
        add_ln58_2586_reg_7983 <= add_ln58_2586_fu_6565_p2;
        add_ln58_2587_reg_7988 <= add_ln58_2587_fu_6591_p2;
        add_ln58_2591_reg_7993 <= add_ln58_2591_fu_6617_p2;
        add_ln58_2594_reg_7998 <= add_ln58_2594_fu_6623_p2;
        add_ln58_2601_reg_8003 <= add_ln58_2601_fu_6687_p2;
        add_ln58_2602_reg_8008 <= add_ln58_2602_fu_6701_p2;
        add_ln58_2608_reg_8013 <= add_ln58_2608_fu_6707_p2;
        add_ln58_2617_reg_8018 <= add_ln58_2617_fu_6733_p2;
        add_ln58_2623_reg_8023 <= add_ln58_2623_fu_6795_p2;
        add_ln73_91_reg_7910 <= add_ln73_91_fu_5963_p2;
        add_ln73_92_reg_7915[11 : 1] <= add_ln73_92_fu_5981_p2[11 : 1];
        mul_ln73_46_reg_3790 <= mul_ln73_46_fu_182_p2;
        sext_ln73_1444_reg_7936[11 : 3] <= sext_ln73_1444_fu_6042_p1[11 : 3];
        shl_ln73_698_reg_7905[9 : 2] <= shl_ln73_698_fu_5915_p3[9 : 2];
        shl_ln73_703_reg_7925[9 : 2] <= shl_ln73_703_fu_6001_p3[9 : 2];
        sub_ln58_654_reg_7968[12 : 2] <= sub_ln58_654_fu_6349_p2[12 : 2];
        sub_ln58_655_reg_7978 <= sub_ln58_655_fu_6509_p2;
        sub_ln73_1072_reg_7887[11 : 1] <= sub_ln73_1072_fu_5807_p2[11 : 1];
        sub_ln73_1077_reg_7892[11 : 1] <= sub_ln73_1077_fu_5889_p2[11 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln58_2366_fu_7514_p1;
        ap_return_1_int_reg <= sext_ln58_2375_fu_7637_p1;
        ap_return_2_int_reg <= sext_ln58_2377_fu_7703_p1;
        ap_return_3_int_reg <= sext_ln58_2379_fu_7739_p1;
        ap_return_4_int_reg <= sext_ln58_2369_fu_7570_p1;
        ap_return_5_int_reg <= sext_ln68_fu_7847_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln58_2366_fu_7514_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln58_2375_fu_7637_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln58_2377_fu_7703_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln58_2379_fu_7739_p1;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln58_2369_fu_7570_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln68_fu_7847_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

assign a_55_cast91_i_fu_6253_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign a_55_cast91_i_fu_6253_p1 = a_55_cast91_i_fu_6253_p0;

assign a_56_cast93_i_fu_6257_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign a_56_cast93_i_fu_6257_p1 = a_56_cast93_i_fu_6257_p0;

assign a_cast92_i_fu_6249_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;

assign a_cast92_i_fu_6249_p1 = a_cast92_i_fu_6249_p0;

assign add_ln58_2558_fu_6137_p2 = ($signed(add_ln73_fu_5141_p2) + $signed(11'd2032));

assign add_ln58_2559_fu_6147_p2 = ($signed(sext_ln58_3695_fu_6143_p1) + $signed(sub_ln73_1048_fu_5081_p2));

assign add_ln58_2560_fu_6157_p2 = ($signed(sub_ln73_1050_fu_5159_p2) + $signed(sext_ln58_fu_6133_p1));

assign add_ln58_2561_fu_6167_p2 = (sub_ln73_1051_fu_5165_p2 + 11'd64);

assign add_ln58_2562_fu_6187_p2 = ($signed(sext_ln58_2268_fu_6153_p1) + $signed(sext_ln73_1381_fu_5227_p1));

assign add_ln58_2563_fu_6197_p2 = ($signed(sub_ln73_1054_fu_5261_p2) + $signed(12'd3984));

assign add_ln58_2564_fu_6211_p2 = ($signed(sub_ln73_1056_fu_5291_p2) + $signed(add_ln73_95_cast_fu_5237_p1));

assign add_ln58_2565_fu_6221_p2 = ($signed(sext_ln58_3696_fu_6217_p1) + $signed(sext_ln58_2269_fu_6163_p1));

assign add_ln58_2566_fu_6231_p2 = ($signed(sub_ln73_1056_fu_5291_p2) + $signed(sext_ln58_2270_fu_6173_p1));

assign add_ln58_2567_fu_6289_p2 = ($signed(sext_ln73_1389_fu_5341_p1) + $signed(12'd4032));

assign add_ln58_2568_fu_6299_p2 = ($signed(sext_ln58_3700_fu_6285_p1) + $signed(sext_ln58_3701_fu_6295_p1));

assign add_ln58_2569_fu_6319_p2 = ($signed(sext_ln58_2272_fu_6193_p1) + $signed(sext_ln58_2274_fu_6207_p1));

assign add_ln58_2570_fu_6335_p2 = ($signed(sext_ln58_3698_fu_6331_p1) + $signed(add_ln58_2569_fu_6319_p2));

assign add_ln58_2571_fu_6363_p2 = ($signed(sext_ln58_2283_fu_6315_p1) + $signed(sext_ln73_1397_fu_5452_p1));

assign add_ln58_2572_fu_6377_p2 = ($signed(sext_ln58_2276_fu_6237_p1) + $signed(sext_ln58_2281_fu_6305_p1));

assign add_ln58_2573_fu_6383_p2 = ($signed(sext_ln58_3704_fu_6369_p1) + $signed(sext_ln58_3702_fu_6355_p1));

assign add_ln58_2574_fu_6393_p2 = ($signed(sext_ln58_3706_fu_6389_p1) + $signed(add_ln58_2572_fu_6377_p2));

assign add_ln58_2575_fu_6423_p2 = ($signed(mul_ln73_fu_166_p2) + $signed(sext_ln58_2273_fu_6203_p1));

assign add_ln58_2576_fu_6429_p2 = ($signed(sext_ln58_3707_fu_6403_p1) + $signed(sext_ln58_3710_fu_6419_p1));

assign add_ln58_2577_fu_6435_p2 = ($signed(add_ln58_2576_fu_6429_p2) + $signed(sext_ln58_3703_fu_6359_p1));

assign add_ln58_2578_fu_6445_p2 = ($signed(sext_ln58_3711_fu_6441_p1) + $signed(add_ln58_2575_fu_6423_p2));

assign add_ln58_2579_fu_6465_p2 = ($signed(sext_ln58_2275_fu_6227_p1) + $signed(sext_ln58_2278_fu_6245_p1));

assign add_ln58_2580_fu_6471_p2 = ($signed(sub_ln73_1065_fu_5577_p2) + $signed(sext_ln58_3705_fu_6373_p1));

assign add_ln58_2581_fu_6481_p2 = ($signed(sext_ln58_3713_fu_6477_p1) + $signed(sext_ln58_3699_fu_6341_p1));

assign add_ln58_2582_fu_6491_p2 = ($signed(sext_ln58_3714_fu_6487_p1) + $signed(add_ln58_2579_fu_6465_p2));

assign add_ln58_2583_fu_6539_p2 = ($signed(sext_ln58_2292_fu_6399_p1) + $signed(sext_ln58_2296_fu_6415_p1));

assign add_ln58_2584_fu_6545_p2 = ($signed(sext_ln58_3719_fu_6519_p1) + $signed(sext_ln58_3723_fu_6535_p1));

assign add_ln58_2585_fu_6555_p2 = ($signed(sext_ln58_3724_fu_6551_p1) + $signed(sext_ln58_3712_fu_6461_p1));

assign add_ln58_2586_fu_6565_p2 = ($signed(sext_ln58_3725_fu_6561_p1) + $signed(add_ln58_2583_fu_6539_p2));

assign add_ln58_2587_fu_6591_p2 = ($signed(mul_ln73_40_fu_127_p2) + $signed(sext_ln58_3708_fu_6407_p1));

assign add_ln58_2588_fu_7301_p2 = ($signed(sext_ln58_3732_fu_7298_p1) + $signed(sext_ln58_2285_fu_7283_p1));

assign add_ln58_2589_fu_6597_p2 = ($signed(mul_ln73_41_fu_168_p2) + $signed(sext_ln58_3727_fu_6575_p1));

assign add_ln58_2590_fu_6607_p2 = ($signed(sub_ln73_1076_fu_5883_p2) + $signed(sext_ln58_3720_fu_6523_p1));

assign add_ln58_2591_fu_6617_p2 = ($signed(sext_ln58_3734_fu_6613_p1) + $signed(sext_ln58_3733_fu_6603_p1));

assign add_ln58_2592_fu_7310_p2 = ($signed(sext_ln58_3735_fu_7307_p1) + $signed(add_ln58_2588_fu_7301_p2));

assign add_ln58_2593_fu_7327_p2 = ($signed(sub_ln58_655_reg_7978) + $signed(sext_ln58_2325_fu_7323_p1));

assign add_ln58_2594_fu_6623_p2 = ($signed(sext_ln58_3721_fu_6527_p1) + $signed(sext_ln58_3731_fu_6587_p1));

assign add_ln58_2595_fu_7335_p2 = ($signed(sext_ln58_3737_fu_7332_p1) + $signed(add_ln58_2593_fu_7327_p2));

assign add_ln58_2596_fu_6645_p2 = ($signed(sub_ln73_1078_fu_5927_p2) + $signed(sext_ln58_3726_fu_6571_p1));

assign add_ln58_2597_fu_6655_p2 = ($signed(sext_ln58_3745_fu_6651_p1) + $signed(sext_ln58_2298_fu_6451_p1));

assign add_ln58_2598_fu_6661_p2 = ($signed(sext_ln58_3730_fu_6583_p1) + $signed(sext_ln58_3741_fu_6633_p1));

assign add_ln58_2599_fu_6667_p2 = ($signed(sext_ln58_3721_fu_6527_p1) + $signed(sext_ln58_3744_fu_6641_p1));

assign add_ln58_2600_fu_6677_p2 = ($signed(sext_ln58_3746_fu_6673_p1) + $signed(add_ln58_2598_fu_6661_p2));

assign add_ln58_2601_fu_6687_p2 = ($signed(sext_ln58_3747_fu_6683_p1) + $signed(add_ln58_2597_fu_6655_p2));

assign add_ln58_2602_fu_6701_p2 = (sub_ln73_1069_fu_5679_p2 + mul_ln73_45_fu_195_p2);

assign add_ln58_2603_fu_7396_p2 = ($signed(sext_ln58_3757_fu_7393_p1) + $signed(sext_ln58_2302_fu_7289_p1));

assign add_ln58_2604_fu_7402_p2 = ($signed(sext_ln58_3736_fu_7320_p1) + $signed(sext_ln58_3738_fu_7349_p1));

assign add_ln58_2605_fu_7408_p2 = ($signed(sext_ln73_1444_reg_7936) + $signed(sext_ln58_3748_fu_7362_p1));

assign add_ln58_2606_fu_7417_p2 = ($signed(sext_ln58_3758_fu_7413_p1) + $signed(add_ln58_2604_fu_7402_p2));

assign add_ln58_2607_fu_7427_p2 = ($signed(sext_ln58_3759_fu_7423_p1) + $signed(add_ln58_2603_fu_7396_p2));

assign add_ln58_2608_fu_6707_p2 = (mul_ln73_43_fu_196_p2 + add_ln73_94_fu_6112_p2);

assign add_ln58_2609_fu_7464_p2 = ($signed(sext_ln58_3766_fu_7461_p1) + $signed(sext_ln58_2335_fu_7359_p1));

assign add_ln58_2610_fu_7498_p2 = ($signed(sext_ln58_3770_fu_7494_p1) + $signed(sub_ln58_656_fu_7474_p2));

assign add_ln58_2611_fu_7508_p2 = ($signed(sext_ln58_3771_fu_7504_p1) + $signed(add_ln58_2609_fu_7464_p2));

assign add_ln58_2612_fu_7522_p2 = ($signed(sext_ln58_3776_fu_7286_p1) + $signed(sext_ln58_3782_fu_7373_p1));

assign add_ln58_2613_fu_7532_p2 = ($signed(sext_ln58_3755_fu_7385_p1) + $signed(sext_ln58_3764_fu_7453_p1));

assign add_ln58_2614_fu_7542_p2 = ($signed(sext_ln58_3805_fu_7538_p1) + $signed(sext_ln58_3804_fu_7528_p1));

assign add_ln58_2615_fu_6713_p2 = ($signed(mul_ln73_47_fu_115_p2) + $signed(sext_ln58_3722_fu_6531_p1));

assign add_ln58_2616_fu_6723_p2 = ($signed(sext_ln58_3743_fu_6637_p1) + $signed(sext_ln58_3751_fu_6697_p1));

assign add_ln58_2617_fu_6733_p2 = ($signed(sext_ln58_3775_fu_6729_p1) + $signed(sext_ln58_3774_fu_6719_p1));

assign add_ln58_2618_fu_7551_p2 = ($signed(sext_ln58_3806_fu_7548_p1) + $signed(add_ln58_2614_fu_7542_p2));

assign add_ln58_2619_fu_6749_p2 = ($signed(sext_ln58_3728_fu_6579_p1) + $signed(sext_ln58_3739_fu_6629_p1));

assign add_ln58_2620_fu_6759_p2 = ($signed(sext_ln58_3778_fu_6755_p1) + $signed(sext_ln58_3777_fu_6745_p1));

assign add_ln58_2621_fu_6769_p2 = ($signed(sext_ln58_3749_fu_6693_p1) + $signed(sext_ln58_3715_fu_6497_p1));

assign add_ln58_2622_fu_6785_p2 = ($signed(sext_ln58_3780_fu_6781_p1) + $signed(add_ln58_2621_fu_6769_p2));

assign add_ln58_2623_fu_6795_p2 = ($signed(sext_ln58_3781_fu_6791_p1) + $signed(sext_ln58_3779_fu_6765_p1));

assign add_ln58_2624_fu_7564_p2 = ($signed(sext_ln58_3808_fu_7561_p1) + $signed(sext_ln58_3807_fu_7557_p1));

assign add_ln58_2625_fu_7586_p2 = (mul_ln73_44_fu_141_p2 + mul_ln73_48_fu_120_p2);

assign add_ln58_2626_fu_7596_p2 = ($signed(sext_ln58_3786_fu_7592_p1) + $signed(sext_ln58_2326_fu_7341_p1));

assign add_ln58_2627_fu_7602_p2 = ($signed(add_ln73_91_reg_7910) + $signed(sext_ln58_3750_fu_7365_p1));

assign add_ln58_2628_fu_7611_p2 = ($signed(sext_ln58_3761_fu_7441_p1) + $signed(sext_ln58_3785_fu_7582_p1));

assign add_ln58_2629_fu_7621_p2 = ($signed(sext_ln58_3788_fu_7617_p1) + $signed(sext_ln58_3787_fu_7607_p1));

assign add_ln58_2630_fu_7631_p2 = ($signed(sext_ln58_3789_fu_7627_p1) + $signed(add_ln58_2626_fu_7596_p2));

assign add_ln58_2631_fu_7645_p2 = ($signed(sext_ln58_2321_fu_7316_p1) + $signed(sext_ln58_2327_fu_7345_p1));

assign add_ln58_2632_fu_7651_p2 = ($signed(sext_ln58_3742_fu_7356_p1) + $signed(sext_ln58_3754_fu_7381_p1));

assign add_ln58_2633_fu_7661_p2 = ($signed(sext_ln58_3791_fu_7657_p1) + $signed(add_ln58_2631_fu_7645_p2));

assign add_ln58_2634_fu_7667_p2 = ($signed(sext_ln58_3762_fu_7445_p1) + $signed(sext_ln58_3790_fu_7641_p1));

assign add_ln58_2635_fu_7687_p2 = ($signed(sext_ln58_3793_fu_7683_p1) + $signed(add_ln58_2634_fu_7667_p2));

assign add_ln58_2636_fu_7697_p2 = ($signed(sext_ln58_3794_fu_7693_p1) + $signed(add_ln58_2633_fu_7661_p2));

assign add_ln58_2637_fu_7711_p2 = ($signed(sext_ln58_2355_fu_7433_p1) + $signed(sext_ln58_2378_fu_7707_p1));

assign add_ln58_2638_fu_7717_p2 = ($signed(sext_ln58_3772_fu_7518_p1) + $signed(sext_ln58_3783_fu_7574_p1));

assign add_ln58_2639_fu_7723_p2 = ($signed(add_ln58_2638_fu_7717_p2) + $signed(sext_ln58_3763_fu_7449_p1));

assign add_ln58_2640_fu_7733_p2 = ($signed(sext_ln58_3795_fu_7729_p1) + $signed(add_ln58_2637_fu_7711_p2));

assign add_ln58_2641_fu_7747_p2 = ($signed(sext_ln58_3729_fu_7295_p1) + $signed(sext_ln58_3736_fu_7320_p1));

assign add_ln58_2642_fu_7757_p2 = ($signed(sext_ln58_3797_fu_7753_p1) + $signed(sext_ln58_2313_fu_7292_p1));

assign add_ln58_2643_fu_7763_p2 = ($signed(sext_ln58_3752_fu_7369_p1) + $signed(sext_ln58_3753_fu_7377_p1));

assign add_ln58_2644_fu_7773_p2 = ($signed(sext_ln58_3798_fu_7769_p1) + $signed(sext_ln58_3765_fu_7457_p1));

assign add_ln58_2645_fu_7783_p2 = ($signed(sext_ln58_3799_fu_7779_p1) + $signed(add_ln58_2642_fu_7757_p2));

assign add_ln58_2646_fu_7789_p2 = ($signed(sext_ln58_3760_fu_7437_p1) + $signed(sext_ln58_3763_fu_7449_p1));

assign add_ln58_2647_fu_7795_p2 = ($signed(add_ln58_2646_fu_7789_p2) + $signed(sext_ln58_3756_fu_7389_p1));

assign add_ln58_2648_fu_7805_p2 = ($signed(sext_ln58_3784_fu_7578_p1) + $signed(sext_ln58_3740_fu_7353_p1));

assign add_ln58_2649_fu_7821_p2 = ($signed(sext_ln58_3801_fu_7817_p1) + $signed(add_ln58_2648_fu_7805_p2));

assign add_ln58_2650_fu_7831_p2 = ($signed(sext_ln58_3802_fu_7827_p1) + $signed(sext_ln58_3800_fu_7801_p1));

assign add_ln58_2651_fu_7841_p2 = ($signed(sext_ln58_3803_fu_7837_p1) + $signed(add_ln58_2645_fu_7783_p2));

assign add_ln58_fu_6127_p2 = (sub_ln73_1049_fu_5099_p2 + 11'd16);

assign add_ln73_83_fu_5231_p2 = ($signed(sext_ln73_1378_fu_5187_p1) + $signed(sext_ln73_1377_fu_5175_p1));

assign add_ln73_84_fu_5279_p2 = ($signed(sext_ln73_1383_fu_5257_p1) + $signed(sext_ln73_1384_fu_5275_p1));

assign add_ln73_85_fu_5327_p2 = ($signed(sext_ln73_1388_fu_5323_p1) + $signed(sext_ln73_1386_fu_5306_p1));

assign add_ln73_86_fu_5389_p2 = ($signed(sext_ln73_1392_fu_5385_p1) + $signed(sext_ln73_1390_fu_5361_p1));

assign add_ln73_87_fu_5617_p2 = ($signed(sext_ln73_1407_fu_5607_p1) + $signed(sext_ln73_1406_fu_5587_p1));

assign add_ln73_88_fu_5705_p2 = ($signed(sext_ln73_1413_fu_5701_p1) + $signed(sext_ln73_1412_fu_5689_p1));

assign add_ln73_89_fu_5777_p2 = ($signed(sext_ln73_1418_fu_5761_p1) + $signed(sext_ln73_1419_fu_5773_p1));

assign add_ln73_90_fu_5801_p2 = ($signed(sext_ln73_1420_fu_5797_p1) + $signed(sext_ln73_1417_fu_5749_p1));

assign add_ln73_91_fu_5963_p2 = ($signed(sext_ln73_1436_fu_5959_p1) + $signed(sext_ln73_1435_fu_5947_p1));

assign add_ln73_92_fu_5981_p2 = ($signed(sext_ln73_1436_fu_5959_p1) + $signed(sext_ln73_1437_fu_5977_p1));

assign add_ln73_93_fu_6013_p2 = ($signed(sext_ln73_1439_fu_6009_p1) + $signed(sext_ln73_1438_fu_5997_p1));

assign add_ln73_94_fu_6112_p2 = ($signed(sext_ln73_1463_fu_6108_p1) + $signed(sext_ln73_1462_fu_6095_p1));

assign add_ln73_95_cast_fu_5237_p1 = $signed(add_ln73_83_fu_5231_p2);

assign add_ln73_95_fu_7066_p2 = ($signed(sext_ln73_1464_fu_7062_p1) + $signed(sext_ln73_1461_fu_7052_p1));

assign add_ln73_fu_5141_p2 = ($signed(sext_ln73_1375_fu_5137_p1) + $signed(sext_ln73_1372_fu_5109_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign empty_fu_6261_p2 = ($signed(a_55_cast91_i_fu_6253_p1) + $signed(a_cast92_i_fu_6249_p1));

assign mul_ln73_39_fu_117_p1 = 13'd8181;

assign mul_ln73_40_fu_127_p1 = 14'd16362;

assign mul_ln73_41_fu_168_p1 = 13'd8181;

assign mul_ln73_42_fu_163_p1 = 13'd8179;

assign mul_ln73_43_fu_196_p1 = 13'd13;

assign mul_ln73_44_fu_141_p1 = 13'd8179;

assign mul_ln73_45_fu_195_p1 = 13'd13;

assign mul_ln73_46_fu_182_p0 = sext_ln73_1462_fu_6095_p1;

assign mul_ln73_46_fu_182_p1 = 13'd8179;

assign mul_ln73_47_fu_115_p1 = 13'd8181;

assign mul_ln73_48_fu_120_p1 = 13'd8181;

assign mul_ln73_fu_166_p1 = 14'd25;

assign p_cast_i_fu_6267_p1 = $signed(empty_fu_6261_p2);

assign sext_ln58_2268_fu_6153_p1 = $signed(add_ln58_2559_fu_6147_p2);

assign sext_ln58_2269_fu_6163_p1 = $signed(add_ln58_2560_fu_6157_p2);

assign sext_ln58_2270_fu_6173_p1 = $signed(add_ln58_2561_fu_6167_p2);

assign sext_ln58_2271_fu_6183_p1 = $signed(sub_ln58_fu_6177_p2);

assign sext_ln58_2272_fu_6193_p1 = $signed(add_ln58_2562_fu_6187_p2);

assign sext_ln58_2273_fu_6203_p1 = $signed(add_ln58_2563_fu_6197_p2);

assign sext_ln58_2274_fu_6207_p1 = $signed(add_ln73_84_fu_5279_p2);

assign sext_ln58_2275_fu_6227_p1 = $signed(add_ln58_2565_fu_6221_p2);

assign sext_ln58_2276_fu_6237_p1 = $signed(add_ln58_2566_fu_6231_p2);

assign sext_ln58_2278_fu_6245_p1 = $signed(mul_ln73_39_fu_117_p2);

assign sext_ln58_2281_fu_6305_p1 = $signed(sub_ln73_1058_fu_5351_p2);

assign sext_ln58_2283_fu_6315_p1 = $signed(sub_ln58_27_fu_6309_p2);

assign sext_ln58_2285_fu_7283_p1 = $signed(add_ln58_2570_reg_7963);

assign sext_ln58_2292_fu_6399_p1 = $signed(add_ln58_2574_fu_6393_p2);

assign sext_ln58_2296_fu_6415_p1 = $signed(sub_ln73_1063_fu_5516_p2);

assign sext_ln58_2298_fu_6451_p1 = $signed(add_ln58_2578_fu_6445_p2);

assign sext_ln58_2302_fu_7289_p1 = $signed(add_ln58_2582_reg_7973);

assign sext_ln58_2313_fu_7292_p1 = $signed(add_ln58_2586_reg_7983);

assign sext_ln58_2321_fu_7316_p1 = $signed(add_ln58_2592_fu_7310_p2);

assign sext_ln58_2325_fu_7323_p1 = $signed(mul_ln73_42_fu_163_p2);

assign sext_ln58_2326_fu_7341_p1 = $signed(add_ln58_2595_fu_7335_p2);

assign sext_ln58_2327_fu_7345_p1 = $signed(sub_ln73_1080_fu_6836_p2);

assign sext_ln58_2335_fu_7359_p1 = $signed(add_ln58_2601_reg_8003);

assign sext_ln58_2355_fu_7433_p1 = $signed(add_ln58_2607_fu_7427_p2);

assign sext_ln58_2366_fu_7514_p1 = $signed(add_ln58_2611_fu_7508_p2);

assign sext_ln58_2369_fu_7570_p1 = $signed(add_ln58_2624_fu_7564_p2);

assign sext_ln58_2375_fu_7637_p1 = $signed(add_ln58_2630_fu_7631_p2);

assign sext_ln58_2377_fu_7703_p1 = $signed(add_ln58_2636_fu_7697_p2);

assign sext_ln58_2378_fu_7707_p1 = $signed(sub_ln73_1108_fu_7277_p2);

assign sext_ln58_2379_fu_7739_p1 = $signed(add_ln58_2640_fu_7733_p2);

assign sext_ln58_3695_fu_6143_p1 = $signed(add_ln58_2558_fu_6137_p2);

assign sext_ln58_3696_fu_6217_p1 = $signed(add_ln58_2564_fu_6211_p2);

assign sext_ln58_3697_fu_6241_p1 = $signed(add_ln73_85_fu_5327_p2);

assign sext_ln58_3698_fu_6331_p1 = $signed(sub_ln58_653_fu_6325_p2);

assign sext_ln58_3699_fu_6341_p1 = $signed(add_ln73_86_fu_5389_p2);

assign sext_ln58_3700_fu_6285_p1 = $signed(tmp_fu_6277_p3);

assign sext_ln58_3701_fu_6295_p1 = $signed(add_ln58_2567_fu_6289_p2);

assign sext_ln58_3702_fu_6355_p1 = $signed(shl_ln73_673_fu_5395_p3);

assign sext_ln58_3703_fu_6359_p1 = $signed(sub_ln73_1059_fu_5428_p2);

assign sext_ln58_3704_fu_6369_p1 = shl_ln73_676_fu_5456_p3;

assign sext_ln58_3705_fu_6373_p1 = shl_ln73_676_fu_5456_p3;

assign sext_ln58_3706_fu_6389_p1 = $signed(add_ln58_2573_fu_6383_p2);

assign sext_ln58_3707_fu_6403_p1 = $signed(sub_ln73_1061_fu_5492_p2);

assign sext_ln58_3708_fu_6407_p1 = $signed(sub_ln73_1062_fu_5510_p2);

assign sext_ln58_3709_fu_6411_p1 = shl_ln73_678_fu_5480_p3;

assign sext_ln58_3710_fu_6419_p1 = $signed(sub_ln73_1064_fu_5559_p2);

assign sext_ln58_3711_fu_6441_p1 = $signed(add_ln58_2577_fu_6435_p2);

assign sext_ln58_3712_fu_6461_p1 = sub_ln73_1065_fu_5577_p2;

assign sext_ln58_3713_fu_6477_p1 = $signed(add_ln58_2580_fu_6471_p2);

assign sext_ln58_3714_fu_6487_p1 = $signed(add_ln58_2581_fu_6481_p2);

assign sext_ln58_3715_fu_6497_p1 = shl_ln73_682_fu_5565_p3;

assign sext_ln58_3716_fu_6501_p1 = $signed(shl_ln73_683_fu_5591_p3);

assign sext_ln58_3717_fu_6505_p1 = $signed(sub_ln58_28_fu_6455_p2);

assign sext_ln58_3718_fu_6515_p1 = $signed(sub_ln73_1066_fu_5611_p2);

assign sext_ln58_3719_fu_6519_p1 = $signed(add_ln73_87_fu_5617_p2);

assign sext_ln58_3720_fu_6523_p1 = $signed(sub_ln73_1068_fu_5649_p2);

assign sext_ln58_3721_fu_6527_p1 = $signed(add_ln73_88_fu_5705_p2);

assign sext_ln58_3722_fu_6531_p1 = $signed(sub_ln73_1070_fu_5735_p2);

assign sext_ln58_3723_fu_6535_p1 = shl_ln73_688_fu_5693_p3;

assign sext_ln58_3724_fu_6551_p1 = $signed(add_ln58_2584_fu_6545_p2);

assign sext_ln58_3725_fu_6561_p1 = $signed(add_ln58_2585_fu_6555_p2);

assign sext_ln58_3726_fu_6571_p1 = $signed(add_ln73_89_fu_5777_p2);

assign sext_ln58_3727_fu_6575_p1 = $signed(sub_ln73_1071_fu_5783_p2);

assign sext_ln58_3728_fu_6579_p1 = $signed(add_ln73_90_fu_5801_p2);

assign sext_ln58_3729_fu_7295_p1 = $signed(sub_ln73_1072_reg_7887);

assign sext_ln58_3730_fu_6583_p1 = $signed(sub_ln73_1073_fu_5837_p2);

assign sext_ln58_3731_fu_6587_p1 = $signed(sub_ln73_1074_fu_5855_p2);

assign sext_ln58_3732_fu_7298_p1 = $signed(add_ln58_2587_reg_7988);

assign sext_ln58_3733_fu_6603_p1 = $signed(add_ln58_2589_fu_6597_p2);

assign sext_ln58_3734_fu_6613_p1 = $signed(add_ln58_2590_fu_6607_p2);

assign sext_ln58_3735_fu_7307_p1 = $signed(add_ln58_2591_reg_7993);

assign sext_ln58_3736_fu_7320_p1 = $signed(sub_ln73_1077_reg_7892);

assign sext_ln58_3737_fu_7332_p1 = $signed(add_ln58_2594_reg_7998);

assign sext_ln58_3738_fu_7349_p1 = $signed(sub_ln73_1081_fu_6842_p2);

assign sext_ln58_3739_fu_6629_p1 = $signed(sub_ln73_1082_fu_5937_p2);

assign sext_ln58_3740_fu_7353_p1 = shl_ln73_698_reg_7905;

assign sext_ln58_3741_fu_6633_p1 = add_ln73_91_fu_5963_p2;

assign sext_ln58_3742_fu_7356_p1 = $signed(add_ln73_92_reg_7915);

assign sext_ln58_3743_fu_6637_p1 = $signed(sub_ln73_1083_fu_5987_p2);

assign sext_ln58_3744_fu_6641_p1 = $signed(add_ln73_93_fu_6013_p2);

assign sext_ln58_3745_fu_6651_p1 = $signed(add_ln58_2596_fu_6645_p2);

assign sext_ln58_3746_fu_6673_p1 = $signed(add_ln58_2599_fu_6667_p2);

assign sext_ln58_3747_fu_6683_p1 = $signed(add_ln58_2600_fu_6677_p2);

assign sext_ln58_3748_fu_7362_p1 = shl_ln73_703_reg_7925;

assign sext_ln58_3749_fu_6693_p1 = $signed(sub_ln73_1084_fu_6019_p2);

assign sext_ln58_3750_fu_7365_p1 = $signed(sub_ln73_1085_fu_6873_p2);

assign sext_ln58_3751_fu_6697_p1 = $signed(sub_ln73_1087_fu_6064_p2);

assign sext_ln58_3752_fu_7369_p1 = $signed(sub_ln73_1088_fu_6879_p2);

assign sext_ln58_3753_fu_7377_p1 = $signed(sub_ln73_1090_fu_6943_p2);

assign sext_ln58_3754_fu_7381_p1 = $signed(sub_ln73_1091_fu_6986_p2);

assign sext_ln58_3755_fu_7385_p1 = $signed(sub_ln73_1092_fu_7020_p2);

assign sext_ln58_3756_fu_7389_p1 = $signed(sub_ln73_1093_fu_7026_p2);

assign sext_ln58_3757_fu_7393_p1 = $signed(add_ln58_2602_reg_8008);

assign sext_ln58_3758_fu_7413_p1 = $signed(add_ln58_2605_fu_7408_p2);

assign sext_ln58_3759_fu_7423_p1 = $signed(add_ln58_2606_fu_7417_p2);

assign sext_ln58_3760_fu_7437_p1 = $signed(sub_ln73_1094_fu_7046_p2);

assign sext_ln58_3761_fu_7441_p1 = $signed(add_ln73_95_fu_7066_p2);

assign sext_ln58_3762_fu_7445_p1 = $signed(sub_ln73_1095_fu_7094_p2);

assign sext_ln58_3763_fu_7449_p1 = $signed(sub_ln73_1096_fu_7100_p2);

assign sext_ln58_3764_fu_7453_p1 = $signed(mul_ln73_46_reg_3790);

assign sext_ln58_3765_fu_7457_p1 = $signed(sub_ln73_1097_fu_7131_p2);

assign sext_ln58_3766_fu_7461_p1 = $signed(add_ln58_2608_reg_8013);

assign sext_ln58_3767_fu_7470_p1 = shl_ln73_712_fu_6962_p3;

assign sext_ln58_3768_fu_7480_p1 = shl_ln73_716_fu_7035_p3;

assign sext_ln58_3769_fu_7484_p1 = $signed(shl_ln73_708_fu_6893_p3);

assign sext_ln58_3770_fu_7494_p1 = $signed(sub_ln58_657_fu_7488_p2);

assign sext_ln58_3771_fu_7504_p1 = $signed(add_ln58_2610_fu_7498_p2);

assign sext_ln58_3772_fu_7518_p1 = $signed(sub_ln73_1099_fu_7154_p2);

assign sext_ln58_3773_fu_6345_p1 = shl_ln73_671_fu_5365_p3;

assign sext_ln58_3774_fu_6719_p1 = $signed(add_ln58_2615_fu_6713_p2);

assign sext_ln58_3775_fu_6729_p1 = $signed(add_ln58_2616_fu_6723_p2);

assign sext_ln58_3776_fu_7286_p1 = $signed(sub_ln58_654_reg_7968);

assign sext_ln58_3777_fu_6745_p1 = $signed(sub_ln58_658_fu_6739_p2);

assign sext_ln58_3778_fu_6755_p1 = $signed(add_ln58_2619_fu_6749_p2);

assign sext_ln58_3779_fu_6765_p1 = $signed(add_ln58_2620_fu_6759_p2);

assign sext_ln58_3780_fu_6781_p1 = $signed(sub_ln58_659_fu_6775_p2);

assign sext_ln58_3781_fu_6791_p1 = $signed(add_ln58_2622_fu_6785_p2);

assign sext_ln58_3782_fu_7373_p1 = $signed(sub_ln73_1089_fu_6925_p2);

assign sext_ln58_3783_fu_7574_p1 = $signed(sub_ln73_1101_fu_7191_p2);

assign sext_ln58_3784_fu_7578_p1 = $signed(sub_ln73_1103_fu_7203_p2);

assign sext_ln58_3785_fu_7582_p1 = $signed(sub_ln73_1105_fu_7235_p2);

assign sext_ln58_3786_fu_7592_p1 = $signed(add_ln58_2625_fu_7586_p2);

assign sext_ln58_3787_fu_7607_p1 = $signed(add_ln58_2627_fu_7602_p2);

assign sext_ln58_3788_fu_7617_p1 = $signed(add_ln58_2628_fu_7611_p2);

assign sext_ln58_3789_fu_7627_p1 = $signed(add_ln58_2629_fu_7621_p2);

assign sext_ln58_3790_fu_7641_p1 = $signed(sub_ln73_1106_fu_7265_p2);

assign sext_ln58_3791_fu_7657_p1 = $signed(add_ln58_2632_fu_7651_p2);

assign sext_ln58_3792_fu_7673_p1 = $signed(sub_ln73_1100_fu_7185_p2);

assign sext_ln58_3793_fu_7683_p1 = $signed(sub_ln58_660_fu_7677_p2);

assign sext_ln58_3794_fu_7693_p1 = $signed(add_ln58_2635_fu_7687_p2);

assign sext_ln58_3795_fu_7729_p1 = $signed(add_ln58_2639_fu_7723_p2);

assign sext_ln58_3796_fu_7743_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;

assign sext_ln58_3796_fu_7743_p1 = sext_ln58_3796_fu_7743_p0;

assign sext_ln58_3797_fu_7753_p1 = $signed(add_ln58_2641_fu_7747_p2);

assign sext_ln58_3798_fu_7769_p1 = $signed(add_ln58_2643_fu_7763_p2);

assign sext_ln58_3799_fu_7779_p1 = $signed(add_ln58_2644_fu_7773_p2);

assign sext_ln58_3800_fu_7801_p1 = $signed(add_ln58_2647_fu_7795_p2);

assign sext_ln58_3801_fu_7817_p1 = $signed(sub_ln58_661_fu_7811_p2);

assign sext_ln58_3802_fu_7827_p1 = $signed(add_ln58_2649_fu_7821_p2);

assign sext_ln58_3803_fu_7837_p1 = $signed(add_ln58_2650_fu_7831_p2);

assign sext_ln58_3804_fu_7528_p1 = $signed(add_ln58_2612_fu_7522_p2);

assign sext_ln58_3805_fu_7538_p1 = $signed(add_ln58_2613_fu_7532_p2);

assign sext_ln58_3806_fu_7548_p1 = $signed(add_ln58_2617_reg_8018);

assign sext_ln58_3807_fu_7557_p1 = $signed(add_ln58_2618_fu_7551_p2);

assign sext_ln58_3808_fu_7561_p1 = $signed(add_ln58_2623_reg_8023);

assign sext_ln58_fu_6133_p1 = $signed(add_ln58_fu_6127_p2);

assign sext_ln68_fu_7847_p1 = $signed(add_ln58_2651_fu_7841_p2);

assign sext_ln73_1369_fu_5059_p1 = $signed(shl_ln_fu_5051_p3);

assign sext_ln73_1370_fu_5077_p1 = $signed(shl_ln73_s_fu_5069_p3);

assign sext_ln73_1371_fu_5095_p1 = $signed(shl_ln73_660_fu_5087_p3);

assign sext_ln73_1372_fu_5109_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign sext_ln73_1372_fu_5109_p1 = sext_ln73_1372_fu_5109_p0;

assign sext_ln73_1373_fu_5121_p1 = shl_ln73_661_fu_5113_p3;

assign sext_ln73_1374_fu_5125_p1 = shl_ln73_661_fu_5113_p3;

assign sext_ln73_1375_fu_5137_p1 = $signed(shl_ln73_662_fu_5129_p3);

assign sext_ln73_1376_fu_5155_p1 = $signed(shl_ln73_663_fu_5147_p3);

assign sext_ln73_1377_fu_5175_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign sext_ln73_1377_fu_5175_p1 = sext_ln73_1377_fu_5175_p0;

assign sext_ln73_1378_fu_5187_p1 = $signed(shl_ln73_664_fu_5179_p3);

assign sext_ln73_1379_fu_5205_p1 = $signed(shl_ln73_665_fu_5197_p3);

assign sext_ln73_1380_fu_5217_p1 = $signed(shl_ln73_666_fu_5209_p3);

assign sext_ln73_1381_fu_5227_p1 = $signed(sub_ln73_1053_fu_5221_p2);

assign sext_ln73_1382_fu_5245_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign sext_ln73_1382_fu_5245_p1 = sext_ln73_1382_fu_5245_p0;

assign sext_ln73_1383_fu_5257_p1 = $signed(shl_ln73_667_fu_5249_p3);

assign sext_ln73_1384_fu_5275_p1 = $signed(shl_ln73_668_fu_5267_p3);

assign sext_ln73_1386_fu_5306_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;

assign sext_ln73_1386_fu_5306_p1 = sext_ln73_1386_fu_5306_p0;

assign sext_ln73_1388_fu_5323_p1 = $signed(shl_ln73_669_fu_5315_p3);

assign sext_ln73_1389_fu_5341_p1 = $signed(shl_ln73_670_fu_5333_p3);

assign sext_ln73_1390_fu_5361_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign sext_ln73_1390_fu_5361_p1 = sext_ln73_1390_fu_5361_p0;

assign sext_ln73_1391_fu_5373_p1 = shl_ln73_671_fu_5365_p3;

assign sext_ln73_1392_fu_5385_p1 = $signed(shl_ln73_672_fu_5377_p3);

assign sext_ln73_1394_fu_5412_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign sext_ln73_1394_fu_5412_p1 = sext_ln73_1394_fu_5412_p0;

assign sext_ln73_1395_fu_5424_p1 = $signed(shl_ln73_674_fu_5416_p3);

assign sext_ln73_1396_fu_5442_p1 = $signed(shl_ln73_675_fu_5434_p3);

assign sext_ln73_1397_fu_5452_p1 = $signed(sub_ln73_1060_fu_5446_p2);

assign sext_ln73_1398_fu_5476_p1 = $signed(shl_ln73_677_fu_5468_p3);

assign sext_ln73_1399_fu_5488_p1 = shl_ln73_678_fu_5480_p3;

assign sext_ln73_1400_fu_5506_p1 = $signed(shl_ln73_679_fu_5498_p3);

assign sext_ln73_1401_fu_5526_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign sext_ln73_1401_fu_5526_p1 = sext_ln73_1401_fu_5526_p0;

assign sext_ln73_1403_fu_5543_p1 = $signed(shl_ln73_680_fu_5535_p3);

assign sext_ln73_1404_fu_5555_p1 = $signed(shl_ln73_681_fu_5547_p3);

assign sext_ln73_1405_fu_5573_p1 = shl_ln73_682_fu_5565_p3;

assign sext_ln73_1406_fu_5587_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign sext_ln73_1406_fu_5587_p1 = sext_ln73_1406_fu_5587_p0;

assign sext_ln73_1407_fu_5607_p1 = $signed(shl_ln73_684_fu_5599_p3);

assign sext_ln73_1408_fu_5627_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14;

assign sext_ln73_1408_fu_5627_p1 = sext_ln73_1408_fu_5627_p0;

assign sext_ln73_1409_fu_5639_p1 = $signed(shl_ln73_685_fu_5631_p3);

assign sext_ln73_1410_fu_5663_p1 = $signed(shl_ln73_686_fu_5655_p3);

assign sext_ln73_1411_fu_5675_p1 = $signed(shl_ln73_687_fu_5667_p3);

assign sext_ln73_1412_fu_5689_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13;

assign sext_ln73_1412_fu_5689_p1 = sext_ln73_1412_fu_5689_p0;

assign sext_ln73_1413_fu_5701_p1 = shl_ln73_688_fu_5693_p3;

assign sext_ln73_1414_fu_5719_p1 = $signed(shl_ln73_689_fu_5711_p3);

assign sext_ln73_1415_fu_5731_p1 = $signed(shl_ln73_690_fu_5723_p3);

assign sext_ln73_1416_fu_5745_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;

assign sext_ln73_1416_fu_5745_p1 = sext_ln73_1416_fu_5745_p0;

assign sext_ln73_1417_fu_5749_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;

assign sext_ln73_1417_fu_5749_p1 = sext_ln73_1417_fu_5749_p0;

assign sext_ln73_1418_fu_5761_p1 = $signed(shl_ln73_691_fu_5753_p3);

assign sext_ln73_1419_fu_5773_p1 = $signed(shl_ln73_692_fu_5765_p3);

assign sext_ln73_1420_fu_5797_p1 = $signed(shl_ln73_693_fu_5789_p3);

assign sext_ln73_1421_fu_5817_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;

assign sext_ln73_1421_fu_5817_p1 = sext_ln73_1421_fu_5817_p0;

assign sext_ln73_1422_fu_5821_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;

assign sext_ln73_1422_fu_5821_p1 = sext_ln73_1422_fu_5821_p0;

assign sext_ln73_1423_fu_5833_p1 = $signed(shl_ln73_694_fu_5825_p3);

assign sext_ln73_1424_fu_5851_p1 = $signed(shl_ln73_695_fu_5843_p3);

assign sext_ln73_1425_fu_5875_p1 = shl_ln73_696_fu_5867_p3;

assign sext_ln73_1426_fu_5879_p1 = shl_ln73_696_fu_5867_p3;

assign sext_ln73_1427_fu_5899_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10;

assign sext_ln73_1427_fu_5899_p1 = sext_ln73_1427_fu_5899_p0;

assign sext_ln73_1429_fu_6805_p1 = a_25_reg_7897;

assign sext_ln73_1430_fu_5911_p1 = $signed(shl_ln73_697_fu_5903_p3);

assign sext_ln73_1431_fu_5923_p1 = shl_ln73_698_fu_5915_p3;

assign sext_ln73_1432_fu_6815_p1 = $signed(shl_ln73_699_fu_6808_p3);

assign sext_ln73_1433_fu_6832_p1 = $signed(shl_ln73_700_fu_6825_p3);

assign sext_ln73_1434_fu_5933_p1 = shl_ln73_698_fu_5915_p3;

assign sext_ln73_1435_fu_5947_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9;

assign sext_ln73_1435_fu_5947_p1 = sext_ln73_1435_fu_5947_p0;

assign sext_ln73_1436_fu_5959_p1 = $signed(shl_ln73_701_fu_5951_p3);

assign sext_ln73_1437_fu_5977_p1 = $signed(shl_ln73_702_fu_5969_p3);

assign sext_ln73_1438_fu_5997_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8;

assign sext_ln73_1438_fu_5997_p1 = sext_ln73_1438_fu_5997_p0;

assign sext_ln73_1439_fu_6009_p1 = shl_ln73_703_fu_6001_p3;

assign sext_ln73_1440_fu_6855_p1 = $signed(shl_ln73_704_fu_6848_p3);

assign sext_ln73_1441_fu_6859_p1 = a_28_reg_7930;

assign sext_ln73_1443_fu_6869_p1 = $signed(shl_ln73_705_fu_6862_p3);

assign sext_ln73_1444_fu_6042_p1 = $signed(shl_ln73_706_fu_6034_p3);

assign sext_ln73_1445_fu_6060_p1 = $signed(shl_ln73_707_fu_6052_p3);

assign sext_ln73_1446_fu_6889_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;

assign sext_ln73_1446_fu_6889_p1 = sext_ln73_1446_fu_6889_p0;

assign sext_ln73_1447_fu_6909_p1 = $signed(shl_ln73_709_fu_6901_p3);

assign sext_ln73_1448_fu_6921_p1 = $signed(shl_ln73_710_fu_6913_p3);

assign sext_ln73_1449_fu_6939_p1 = $signed(shl_ln73_711_fu_6931_p3);

assign sext_ln73_1451_fu_6958_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;

assign sext_ln73_1451_fu_6958_p1 = sext_ln73_1451_fu_6958_p0;

assign sext_ln73_1452_fu_6970_p1 = shl_ln73_712_fu_6962_p3;

assign sext_ln73_1453_fu_6982_p1 = $signed(shl_ln73_713_fu_6974_p3);

assign sext_ln73_1454_fu_7000_p1 = $signed(shl_ln73_714_fu_6992_p3);

assign sext_ln73_1455_fu_7012_p1 = shl_ln73_715_fu_7004_p3;

assign sext_ln73_1456_fu_7016_p1 = shl_ln73_715_fu_7004_p3;

assign sext_ln73_1457_fu_7032_p1 = a_31_reg_7941;

assign sext_ln73_1459_fu_7042_p1 = shl_ln73_716_fu_7035_p3;

assign sext_ln73_1460_fu_6087_p1 = $signed(shl_ln73_717_fu_6079_p3);

assign sext_ln73_1461_fu_7052_p1 = a_32_reg_7947;

assign sext_ln73_1462_fu_6095_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_3;

assign sext_ln73_1462_fu_6095_p1 = sext_ln73_1462_fu_6095_p0;

assign sext_ln73_1463_fu_6108_p1 = $signed(shl_ln73_718_fu_6100_p3);

assign sext_ln73_1464_fu_7062_p1 = $signed(shl_ln73_719_fu_7055_p3);

assign sext_ln73_1465_fu_7079_p1 = $signed(shl_ln73_720_fu_7072_p3);

assign sext_ln73_1466_fu_7090_p1 = $signed(shl_ln73_721_fu_7083_p3);

assign sext_ln73_1468_fu_7106_p1 = a_33_reg_7955;

assign sext_ln73_1469_fu_7116_p1 = $signed(shl_ln73_722_fu_7109_p3);

assign sext_ln73_1470_fu_7127_p1 = $signed(shl_ln73_723_fu_7120_p3);

assign sext_ln73_1471_fu_7144_p1 = $signed(shl_ln73_724_fu_7137_p3);

assign sext_ln73_1472_fu_7164_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_1;

assign sext_ln73_1472_fu_7164_p1 = sext_ln73_1472_fu_7164_p0;

assign sext_ln73_1474_fu_7181_p1 = $signed(shl_ln73_725_fu_7173_p3);

assign sext_ln73_1475_fu_7213_p0 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;

assign sext_ln73_1475_fu_7213_p1 = sext_ln73_1475_fu_7213_p0;

assign sext_ln73_1476_fu_7225_p1 = $signed(shl_ln73_726_fu_7217_p3);

assign sext_ln73_1477_fu_7249_p1 = $signed(shl_ln73_727_fu_7241_p3);

assign sext_ln73_1478_fu_7261_p1 = $signed(shl_ln73_728_fu_7253_p3);

assign sext_ln73_fu_5047_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;

assign sext_ln73_fu_5047_p1 = sext_ln73_fu_5047_p0;

assign shl_ln73_660_fu_5087_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;

assign shl_ln73_660_fu_5087_p3 = {{shl_ln73_660_fu_5087_p1}, {2'd0}};

assign shl_ln73_661_fu_5113_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign shl_ln73_661_fu_5113_p3 = {{shl_ln73_661_fu_5113_p1}, {1'd0}};

assign shl_ln73_662_fu_5129_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign shl_ln73_662_fu_5129_p3 = {{shl_ln73_662_fu_5129_p1}, {2'd0}};

assign shl_ln73_663_fu_5147_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign shl_ln73_663_fu_5147_p3 = {{shl_ln73_663_fu_5147_p1}, {3'd0}};

assign shl_ln73_664_fu_5179_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign shl_ln73_664_fu_5179_p3 = {{shl_ln73_664_fu_5179_p1}, {2'd0}};

assign shl_ln73_665_fu_5197_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign shl_ln73_665_fu_5197_p3 = {{shl_ln73_665_fu_5197_p1}, {3'd0}};

assign shl_ln73_666_fu_5209_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign shl_ln73_666_fu_5209_p3 = {{shl_ln73_666_fu_5209_p1}, {1'd0}};

assign shl_ln73_667_fu_5249_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign shl_ln73_667_fu_5249_p3 = {{shl_ln73_667_fu_5249_p1}, {3'd0}};

assign shl_ln73_668_fu_5267_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign shl_ln73_668_fu_5267_p3 = {{shl_ln73_668_fu_5267_p1}, {1'd0}};

assign shl_ln73_669_fu_5315_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;

assign shl_ln73_669_fu_5315_p3 = {{shl_ln73_669_fu_5315_p1}, {2'd0}};

assign shl_ln73_670_fu_5333_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;

assign shl_ln73_670_fu_5333_p3 = {{shl_ln73_670_fu_5333_p1}, {3'd0}};

assign shl_ln73_671_fu_5365_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign shl_ln73_671_fu_5365_p3 = {{shl_ln73_671_fu_5365_p1}, {2'd0}};

assign shl_ln73_672_fu_5377_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign shl_ln73_672_fu_5377_p3 = {{shl_ln73_672_fu_5377_p1}, {3'd0}};

assign shl_ln73_673_fu_5395_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign shl_ln73_673_fu_5395_p3 = {{shl_ln73_673_fu_5395_p1}, {1'd0}};

assign shl_ln73_674_fu_5416_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign shl_ln73_674_fu_5416_p3 = {{shl_ln73_674_fu_5416_p1}, {3'd0}};

assign shl_ln73_675_fu_5434_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign shl_ln73_675_fu_5434_p3 = {{shl_ln73_675_fu_5434_p1}, {1'd0}};

assign shl_ln73_676_fu_5456_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign shl_ln73_676_fu_5456_p3 = {{shl_ln73_676_fu_5456_p1}, {2'd0}};

assign shl_ln73_677_fu_5468_p3 = {{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2}, {3'd0}};

assign shl_ln73_678_fu_5480_p3 = {{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2}, {1'd0}};

assign shl_ln73_679_fu_5498_p3 = {{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2}, {4'd0}};

assign shl_ln73_680_fu_5535_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign shl_ln73_680_fu_5535_p3 = {{shl_ln73_680_fu_5535_p1}, {3'd0}};

assign shl_ln73_681_fu_5547_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign shl_ln73_681_fu_5547_p3 = {{shl_ln73_681_fu_5547_p1}, {1'd0}};

assign shl_ln73_682_fu_5565_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign shl_ln73_682_fu_5565_p3 = {{shl_ln73_682_fu_5565_p1}, {2'd0}};

assign shl_ln73_683_fu_5591_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign shl_ln73_683_fu_5591_p3 = {{shl_ln73_683_fu_5591_p1}, {3'd0}};

assign shl_ln73_684_fu_5599_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign shl_ln73_684_fu_5599_p3 = {{shl_ln73_684_fu_5599_p1}, {2'd0}};

assign shl_ln73_685_fu_5631_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14;

assign shl_ln73_685_fu_5631_p3 = {{shl_ln73_685_fu_5631_p1}, {2'd0}};

assign shl_ln73_686_fu_5655_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14;

assign shl_ln73_686_fu_5655_p3 = {{shl_ln73_686_fu_5655_p1}, {4'd0}};

assign shl_ln73_687_fu_5667_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_14;

assign shl_ln73_687_fu_5667_p3 = {{shl_ln73_687_fu_5667_p1}, {1'd0}};

assign shl_ln73_688_fu_5693_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13;

assign shl_ln73_688_fu_5693_p3 = {{shl_ln73_688_fu_5693_p1}, {2'd0}};

assign shl_ln73_689_fu_5711_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13;

assign shl_ln73_689_fu_5711_p3 = {{shl_ln73_689_fu_5711_p1}, {3'd0}};

assign shl_ln73_690_fu_5723_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13;

assign shl_ln73_690_fu_5723_p3 = {{shl_ln73_690_fu_5723_p1}, {1'd0}};

assign shl_ln73_691_fu_5753_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;

assign shl_ln73_691_fu_5753_p3 = {{shl_ln73_691_fu_5753_p1}, {3'd0}};

assign shl_ln73_692_fu_5765_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;

assign shl_ln73_692_fu_5765_p3 = {{shl_ln73_692_fu_5765_p1}, {1'd0}};

assign shl_ln73_693_fu_5789_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12;

assign shl_ln73_693_fu_5789_p3 = {{shl_ln73_693_fu_5789_p1}, {2'd0}};

assign shl_ln73_694_fu_5825_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;

assign shl_ln73_694_fu_5825_p3 = {{shl_ln73_694_fu_5825_p1}, {3'd0}};

assign shl_ln73_695_fu_5843_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;

assign shl_ln73_695_fu_5843_p3 = {{shl_ln73_695_fu_5843_p1}, {2'd0}};

assign shl_ln73_696_fu_5867_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11;

assign shl_ln73_696_fu_5867_p3 = {{shl_ln73_696_fu_5867_p1}, {1'd0}};

assign shl_ln73_697_fu_5903_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10;

assign shl_ln73_697_fu_5903_p3 = {{shl_ln73_697_fu_5903_p1}, {4'd0}};

assign shl_ln73_698_fu_5915_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10;

assign shl_ln73_698_fu_5915_p3 = {{shl_ln73_698_fu_5915_p1}, {2'd0}};

assign shl_ln73_699_fu_6808_p3 = {{a_25_reg_7897}, {3'd0}};

assign shl_ln73_700_fu_6825_p3 = {{a_25_reg_7897}, {1'd0}};

assign shl_ln73_701_fu_5951_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9;

assign shl_ln73_701_fu_5951_p3 = {{shl_ln73_701_fu_5951_p1}, {3'd0}};

assign shl_ln73_702_fu_5969_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9;

assign shl_ln73_702_fu_5969_p3 = {{shl_ln73_702_fu_5969_p1}, {1'd0}};

assign shl_ln73_703_fu_6001_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8;

assign shl_ln73_703_fu_6001_p3 = {{shl_ln73_703_fu_6001_p1}, {2'd0}};

assign shl_ln73_704_fu_6848_p3 = {{a_27_reg_7920}, {1'd0}};

assign shl_ln73_705_fu_6862_p3 = {{a_28_reg_7930}, {2'd0}};

assign shl_ln73_706_fu_6034_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7;

assign shl_ln73_706_fu_6034_p3 = {{shl_ln73_706_fu_6034_p1}, {3'd0}};

assign shl_ln73_707_fu_6052_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_7;

assign shl_ln73_707_fu_6052_p3 = {{shl_ln73_707_fu_6052_p1}, {1'd0}};

assign shl_ln73_708_fu_6893_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;

assign shl_ln73_708_fu_6893_p3 = {{shl_ln73_708_fu_6893_p1}, {3'd0}};

assign shl_ln73_709_fu_6901_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;

assign shl_ln73_709_fu_6901_p3 = {{shl_ln73_709_fu_6901_p1}, {4'd0}};

assign shl_ln73_710_fu_6913_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;

assign shl_ln73_710_fu_6913_p3 = {{shl_ln73_710_fu_6913_p1}, {1'd0}};

assign shl_ln73_711_fu_6931_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_6;

assign shl_ln73_711_fu_6931_p3 = {{shl_ln73_711_fu_6931_p1}, {2'd0}};

assign shl_ln73_712_fu_6962_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;

assign shl_ln73_712_fu_6962_p3 = {{shl_ln73_712_fu_6962_p1}, {3'd0}};

assign shl_ln73_713_fu_6974_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;

assign shl_ln73_713_fu_6974_p3 = {{shl_ln73_713_fu_6974_p1}, {1'd0}};

assign shl_ln73_714_fu_6992_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;

assign shl_ln73_714_fu_6992_p3 = {{shl_ln73_714_fu_6992_p1}, {4'd0}};

assign shl_ln73_715_fu_7004_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_5;

assign shl_ln73_715_fu_7004_p3 = {{shl_ln73_715_fu_7004_p1}, {2'd0}};

assign shl_ln73_716_fu_7035_p3 = {{a_31_reg_7941}, {2'd0}};

assign shl_ln73_717_fu_6079_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_4;

assign shl_ln73_717_fu_6079_p3 = {{shl_ln73_717_fu_6079_p1}, {3'd0}};

assign shl_ln73_718_fu_6100_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_3;

assign shl_ln73_718_fu_6100_p3 = {{shl_ln73_718_fu_6100_p1}, {4'd0}};

assign shl_ln73_719_fu_7055_p3 = {{a_32_reg_7947}, {2'd0}};

assign shl_ln73_720_fu_7072_p3 = {{a_32_reg_7947}, {3'd0}};

assign shl_ln73_721_fu_7083_p3 = {{a_32_reg_7947}, {1'd0}};

assign shl_ln73_722_fu_7109_p3 = {{a_33_reg_7955}, {3'd0}};

assign shl_ln73_723_fu_7120_p3 = {{a_33_reg_7955}, {1'd0}};

assign shl_ln73_724_fu_7137_p3 = {{a_33_reg_7955}, {2'd0}};

assign shl_ln73_725_fu_7173_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_1;

assign shl_ln73_725_fu_7173_p3 = {{shl_ln73_725_fu_7173_p1}, {2'd0}};

assign shl_ln73_726_fu_7217_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;

assign shl_ln73_726_fu_7217_p3 = {{shl_ln73_726_fu_7217_p1}, {2'd0}};

assign shl_ln73_727_fu_7241_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;

assign shl_ln73_727_fu_7241_p3 = {{shl_ln73_727_fu_7241_p1}, {3'd0}};

assign shl_ln73_728_fu_7253_p1 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a;

assign shl_ln73_728_fu_7253_p3 = {{shl_ln73_728_fu_7253_p1}, {1'd0}};

assign shl_ln73_s_fu_5069_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;

assign shl_ln73_s_fu_5069_p3 = {{shl_ln73_s_fu_5069_p1}, {1'd0}};

assign shl_ln_fu_5051_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;

assign shl_ln_fu_5051_p3 = {{shl_ln_fu_5051_p1}, {3'd0}};

assign sub_ln58_27_fu_6309_p2 = ($signed(sext_ln58_2271_fu_6183_p1) - $signed(sext_ln73_1391_fu_5373_p1));

assign sub_ln58_28_fu_6455_p2 = ($signed(add_ln58_2571_fu_6363_p2) - $signed(sext_ln73_1405_fu_5573_p1));

assign sub_ln58_653_fu_6325_p2 = ($signed(sext_ln58_3697_fu_6241_p1) - $signed(sext_ln73_1392_fu_5385_p1));

assign sub_ln58_654_fu_6349_p2 = ($signed(add_ln58_2568_fu_6299_p2) - $signed(sext_ln58_3773_fu_6345_p1));

assign sub_ln58_655_fu_6509_p2 = ($signed(sext_ln58_3717_fu_6505_p1) - $signed(sext_ln58_3716_fu_6501_p1));

assign sub_ln58_656_fu_7474_p2 = ($signed(sext_ln58_3765_fu_7457_p1) - $signed(sext_ln58_3767_fu_7470_p1));

assign sub_ln58_657_fu_7488_p2 = ($signed(sext_ln58_3769_fu_7484_p1) - $signed(sext_ln58_3768_fu_7480_p1));

assign sub_ln58_658_fu_6739_p2 = ($signed(sext_ln58_3718_fu_6515_p1) - $signed(sext_ln73_1460_fu_6087_p1));

assign sub_ln58_659_fu_6775_p2 = ($signed(sext_ln58_3709_fu_6411_p1) - $signed(sext_ln73_1425_fu_5875_p1));

assign sub_ln58_660_fu_7677_p2 = ($signed(sext_ln58_3792_fu_7673_p1) - $signed(sext_ln58_3748_fu_7362_p1));

assign sub_ln58_661_fu_7811_p2 = ($signed(sext_ln58_3796_fu_7743_p1) - $signed(sext_ln73_1440_fu_6855_p1));

assign sub_ln58_fu_6177_p2 = ($signed(sub_ln73_1052_fu_5191_p2) - $signed(sext_ln73_1373_fu_5121_p1));

assign sub_ln73_1048_fu_5081_p2 = ($signed(sub_ln73_fu_5063_p2) - $signed(sext_ln73_1370_fu_5077_p1));

assign sub_ln73_1049_fu_5099_p2 = ($signed(sext_ln73_1371_fu_5095_p1) - $signed(sext_ln73_fu_5047_p1));

assign sub_ln73_1050_fu_5159_p2 = ($signed(sext_ln73_1376_fu_5155_p1) - $signed(sext_ln73_1374_fu_5125_p1));

assign sub_ln73_1051_fu_5165_p2 = ($signed(sext_ln73_1372_fu_5109_p1) - $signed(sext_ln73_1375_fu_5137_p1));

assign sub_ln73_1052_fu_5191_p2 = ($signed(sext_ln73_1378_fu_5187_p1) - $signed(sext_ln73_1377_fu_5175_p1));

assign sub_ln73_1053_fu_5221_p2 = ($signed(sext_ln73_1379_fu_5205_p1) - $signed(sext_ln73_1380_fu_5217_p1));

assign sub_ln73_1054_fu_5261_p2 = ($signed(sext_ln73_1383_fu_5257_p1) - $signed(sext_ln73_1382_fu_5245_p1));

assign sub_ln73_1055_fu_5285_p2 = ($signed(12'd0) - $signed(sext_ln73_1383_fu_5257_p1));

assign sub_ln73_1056_fu_5291_p2 = ($signed(sub_ln73_1055_fu_5285_p2) - $signed(sext_ln73_1384_fu_5275_p1));

assign sub_ln73_1057_fu_5345_p2 = ($signed(11'd0) - $signed(sext_ln73_1388_fu_5323_p1));

assign sub_ln73_1058_fu_5351_p2 = ($signed(sub_ln73_1057_fu_5345_p2) - $signed(sext_ln73_1386_fu_5306_p1));

assign sub_ln73_1059_fu_5428_p2 = ($signed(sext_ln73_1394_fu_5412_p1) - $signed(sext_ln73_1395_fu_5424_p1));

assign sub_ln73_1060_fu_5446_p2 = ($signed(sext_ln73_1395_fu_5424_p1) - $signed(sext_ln73_1396_fu_5442_p1));

assign sub_ln73_1061_fu_5492_p2 = ($signed(sext_ln73_1398_fu_5476_p1) - $signed(sext_ln73_1399_fu_5488_p1));

assign sub_ln73_1062_fu_5510_p2 = ($signed(13'd0) - $signed(sext_ln73_1400_fu_5506_p1));

assign sub_ln73_1063_fu_5516_p2 = ($signed(sext_ln73_1399_fu_5488_p1) - $signed(sext_ln73_1398_fu_5476_p1));

assign sub_ln73_1064_fu_5559_p2 = ($signed(sext_ln73_1403_fu_5543_p1) - $signed(sext_ln73_1404_fu_5555_p1));

assign sub_ln73_1065_fu_5577_p2 = ($signed(sext_ln73_1401_fu_5526_p1) - $signed(sext_ln73_1403_fu_5543_p1));

assign sub_ln73_1066_fu_5611_p2 = ($signed(11'd0) - $signed(sext_ln73_1407_fu_5607_p1));

assign sub_ln73_1067_fu_5643_p2 = ($signed(11'd0) - $signed(sext_ln73_1409_fu_5639_p1));

assign sub_ln73_1068_fu_5649_p2 = ($signed(sub_ln73_1067_fu_5643_p2) - $signed(sext_ln73_1408_fu_5627_p1));

assign sub_ln73_1069_fu_5679_p2 = ($signed(sext_ln73_1410_fu_5663_p1) - $signed(sext_ln73_1411_fu_5675_p1));

assign sub_ln73_1070_fu_5735_p2 = ($signed(sext_ln73_1414_fu_5719_p1) - $signed(sext_ln73_1415_fu_5731_p1));

assign sub_ln73_1071_fu_5783_p2 = ($signed(sext_ln73_1416_fu_5745_p1) - $signed(sext_ln73_1418_fu_5761_p1));

assign sub_ln73_1072_fu_5807_p2 = ($signed(sext_ln73_1418_fu_5761_p1) - $signed(sext_ln73_1419_fu_5773_p1));

assign sub_ln73_1073_fu_5837_p2 = ($signed(sext_ln73_1421_fu_5817_p1) - $signed(sext_ln73_1423_fu_5833_p1));

assign sub_ln73_1074_fu_5855_p2 = ($signed(sext_ln73_1422_fu_5821_p1) - $signed(sext_ln73_1424_fu_5851_p1));

assign sub_ln73_1075_fu_5861_p2 = ($signed(12'd0) - $signed(sext_ln73_1423_fu_5833_p1));

assign sub_ln73_1076_fu_5883_p2 = ($signed(sub_ln73_1075_fu_5861_p2) - $signed(sext_ln73_1426_fu_5879_p1));

assign sub_ln73_1077_fu_5889_p2 = ($signed(sext_ln73_1426_fu_5879_p1) - $signed(sext_ln73_1423_fu_5833_p1));

assign sub_ln73_1078_fu_5927_p2 = ($signed(sext_ln73_1431_fu_5923_p1) - $signed(sext_ln73_1430_fu_5911_p1));

assign sub_ln73_1079_fu_6819_p2 = ($signed(12'd0) - $signed(sext_ln73_1432_fu_6815_p1));

assign sub_ln73_1080_fu_6836_p2 = ($signed(sub_ln73_1079_fu_6819_p2) - $signed(sext_ln73_1433_fu_6832_p1));

assign sub_ln73_1081_fu_6842_p2 = ($signed(sext_ln73_1432_fu_6815_p1) - $signed(sext_ln73_1429_fu_6805_p1));

assign sub_ln73_1082_fu_5937_p2 = ($signed(sext_ln73_1427_fu_5899_p1) - $signed(sext_ln73_1434_fu_5933_p1));

assign sub_ln73_1083_fu_5987_p2 = ($signed(sext_ln73_1436_fu_5959_p1) - $signed(sext_ln73_1435_fu_5947_p1));

assign sub_ln73_1084_fu_6019_p2 = ($signed(sext_ln73_1439_fu_6009_p1) - $signed(sext_ln73_1438_fu_5997_p1));

assign sub_ln73_1085_fu_6873_p2 = ($signed(sext_ln73_1441_fu_6859_p1) - $signed(sext_ln73_1443_fu_6869_p1));

assign sub_ln73_1086_fu_6046_p2 = ($signed(12'd0) - $signed(sext_ln73_1444_fu_6042_p1));

assign sub_ln73_1087_fu_6064_p2 = ($signed(sub_ln73_1086_fu_6046_p2) - $signed(sext_ln73_1445_fu_6060_p1));

assign sub_ln73_1088_fu_6879_p2 = ($signed(sext_ln73_1443_fu_6869_p1) - $signed(sext_ln73_1441_fu_6859_p1));

assign sub_ln73_1089_fu_6925_p2 = ($signed(sext_ln73_1448_fu_6921_p1) - $signed(sext_ln73_1447_fu_6909_p1));

assign sub_ln73_1090_fu_6943_p2 = ($signed(sext_ln73_1449_fu_6939_p1) - $signed(sext_ln73_1446_fu_6889_p1));

assign sub_ln73_1091_fu_6986_p2 = ($signed(sext_ln73_1453_fu_6982_p1) - $signed(sext_ln73_1452_fu_6970_p1));

assign sub_ln73_1092_fu_7020_p2 = ($signed(sext_ln73_1456_fu_7016_p1) - $signed(sext_ln73_1454_fu_7000_p1));

assign sub_ln73_1093_fu_7026_p2 = ($signed(sext_ln73_1455_fu_7012_p1) - $signed(sext_ln73_1451_fu_6958_p1));

assign sub_ln73_1094_fu_7046_p2 = ($signed(sext_ln73_1457_fu_7032_p1) - $signed(sext_ln73_1459_fu_7042_p1));

assign sub_ln73_1095_fu_7094_p2 = ($signed(sext_ln73_1465_fu_7079_p1) - $signed(sext_ln73_1466_fu_7090_p1));

assign sub_ln73_1096_fu_7100_p2 = ($signed(sext_ln73_1461_fu_7052_p1) - $signed(sext_ln73_1464_fu_7062_p1));

assign sub_ln73_1097_fu_7131_p2 = ($signed(sext_ln73_1470_fu_7127_p1) - $signed(sext_ln73_1469_fu_7116_p1));

assign sub_ln73_1098_fu_7148_p2 = ($signed(11'd0) - $signed(sext_ln73_1471_fu_7144_p1));

assign sub_ln73_1099_fu_7154_p2 = ($signed(sub_ln73_1098_fu_7148_p2) - $signed(sext_ln73_1468_fu_7106_p1));

assign sub_ln73_1100_fu_7185_p2 = ($signed(sext_ln73_1474_fu_7181_p1) - $signed(sext_ln73_1472_fu_7164_p1));

assign sub_ln73_1101_fu_7191_p2 = ($signed(sext_ln73_1472_fu_7164_p1) - $signed(sext_ln73_1474_fu_7181_p1));

assign sub_ln73_1102_fu_7197_p2 = ($signed(11'd0) - $signed(sext_ln73_1474_fu_7181_p1));

assign sub_ln73_1103_fu_7203_p2 = ($signed(sub_ln73_1102_fu_7197_p2) - $signed(sext_ln73_1472_fu_7164_p1));

assign sub_ln73_1104_fu_7229_p2 = ($signed(11'd0) - $signed(sext_ln73_1476_fu_7225_p1));

assign sub_ln73_1105_fu_7235_p2 = ($signed(sub_ln73_1104_fu_7229_p2) - $signed(sext_ln73_1475_fu_7213_p1));

assign sub_ln73_1106_fu_7265_p2 = ($signed(sext_ln73_1477_fu_7249_p1) - $signed(sext_ln73_1478_fu_7261_p1));

assign sub_ln73_1107_fu_7271_p2 = ($signed(12'd0) - $signed(sext_ln73_1477_fu_7249_p1));

assign sub_ln73_1108_fu_7277_p2 = ($signed(sub_ln73_1107_fu_7271_p2) - $signed(sext_ln73_1478_fu_7261_p1));

assign sub_ln73_fu_5063_p2 = ($signed(12'd0) - $signed(sext_ln73_1369_fu_5059_p1));

assign tmp1986_i_fu_6271_p2 = ($signed(p_cast_i_fu_6267_p1) + $signed(a_56_cast93_i_fu_6257_p1));

assign tmp_fu_6277_p3 = {{tmp1986_i_fu_6271_p2}, {2'd0}};

always @ (posedge ap_clk) begin
    sub_ln73_1072_reg_7887[0] <= 1'b0;
    sub_ln73_1077_reg_7892[0] <= 1'b0;
    shl_ln73_698_reg_7905[1:0] <= 2'b00;
    add_ln73_92_reg_7915[0] <= 1'b0;
    shl_ln73_703_reg_7925[1:0] <= 2'b00;
    sext_ln73_1444_reg_7936[2:0] <= 3'b000;
    sub_ln58_654_reg_7968[1:0] <= 2'b00;
end

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_22_14_5_3_0_config2_mult_s
