// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_i,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_i,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6_ap_vld,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_i;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld;
input  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld;
input  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld;
input  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o_ap_vld;
output  [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
output   void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7_ap_vld;
input  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_i;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o_ap_vld;
output  [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6;
output   p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6_ap_vld;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld;
reg[7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld;
reg[7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld;
reg[7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o_ap_vld;
reg void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7_ap_vld;
reg[7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o_ap_vld;
reg p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_q0;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
end

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_we0),
    .d0(p_read),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_q0)
);

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_we0),
    .d0(p_read1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_q0)
);

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_we0),
    .d0(p_read2),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_q0)
);

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_we0),
    .d0(p_read3),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_q0)
);

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_we0),
    .d0(p_read4),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_q0)
);

myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s_void_pooling2d_cl_strfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_we0),
    .d0(p_read5),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_q0;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_q0;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o = p_read4;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o = p_read3;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o = p_read2;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o = p_read1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o = p_read;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o = p_read5;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_q0;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_q0;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_q0;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o = void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_q0;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld = 1'b1;
    end else begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_ce))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_6u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_10 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_4_i;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_11 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_5_i;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_6 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_s_i;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_7 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_1_i;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_8 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_2_i;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_9 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_3_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_12_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi1EL9ap_q_mode4EL9ap_13_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_i;

endmodule //myproject_shift_line_buffer_array_ap_fixed_8_1_4_0_0_6u_config5_s
