// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer11_out_dout,
        layer11_out_num_data_valid,
        layer11_out_fifo_cap,
        layer11_out_empty_n,
        layer11_out_read,
        layer13_out_din,
        layer13_out_num_data_valid,
        layer13_out_fifo_cap,
        layer13_out_full_n,
        layer13_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [399:0] layer11_out_dout;
input  [1:0] layer11_out_num_data_valid;
input  [1:0] layer11_out_fifo_cap;
input   layer11_out_empty_n;
output   layer11_out_read;
output  [543:0] layer13_out_din;
input  [1:0] layer13_out_num_data_valid;
input  [1:0] layer13_out_fifo_cap;
input   layer13_out_full_n;
output   layer13_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer11_out_read;
reg layer13_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer11_out_blk_n;
reg    layer13_out_blk_n;
wire    ap_CS_fsm_state2;
wire  signed [24:0] a_fu_141_p4;
reg  signed [24:0] a_reg_865;
reg    ap_block_state1;
wire  signed [24:0] a_1_fu_151_p4;
reg  signed [24:0] a_1_reg_870;
wire  signed [24:0] a_2_fu_161_p4;
reg  signed [24:0] a_2_reg_875;
wire  signed [24:0] a_3_fu_171_p4;
reg  signed [24:0] a_3_reg_880;
reg  signed [24:0] a_4_reg_885;
wire   [24:0] trunc_ln73_fu_191_p1;
reg   [24:0] trunc_ln73_reg_891;
reg   [24:0] tmp_2_reg_896;
wire   [25:0] add_ln42_16_fu_209_p2;
reg   [25:0] add_ln42_16_reg_902;
wire   [25:0] add_ln42_17_fu_219_p2;
reg   [25:0] add_ln42_17_reg_907;
reg   [24:0] tmp_6_reg_912;
wire   [25:0] add_ln42_18_fu_239_p2;
reg   [25:0] add_ln42_18_reg_918;
reg   [24:0] tmp_9_reg_923;
reg   [24:0] tmp_s_reg_929;
reg   [24:0] tmp_1_reg_935;
wire   [25:0] add_ln42_19_fu_279_p2;
reg   [25:0] add_ln42_19_reg_941;
reg   [24:0] tmp_3_reg_946;
reg   [24:0] tmp_4_reg_951;
reg   [24:0] tmp_5_reg_957;
reg   [24:0] tmp_7_reg_963;
reg   [24:0] tmp_8_reg_968;
wire  signed [25:0] sext_ln73_2_fu_205_p1;
wire  signed [25:0] sext_ln73_4_fu_215_p1;
wire  signed [25:0] sext_ln73_8_fu_235_p1;
wire  signed [25:0] sext_ln73_16_fu_275_p1;
wire   [26:0] shl_ln_fu_335_p3;
wire  signed [27:0] sext_ln42_11_fu_342_p1;
wire   [27:0] add_ln42_fu_346_p2;
wire   [27:0] and_ln_fu_356_p3;
wire   [25:0] and_ln73_1_fu_367_p3;
wire  signed [28:0] sext_ln73_fu_363_p1;
wire  signed [28:0] sext_ln73_1_fu_374_p1;
wire   [28:0] sub_ln73_fu_378_p2;
wire   [28:0] add_ln42_1_fu_384_p2;
wire   [26:0] shl_ln73_1_fu_394_p3;
wire  signed [27:0] sext_ln42_14_fu_405_p1;
wire  signed [27:0] sext_ln73_3_fu_401_p1;
wire   [26:0] shl_ln73_2_fu_414_p3;
wire  signed [27:0] sext_ln42_15_fu_425_p1;
wire  signed [27:0] sext_ln73_5_fu_421_p1;
wire   [27:0] add_ln42_3_fu_428_p2;
wire   [27:0] and_ln73_2_fu_438_p3;
wire   [25:0] and_ln73_3_fu_449_p3;
wire  signed [28:0] sext_ln73_6_fu_445_p1;
wire  signed [28:0] sext_ln73_7_fu_456_p1;
wire   [28:0] sub_ln73_1_fu_460_p2;
wire   [28:0] add_ln42_4_fu_466_p2;
wire   [26:0] shl_ln73_3_fu_476_p3;
wire  signed [27:0] sext_ln42_16_fu_487_p1;
wire  signed [27:0] sext_ln73_9_fu_483_p1;
wire   [27:0] add_ln42_5_fu_490_p2;
wire   [27:0] and_ln73_4_fu_500_p3;
wire   [25:0] and_ln73_5_fu_511_p3;
wire  signed [28:0] sext_ln73_10_fu_507_p1;
wire  signed [28:0] sext_ln73_11_fu_518_p1;
wire   [28:0] sub_ln73_2_fu_522_p2;
wire   [28:0] add_ln42_6_fu_528_p2;
wire   [27:0] and_ln73_6_fu_538_p3;
wire   [25:0] and_ln73_7_fu_549_p3;
wire  signed [28:0] sext_ln73_12_fu_545_p1;
wire  signed [28:0] sext_ln73_13_fu_556_p1;
wire   [28:0] sub_ln73_3_fu_560_p2;
wire   [28:0] add_ln42_7_fu_566_p2;
wire   [27:0] and_ln73_8_fu_576_p3;
wire   [25:0] and_ln73_9_fu_587_p3;
wire  signed [28:0] sext_ln73_14_fu_583_p1;
wire  signed [28:0] sext_ln73_15_fu_594_p1;
wire   [28:0] sub_ln73_4_fu_598_p2;
wire   [28:0] add_ln42_8_fu_604_p2;
wire   [26:0] shl_ln73_4_fu_614_p3;
wire  signed [27:0] sext_ln42_17_fu_625_p1;
wire  signed [27:0] sext_ln73_17_fu_621_p1;
wire   [27:0] add_ln42_9_fu_628_p2;
wire   [26:0] and_ln73_s_fu_638_p3;
wire  signed [27:0] sext_ln42_12_fu_645_p1;
wire   [27:0] and_ln73_10_fu_655_p3;
wire   [25:0] and_ln73_11_fu_666_p3;
wire  signed [28:0] sext_ln73_18_fu_662_p1;
wire  signed [28:0] sext_ln73_19_fu_673_p1;
wire   [28:0] sub_ln73_5_fu_677_p2;
wire   [28:0] add_ln42_11_fu_683_p2;
wire   [27:0] and_ln73_12_fu_693_p3;
wire   [25:0] and_ln73_13_fu_704_p3;
wire  signed [28:0] sext_ln73_20_fu_700_p1;
wire  signed [28:0] sext_ln73_21_fu_711_p1;
wire   [28:0] sub_ln73_6_fu_715_p2;
wire   [27:0] shl_ln73_5_fu_730_p3;
wire  signed [28:0] sext_ln73_23_fu_737_p1;
wire  signed [28:0] sext_ln73_22_fu_727_p1;
wire   [28:0] sub_ln73_7_fu_741_p2;
wire   [28:0] add_ln42_13_fu_747_p2;
wire   [26:0] and_ln73_14_fu_757_p3;
wire  signed [27:0] sext_ln42_13_fu_764_p1;
wire   [27:0] and_ln73_15_fu_774_p3;
wire   [25:0] and_ln73_16_fu_785_p3;
wire  signed [28:0] sext_ln73_24_fu_781_p1;
wire  signed [28:0] sext_ln73_25_fu_792_p1;
wire   [28:0] sub_ln73_8_fu_796_p2;
wire   [27:0] add_ln42_2_fu_408_p2;
wire   [27:0] add_ln42_10_fu_649_p2;
wire   [28:0] add_ln42_12_fu_721_p2;
wire   [27:0] add_ln42_14_fu_768_p2;
wire   [28:0] add_ln42_15_fu_802_p2;
wire  signed [33:0] sext_ln46_3_fu_820_p1;
wire  signed [33:0] sext_ln42_10_fu_753_p1;
wire  signed [33:0] sext_ln46_2_fu_816_p1;
wire  signed [33:0] sext_ln42_9_fu_689_p1;
wire  signed [33:0] sext_ln46_1_fu_812_p1;
wire  signed [33:0] sext_ln42_8_fu_634_p1;
wire  signed [33:0] sext_ln42_7_fu_610_p1;
wire  signed [33:0] sext_ln42_6_fu_572_p1;
wire  signed [33:0] sext_ln42_5_fu_534_p1;
wire  signed [33:0] sext_ln42_4_fu_496_p1;
wire  signed [33:0] sext_ln42_3_fu_472_p1;
wire  signed [33:0] sext_ln42_2_fu_434_p1;
wire  signed [33:0] sext_ln46_fu_808_p1;
wire  signed [33:0] sext_ln42_1_fu_390_p1;
wire  signed [33:0] sext_ln42_fu_352_p1;
wire   [538:0] tmp_fu_824_p17;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer13_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        a_1_reg_870 <= {{layer11_out_dout[99:75]}};
        a_2_reg_875 <= {{layer11_out_dout[149:125]}};
        a_3_reg_880 <= {{layer11_out_dout[249:225]}};
        a_4_reg_885 <= {{layer11_out_dout[349:325]}};
        a_reg_865 <= {{layer11_out_dout[74:50]}};
        add_ln42_16_reg_902 <= add_ln42_16_fu_209_p2;
        add_ln42_17_reg_907 <= add_ln42_17_fu_219_p2;
        add_ln42_18_reg_918 <= add_ln42_18_fu_239_p2;
        add_ln42_19_reg_941 <= add_ln42_19_fu_279_p2;
        tmp_1_reg_935 <= {{layer11_out_dout[224:200]}};
        tmp_2_reg_896 <= {{layer11_out_dout[49:25]}};
        tmp_3_reg_946 <= {{layer11_out_dout[274:250]}};
        tmp_4_reg_951 <= {{layer11_out_dout[299:275]}};
        tmp_5_reg_957 <= {{layer11_out_dout[324:300]}};
        tmp_6_reg_912 <= {{layer11_out_dout[124:100]}};
        tmp_7_reg_963 <= {{layer11_out_dout[374:350]}};
        tmp_8_reg_968 <= {{layer11_out_dout[399:375]}};
        tmp_9_reg_923 <= {{layer11_out_dout[174:150]}};
        tmp_s_reg_929 <= {{layer11_out_dout[199:175]}};
        trunc_ln73_reg_891 <= trunc_ln73_fu_191_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer13_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer13_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer13_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_blk_n = layer11_out_empty_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_read = 1'b1;
    end else begin
        layer11_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer13_out_blk_n = layer13_out_full_n;
    end else begin
        layer13_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer13_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_write = 1'b1;
    end else begin
        layer13_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer13_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_151_p4 = {{layer11_out_dout[99:75]}};

assign a_2_fu_161_p4 = {{layer11_out_dout[149:125]}};

assign a_3_fu_171_p4 = {{layer11_out_dout[249:225]}};

assign a_fu_141_p4 = {{layer11_out_dout[74:50]}};

assign add_ln42_10_fu_649_p2 = ($signed(sext_ln42_12_fu_645_p1) + $signed(28'd20480));

assign add_ln42_11_fu_683_p2 = (sub_ln73_5_fu_677_p2 + 29'd12288);

assign add_ln42_12_fu_721_p2 = ($signed(sub_ln73_6_fu_715_p2) + $signed(29'd536864768));

assign add_ln42_13_fu_747_p2 = (sub_ln73_7_fu_741_p2 + 29'd36864);

assign add_ln42_14_fu_768_p2 = ($signed(sext_ln42_13_fu_764_p1) + $signed(28'd268421120));

assign add_ln42_15_fu_802_p2 = (sub_ln73_8_fu_796_p2 + 29'd20480);

assign add_ln42_16_fu_209_p2 = ($signed(sext_ln73_2_fu_205_p1) + $signed(26'd2048));

assign add_ln42_17_fu_219_p2 = ($signed(sext_ln73_4_fu_215_p1) + $signed(26'd20480));

assign add_ln42_18_fu_239_p2 = ($signed(sext_ln73_8_fu_235_p1) + $signed(26'd14336));

assign add_ln42_19_fu_279_p2 = ($signed(sext_ln73_16_fu_275_p1) + $signed(26'd67094528));

assign add_ln42_1_fu_384_p2 = (sub_ln73_fu_378_p2 + 29'd12288);

assign add_ln42_2_fu_408_p2 = ($signed(sext_ln42_14_fu_405_p1) + $signed(sext_ln73_3_fu_401_p1));

assign add_ln42_3_fu_428_p2 = ($signed(sext_ln42_15_fu_425_p1) + $signed(sext_ln73_5_fu_421_p1));

assign add_ln42_4_fu_466_p2 = (sub_ln73_1_fu_460_p2 + 29'd32768);

assign add_ln42_5_fu_490_p2 = ($signed(sext_ln42_16_fu_487_p1) + $signed(sext_ln73_9_fu_483_p1));

assign add_ln42_6_fu_528_p2 = ($signed(sub_ln73_2_fu_522_p2) + $signed(29'd536858624));

assign add_ln42_7_fu_566_p2 = ($signed(sub_ln73_3_fu_560_p2) + $signed(29'd536864768));

assign add_ln42_8_fu_604_p2 = ($signed(sub_ln73_4_fu_598_p2) + $signed(29'd536852480));

assign add_ln42_9_fu_628_p2 = ($signed(sext_ln42_17_fu_625_p1) + $signed(sext_ln73_17_fu_621_p1));

assign add_ln42_fu_346_p2 = ($signed(sext_ln42_11_fu_342_p1) + $signed(28'd18432));

assign and_ln73_10_fu_655_p3 = {{tmp_4_reg_951}, {3'd0}};

assign and_ln73_11_fu_666_p3 = {{tmp_4_reg_951}, {1'd0}};

assign and_ln73_12_fu_693_p3 = {{tmp_5_reg_957}, {3'd0}};

assign and_ln73_13_fu_704_p3 = {{tmp_5_reg_957}, {1'd0}};

assign and_ln73_14_fu_757_p3 = {{tmp_7_reg_963}, {2'd0}};

assign and_ln73_15_fu_774_p3 = {{tmp_8_reg_968}, {3'd0}};

assign and_ln73_16_fu_785_p3 = {{tmp_8_reg_968}, {1'd0}};

assign and_ln73_1_fu_367_p3 = {{tmp_2_reg_896}, {1'd0}};

assign and_ln73_2_fu_438_p3 = {{tmp_6_reg_912}, {3'd0}};

assign and_ln73_3_fu_449_p3 = {{tmp_6_reg_912}, {1'd0}};

assign and_ln73_4_fu_500_p3 = {{tmp_9_reg_923}, {3'd0}};

assign and_ln73_5_fu_511_p3 = {{tmp_9_reg_923}, {1'd0}};

assign and_ln73_6_fu_538_p3 = {{tmp_s_reg_929}, {3'd0}};

assign and_ln73_7_fu_549_p3 = {{tmp_s_reg_929}, {1'd0}};

assign and_ln73_8_fu_576_p3 = {{tmp_1_reg_935}, {3'd0}};

assign and_ln73_9_fu_587_p3 = {{tmp_1_reg_935}, {1'd0}};

assign and_ln73_s_fu_638_p3 = {{tmp_3_reg_946}, {2'd0}};

assign and_ln_fu_356_p3 = {{tmp_2_reg_896}, {3'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer13_out_din = $signed(tmp_fu_824_p17);

assign sext_ln42_10_fu_753_p1 = $signed(add_ln42_13_fu_747_p2);

assign sext_ln42_11_fu_342_p1 = $signed(shl_ln_fu_335_p3);

assign sext_ln42_12_fu_645_p1 = $signed(and_ln73_s_fu_638_p3);

assign sext_ln42_13_fu_764_p1 = $signed(and_ln73_14_fu_757_p3);

assign sext_ln42_14_fu_405_p1 = $signed(add_ln42_16_reg_902);

assign sext_ln42_15_fu_425_p1 = $signed(add_ln42_17_reg_907);

assign sext_ln42_16_fu_487_p1 = $signed(add_ln42_18_reg_918);

assign sext_ln42_17_fu_625_p1 = $signed(add_ln42_19_reg_941);

assign sext_ln42_1_fu_390_p1 = $signed(add_ln42_1_fu_384_p2);

assign sext_ln42_2_fu_434_p1 = $signed(add_ln42_3_fu_428_p2);

assign sext_ln42_3_fu_472_p1 = $signed(add_ln42_4_fu_466_p2);

assign sext_ln42_4_fu_496_p1 = $signed(add_ln42_5_fu_490_p2);

assign sext_ln42_5_fu_534_p1 = $signed(add_ln42_6_fu_528_p2);

assign sext_ln42_6_fu_572_p1 = $signed(add_ln42_7_fu_566_p2);

assign sext_ln42_7_fu_610_p1 = $signed(add_ln42_8_fu_604_p2);

assign sext_ln42_8_fu_634_p1 = $signed(add_ln42_9_fu_628_p2);

assign sext_ln42_9_fu_689_p1 = $signed(add_ln42_11_fu_683_p2);

assign sext_ln42_fu_352_p1 = $signed(add_ln42_fu_346_p2);

assign sext_ln46_1_fu_812_p1 = $signed(add_ln42_10_fu_649_p2);

assign sext_ln46_2_fu_816_p1 = $signed(add_ln42_12_fu_721_p2);

assign sext_ln46_3_fu_820_p1 = $signed(add_ln42_14_fu_768_p2);

assign sext_ln46_fu_808_p1 = $signed(add_ln42_2_fu_408_p2);

assign sext_ln73_10_fu_507_p1 = $signed(and_ln73_4_fu_500_p3);

assign sext_ln73_11_fu_518_p1 = $signed(and_ln73_5_fu_511_p3);

assign sext_ln73_12_fu_545_p1 = $signed(and_ln73_6_fu_538_p3);

assign sext_ln73_13_fu_556_p1 = $signed(and_ln73_7_fu_549_p3);

assign sext_ln73_14_fu_583_p1 = $signed(and_ln73_8_fu_576_p3);

assign sext_ln73_15_fu_594_p1 = $signed(and_ln73_9_fu_587_p3);

assign sext_ln73_16_fu_275_p1 = a_3_fu_171_p4;

assign sext_ln73_17_fu_621_p1 = $signed(shl_ln73_4_fu_614_p3);

assign sext_ln73_18_fu_662_p1 = $signed(and_ln73_10_fu_655_p3);

assign sext_ln73_19_fu_673_p1 = $signed(and_ln73_11_fu_666_p3);

assign sext_ln73_1_fu_374_p1 = $signed(and_ln73_1_fu_367_p3);

assign sext_ln73_20_fu_700_p1 = $signed(and_ln73_12_fu_693_p3);

assign sext_ln73_21_fu_711_p1 = $signed(and_ln73_13_fu_704_p3);

assign sext_ln73_22_fu_727_p1 = a_4_reg_885;

assign sext_ln73_23_fu_737_p1 = $signed(shl_ln73_5_fu_730_p3);

assign sext_ln73_24_fu_781_p1 = $signed(and_ln73_15_fu_774_p3);

assign sext_ln73_25_fu_792_p1 = $signed(and_ln73_16_fu_785_p3);

assign sext_ln73_2_fu_205_p1 = a_fu_141_p4;

assign sext_ln73_3_fu_401_p1 = $signed(shl_ln73_1_fu_394_p3);

assign sext_ln73_4_fu_215_p1 = a_1_fu_151_p4;

assign sext_ln73_5_fu_421_p1 = $signed(shl_ln73_2_fu_414_p3);

assign sext_ln73_6_fu_445_p1 = $signed(and_ln73_2_fu_438_p3);

assign sext_ln73_7_fu_456_p1 = $signed(and_ln73_3_fu_449_p3);

assign sext_ln73_8_fu_235_p1 = a_2_fu_161_p4;

assign sext_ln73_9_fu_483_p1 = $signed(shl_ln73_3_fu_476_p3);

assign sext_ln73_fu_363_p1 = $signed(and_ln_fu_356_p3);

assign shl_ln73_1_fu_394_p3 = {{a_reg_865}, {2'd0}};

assign shl_ln73_2_fu_414_p3 = {{a_1_reg_870}, {2'd0}};

assign shl_ln73_3_fu_476_p3 = {{a_2_reg_875}, {2'd0}};

assign shl_ln73_4_fu_614_p3 = {{a_3_reg_880}, {2'd0}};

assign shl_ln73_5_fu_730_p3 = {{a_4_reg_885}, {3'd0}};

assign shl_ln_fu_335_p3 = {{trunc_ln73_reg_891}, {2'd0}};

assign start_out = real_start;

assign sub_ln73_1_fu_460_p2 = ($signed(sext_ln73_6_fu_445_p1) - $signed(sext_ln73_7_fu_456_p1));

assign sub_ln73_2_fu_522_p2 = ($signed(sext_ln73_10_fu_507_p1) - $signed(sext_ln73_11_fu_518_p1));

assign sub_ln73_3_fu_560_p2 = ($signed(sext_ln73_12_fu_545_p1) - $signed(sext_ln73_13_fu_556_p1));

assign sub_ln73_4_fu_598_p2 = ($signed(sext_ln73_14_fu_583_p1) - $signed(sext_ln73_15_fu_594_p1));

assign sub_ln73_5_fu_677_p2 = ($signed(sext_ln73_18_fu_662_p1) - $signed(sext_ln73_19_fu_673_p1));

assign sub_ln73_6_fu_715_p2 = ($signed(sext_ln73_20_fu_700_p1) - $signed(sext_ln73_21_fu_711_p1));

assign sub_ln73_7_fu_741_p2 = ($signed(sext_ln73_23_fu_737_p1) - $signed(sext_ln73_22_fu_727_p1));

assign sub_ln73_8_fu_796_p2 = ($signed(sext_ln73_24_fu_781_p1) - $signed(sext_ln73_25_fu_792_p1));

assign sub_ln73_fu_378_p2 = ($signed(sext_ln73_fu_363_p1) - $signed(sext_ln73_1_fu_374_p1));

assign tmp_fu_824_p17 = {{{{{{{{{{{{{{{{add_ln42_15_fu_802_p2}, {sext_ln46_3_fu_820_p1}}, {sext_ln42_10_fu_753_p1}}, {sext_ln46_2_fu_816_p1}}, {sext_ln42_9_fu_689_p1}}, {sext_ln46_1_fu_812_p1}}, {sext_ln42_8_fu_634_p1}}, {sext_ln42_7_fu_610_p1}}, {sext_ln42_6_fu_572_p1}}, {sext_ln42_5_fu_534_p1}}, {sext_ln42_4_fu_496_p1}}, {sext_ln42_3_fu_472_p1}}, {sext_ln42_2_fu_434_p1}}, {sext_ln46_fu_808_p1}}, {sext_ln42_1_fu_390_p1}}, {sext_ln42_fu_352_p1}};

assign trunc_ln73_fu_191_p1 = layer11_out_dout[24:0];

endmodule //myproject_normalize_array_ap_fixed_16u_array_ap_fixed_34_19_5_3_0_16u_config13_s
